### ISSUE TITLE
Albany compilation error: stk::CommAll not found

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#100]
It looks like something changed in the STK Trilinos package yesterday (3/29), causing a compilation error.  Here is the error:

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=50632 

It happened on my Linux workstation, camobap, as well as ride: 

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=50621

I have verified that the problem does not show up when pulling Trilinos develop from midnight on 3/29, which suggests the problematic code was introduced during the day on 3/29.

**Comment by lxmota** [comment]
Welcome to my world, where STK is the source of a lot of broken builds.

I noticed this last night, and I thought it would be fixed eventually.

**Comment by ikalash** [comment]
Yes...  this is one of the issues I asked you about on the phone when I called, but at that point I hadn't realized it was a bug in STK, I thought it was an issue with my configure scripts.
