### ISSUE TITLE
OpenMPI library link with LCM scripts on CEE

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#104]
as reported by @jwfoulk 

One of the tests fails on the CEE Lan - SurfaceElementLocking - because algebra cannot be executed. The reason is that the system libraries come before the libraries used to compile trilinos. I think the Fedora build relies on this but this will lead to issues on the CEE lan and building for the clusters. For example, I get the following error after loading sems and serial-gcc-release:

[jwfoulk@ceerws2210 SurfaceElementLocking]$ algebra outNoVolJ.e outNoVolJ.alg.e
algebra: symbol lookup error: /usr/lib64/openmpi/lib/libmpi.so.1: undefined symbol: opal_memchecker_base_isdefined

algebra is in LCM/trilinos-install-serial-gcc-release/bin/algebra

There are multiple shared object libraries in my path - that resulted from the gcc-serial-release module.

jwfoulk@ceerws2210 SurfaceElementLocking]$ echo $LD_LIBRARY_PATH
/usr/local/netcdf/lib:/usr/lib64/openmpi/lib:/scratch/jwfoulk/builds/LCM/trilinos-install-serial-gcc-release/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/6.1.0/base/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/4.4.7/base/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/superlu/4.3/gcc/6.1.0/base/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/superlu/4.3/gcc/4.4.7/base/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/parmetis/4.0.3/gcc/6.1.0/openmpi/1.8.7/parallel/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/parmetis/4.0.3/gcc/4.4.7/openmpi/1.8.7/parallel/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/6.1.0/openmpi/1.8.7/parallel/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/4.4.7/openmpi/1.8.7/parallel/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/6.1.0/openmpi/1.8.7/parallel/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/4.4.7/openmpi/1.8.7/parallel/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/zlib/1.2.8/gcc/6.1.0/base/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/zlib/1.2.8/gcc/4.4.7/base/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.63.0/gcc/6.1.0/base/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.63.0/gcc/4.4.7/base/lib:/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/6.1.0/openmpi/1.8.7/lib:/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.4.7/openmpi/1.8.7/lib:/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/6.1.0/base/lib64:/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/6.1.0/base/lib:/projects/sems/install/rhel6-x86_64/sems/utility/git/2.10.1/lib:/projects/sems/install/rhel6-x86_64/sems/utility/cmake/3.5.2/lib:/projects/sems/install/rhel6-x86_64/sems/compiler/python/2.7.9/lib

If I prepend the sems libraries:

export LD_LIBRARY_PATH=/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/6.1.0/openmpi/1.8.7/lib:$LD_LIBRARY_PATH

I can run algebra just fine. I think this will also come up again on cluster builds. Many thanks.

**Comment by ibaned** [comment]
Yea, the issue seems to be these entries:
```
/usr/local/netcdf/lib:/usr/lib64/openmpi/lib
```
They should not have appeared in a SEMS setup.
I'll look into this.

**Comment by ibaned** [comment]
Yep, there were unwanted paths in the `lcm/finalize` module. Commit ee9ee2a should fix this.

**Comment by jwfoulk** [comment]
Hi Dan - thanks again. Two more tests now pass and the serial-gcc-debug seems to now be rolling. Before the change, the configuration of debug was broken. I'll keep trying to get the tests clean on CEE. Cheers. -Jay
