### ISSUE TITLE
[[noreturn]] not supported by gcc 4.7.2

### ISSUE THREAD

**Issue by liz13** [gahansen/Albany#108]
Hello,
I am trying to compile Albany on RPI Blue Gene/Q machine. The newest compiler supported on this machine is gcc 4.7.2, it appears that the keyword [[noreturn]] is not supported by this compiler, below is the error message I receive.

```
In file included from /gpfs/u/home/PGES/PGESzhnl/scratch/Albany_2017/src/LCM/problems/ConstitutiveDriverProblem.cpp:7:0:
/gpfs/u/home/PGES/PGESzhnl/scratch/Albany_2017/src/./Albany_Utils.hpp:183:1: error: expected unqualified-id before ���[��� token
make[2]: *** [src/LCM/CMakeFiles/LCM.dir/problems/ConstitutiveDriverProblem.cpp.o] Error 1
```

**Comment by ibaned** [comment]
let me know if commit fe109c4 fixes this for you

**Comment by liz13** [comment]
Thanks Dan,

this commit works.

Thanks,
Zhen

**Comment by liz13** [comment]
Hello,
I am trying to run a solderball simulation using creep model with Albany on RPI Blue Gene/Q machine. The latest version of Albany couldn't not work with the restart files generated from the previous run due to the following notification.
```
! m->findField(name) failed at /gpfs/u/home/PGES/PGESzhnl/scratch/TRILINOS/src/SCOREC/apf/apf.cc + 57'. 
```

**Comment by ibaned** [comment]
Please open a separate issue for this.
