### ISSUE TITLE
consolidate QCAD and LCM MaterialDatabase objects

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#112]
There is something called a `QCAD::MaterialDatabase`, but it is part of the core of Albany and compiles with the demo problems. There is also `LCM::MaterialDatabase`, which supports YAML unlike the QCAD one, but only builds with LCM. Lets see if we can just have one Albany::MaterialDatabase that everyone uses.

**Comment by ibaned** [comment]
This is done, though its in a branch with lots of other changes. Hopefully the merge will happen soon.

**Comment by bartgol** [comment]
Agreed. 

In addition to this, personally, I don't like to see anything other than Albany_XYZ or PHAL_XYZ in the albany folders. If something is general enough to be in the main albany folders (src, src/disc, src/evaluators,src/responses, src/problems, src/utility) and always be compiled (and not package dependent), then it should be named with a generic prefix. If something is package dependent, then it should be contained in the subfolder of that package.

**Comment by ibaned** [comment]
I did change the prefix and the namespace to Albany, this bugs me too.

**Comment by ibaned** [comment]
I just pushed this change.
