### ISSUE TITLE
Improving adaptive time stepping for mechanics problems

### ISSUE THREAD

**Issue by jtostie** [gahansen/Albany#12]
Catching appropriate flags and passing them to NOX. Known issue with Schwarz right now, material model wants to cut the time step, but Schwarz is not honoring that. (NEED TO VERIFY)

Revisit algorithms employed for adaptive time stepping. May link with Tempus task.

**Comment by jtostie** [comment]
Jay Foulk is volunteering to add a simple test that employs the crystal plasticity model and attempts to cut the time step in a Schwarz coupling analysis.

**Comment by ikalash** [comment]
I believe the issue of time-stepping schemes not passed to NOX for Schwarz problems has been resolved.  @djlittl and @jwfoulk , can you please confirm?  If confirmed, I say we close out this issue.

**Comment by lxmota** [comment]
Yes, this has been fixed and is frequently used for crystal plasticity.
