### ISSUE TITLE
Add contact to LCM

### ISSUE THREAD

**Issue by knkarls** [gahansen/Albany#123]
I need to run simulations with contact for my research.

**Comment by lxmota** [comment]
@gahansen has added some capability for this, but I believe it's still in development.

Another possibility is to use the machinery we developed for Schwarz to keep track of contact surfaces. I mentioned this to @jtostie, @jwfoulk and @calleman21 some weeks ago.

We had some resources in the LCM project to do some work on contact, but regrettably we don't have them any more.

Still, the contact problem is very important, and we should try to address it.

**Comment by gahansen** [comment]
@knkaris and @lxmota - There is another issue related to contact in Albany/LCM (issue #117) . Please take a look and let me know what you think. If you support continuing along those lines, I'd suggest that we close this issue and continue comments on issue #117. Commit 731d917b7ddc0becd5ace39d0223ce4abbb70a5a is the first one targeting #117

**Comment by lxmota** [comment]
@knkarls @gahansen I agree that we should merge the issues. We had discussions about this long ago, so I would need to recall what mortar contact does. Perhaps it would be worthwhile to have an offline discussion or address this at the Albany teleconference.

**Comment by gahansen** [comment]
Duplicates issue #117.
