### ISSUE TITLE
Continuation for the Schwarz alternating method.

### ISSUE THREAD

**Issue by lxmota** [gahansen/Albany#126]
It appears that doing this through LOCA would be
too difficult. A suggested way to do this is through Anderson
acceleration, a variant of fixed point methods. But now that Tempus
is enabled, perhaps it would be easier to do continuation through
dynamics. Then quasi-static problems would be run as truly
quasi-static: very slow dynamic problems.

**Comment by ikalash** [comment]
I am in favor of this approach.

**Comment by lxmota** [comment]
This is working now with constant time stepping.
