### ISSUE TITLE
Investigate automatic detection of existence of parallel NetCDF in Albany build, and activation of "Use Serial Mesh" tests only if parallel NetCDF is found.

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#130]
This is a follow up to issue #102.

**Comment by ibaned** [comment]
trilinos/Trilinos#1359 indicates a way forward, I'll try to implement that.

**Comment by ibaned** [comment]
looks like I made a duplicate #140. lets focus on that one.
