### ISSUE TITLE
Albany does not compile when KOKKOS_UNDER_DEVELOPMENT is OFF and FELIX is ON

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#131]
I discovered today that it does not seem possible to compile the code when KOKKOS_UNDER_DEVELOPMENT is OFF and FELIX is ON.  For certain physics, to do debugging and performance comparisons, it would be worthwhile to be able to compile with KOKKOS_UNDER_DEVELOPMENT set to OFF, so this compilation error should be fixed.  If FELIX is meant to use only KOKKOS_UNDER_DEVELOPMENT=ON code, I suggest the code that is not within these ifdef guards is removed, so that KOKKOS_UNDER_DEVELOPMENT code is always what gets compiled.

**Comment by mperego** [comment]
This should be fixed by commit afc9cdc873f810da23.
