### ISSUE TITLE
Attain clean dashboard for Albany

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#135]
This issue was brought up at the Albany meeting in January.  Certain tests have been failing for awhile consistently.  These tests should either be fixed or removed, if they are no longer applicable.  This will make code easier to maintain / develop.

**Comment by ikalash** [comment]
One of the failing tests for a few weeks now has been Aeras_HydrostaticPureAdvection_1_noHV.  This fails with a Serial KokkosNode, and not an OpenMP or CUDA KokkosNode, interestingly enough.  The code computed nans with the Serial KokkosNode: 

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=2822337&build=52501

I have tracked this down to the following commit 0a95851b5362c9ec4c3731284af2a11534b5bb7d (be me).  This commit is what broke the tests.  I will attempt to track it down further and fix it tomorrow.

**Comment by ikalash** [comment]
@calleman21 : it looks like one of the CrystalPlasticity tests that was passing on my machine is now failing http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlyfailed&buildid=52878 .

**Comment by gahansen** [comment]
Through the efforts of many, we have a --mostly green-- test dashboard lately. The Clang tests have two failures with FPEs. The "SCOREC_J2Adapt_Verification_Tpetra" should start passing once a fix in NOX makes it over from the develop branch. I think the "MechWithHydrogenFastPath_surfaceDiffusion" test has a more fundamental problem. @jwfoulk and @lxmota - should we turn that one off for now until that problem is fixed?

**Comment by gahansen** [comment]
The intel compiler tests have several more FPEs / diffs. @jrobbin - can I help with the two ATO tests? @mperego - the FO_AIS_16km_MueLu test has an FPE. @jwfoulk @djlittl @calleman21 - there are several CrystalPlastivity tests failing with FPEs that trace out of the minitensor package. Would you be OK if I built a debug version, made a stack trace, and tried to track these down?

Thanks to everyone for their hard work in cleaning up the test dashboard!!!

**Comment by jwfoulk** [comment]
Hi Glen - yes - MechWithHydrogenFastPath_surfaceDiffusion uncovers a bug. The code was broken and we are struggling to find the solution. Although indicated in the input deck, separate evaluators are not being honored for separate element blocks. Consequently, bulk element blocks are being run through the surface element code. We need to fix it and I'm open to turning them off until we fix it and then we will turn them back on.

**Comment by mperego** [comment]
Test FO_AIS_16km appears to fail because of MueLu. MueLu team is looking into this
https://github.com/trilinos/Trilinos/issues/1542

**Comment by gahansen** [comment]
Per @jwfoulk , I just pushed commit 2643d302330d5480aac468f53e02406775f85caa that deactivates the *surfaceDiffusion test. The Clang and gcc nightly dashboards should now be all green (said cautiously).

We have 8 failing tests in the Intel build:

ATO:RegHeaviside_3D
ATOT:RegHeaviside_3D
FO_AIS_16km_MueLu
CrystalPlasticity_OrientationOnMesh
CrystalPlasticity_OrientationOnMesh_np4
CrystalPlasticity_OrientationNotOnMesh
CrystalPlasticity_OrientationNotOnMesh_np4
CrystalPlasticity_MultiFamily
 
The FO_* test is waiting on resolution of trilinos/Trilinos#1542 . Any volunteers to fix the ATO and CrystalPlasticity tests on this platform? I'll push a commit to turn these tests off on the Intel build later today if not.

CC: @ikalash @lxmota @calleman21 @ibaned @jrobbin @mperego

**Comment by ikalash** [comment]
I believe this has finally been attained!
