### ISSUE TITLE
Invalid parameter list issue in ATO Mitchell_3D test 

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#136]
It looks like there is a parameter list issue in the ATO Mitchell_3D test:

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=2824659&build=52558 

It looks like the same parameter list syntax appears in the following input files, so it should be changed/fixed there as well.

```
Mitchell_3D/nodal_nloptT.xml:    <ParameterList name="Topology">
Mitchell_3D/nodal_nlopt.xml:    <ParameterList name="Topology">
Mitchell_3D/element_nlopt.xml:    <ParameterList name="Topology">
Mitchell_3D/element_oc.xml:    <ParameterList name="Topology">
Modal_2D/nlopt_inputT.xml:    <ParameterList name="Topology">
Modal_2D/input.xml:    <ParameterList name="Topology">
Modal_2D/inputT.xml:    <ParameterList name="Topology">
Modal_2D/nlopt_input.xml:    <ParameterList name="Topology">
MultiLoadSet/element_nlopt.xml:    <ParameterList name="Topology">
MultiLoadSet/element_oc.xml:    <ParameterList name="Topology">
Mitchell_2D/input.xml:    <ParameterList name="Topology">
```

**Comment by gahansen** [comment]
@ikalash and @jrobbin : Is this test failure still an issue? I'll take a look if you can point me to the dashboard that shows this failing.

**Comment by ikalash** [comment]
It looks like this is no longer a problem based on the dashboard.  I will close the issue.
