### ISSUE TITLE
Have tests send output to screen to be sent to CDash 

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#137]
Some of the Albany tests (mostly LCM) write the output to a log file rather than to the screen.  It would be nice to have it be printed to the screen as well, so that one can see the output on the CDash site.

**Comment by gahansen** [comment]
Could we add an optional argument to the python tests scripts that is specified in the nightly tests that would "cat" the log files right after they are written? An idea along these lines might serve to post the output to CDash for just the dashboard runs without changing the behavior of tests in the interactive LCM workflow.

I'll mention @ibaned and @lxmota on this comment for their thoughts.

**Comment by ibaned** [comment]
Yes, someones gotta do this. I was just browsing the dashboard's new failing tests, and got zero useful information due to the python scripts.

**Comment by lxmota** [comment]
Let me take a look at this for LCM. If all that is required is that the output log goes to screen, Glen's suggestion might be the easiest to implement.

**Comment by calleman21** [comment]
Adding a print statement to the python script that runs the tests seems to work, and it only affects the ctest output with the -V flag, or (hopefully) on CDash. Thanks to @ikalash for helping me figure that out. I did this for the CrystalPlasticity tests, to start. I want to see how that works on the nightly tests before changing the default behavior for the rest.

**Comment by ikalash** [comment]
I believe I have fixed this for all the Albany basic tests (not including Peridigm, which I do not build / run), so I am going to close this issue.  I'm happy to propagate this fix to any tests I may have missed.
