### ISSUE TITLE
Disable "Serial Mesh" tests when TPL_Netcdf_PARALLEL=OFF

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#140]
In Albany, check this Trilinos option (if possible?) and disable all tests that rely on parallel NetCDF. Maybe we'll need a change to Trilinos to make that option available to downstream users.

This is @lxmota 's preferred solution for the problem that Fedora's installed NetCDF is not parallel.

**Comment by ibaned** [comment]
See trilinos/Trilinos#1359 for an approach.

**Comment by lxmota** [comment]
@ibaned We can close this, right?

**Comment by ibaned** [comment]
Yes, I think we've implemented this.

**Comment by ikalash** [comment]
@ibaned : it seems from this issue that the "Use Serial Mesh = true" tests should be turned off when Trilinos has been built with -DTPL_Netcdf_PARALLEL:BOOL=ON; is that right?  I am finding on a couple platforms where I am building that it does not work.  Are any additional flags required to turn off the tests?

**Comment by ikalash** [comment]
@ibaned : I had a typo in my comment above... I meant -DTPL_Netcdf_PARALLEL:BOOL=OFF .  It has been corrected. Sorry about the confusion.

**Comment by ikalash** [comment]
Follow up question: is anyone opposed to me adding a configure flag to Albany to turn off use serial mesh tests?  It would utilize logic @ibaned already put in (-d albany_iopx) but that seems to depend only on trilinos options.
