### ISSUE TITLE
basic tests failing due to PUMI PCU

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#141]
http://my.cdash.org/testDetails.php?test=31846558&build=1211992

I certainly haven't touched any PUMI-related stuff recently. @bgranzow  any ideas ?

**Comment by bgranzow** [comment]
I don't think any PUMI-related changes have happened in Albany recently, and it looks like the commit history for SCOREC/core is pretty sparse. Does this function still get called ?

https://github.com/gahansen/Albany/blob/master/src/disc/pumi/Albany_APFMeshStruct.hpp#L156

**Comment by ibaned** [comment]
Looks like @lxmota made a small mistake in changing all `#ifdef` to `#if defined` in 9a1f9b5. I just pushed a fix in 7290ea8. That should re-enable the call to `initialize_libraries` and fix these failing tests.

**Comment by lxmota** [comment]
Sorry about this.
