### ISSUE TITLE
Installation/test run errors

### ISSUE THREAD

**Issue by cmsande** [gahansen/Albany#149]
I am attempting to install Trilinos/Albany on a CEE lan machine and am running into errors when I run the albany test suite in my build directory. After having followed the instructions in the install pdf, I attempted to run the tests using ctest and get the following error: 

cannot connect to local mpd (/tmp/mpd2.console) possible causes:
   1. no mpd is running on this host
   2. an mpd is running but was started without a "console" (-n option)

I've rebuilt both albany and trilinos and no errors were indicated. Have I missed a step in setting up the proper environment? This error looks like it may have to do with mpi configurations, but I'm at a loss of what to do.

**Comment by ibaned** [comment]
Can you post what modules you loaded and what your configuration was?
It may also be quicker just to indicate which "install pdf" you are using. It may be outdated.

**Comment by cmsande** [comment]
I built the I believe I was following up-to-date installation instructions, from https://github.com/gahansen/Albany/blob/master/doc/LCM/install/INSTALL.pdf

I've been building the release version of trilinos/albany. I had loaded modules using
module load lcm/sems
module load release

The modules currently have loaded are: 

  1) lcm/common                    12) sems-boost/1.63.0/base
  2) sems-env                      13) sems-zlib/1.2.8/base
  3) sems-python/2.7.9             14) sems-hdf5/1.8.12/parallel
  4) sems-cmake/3.5.2              15) sems-netcdf/4.3.2/parallel
  5) sems-git/2.10.1               16) sems-parmetis/4.0.3/parallel
  6) lcm/sems                      17) sems-superlu/4.3/base
  7) lcm/serial                    18) sems-yaml_cpp/0.5.3/base
  8) sems-gcc/6.1.0                19) lcm/tpls
  9) lcm/gcc                       20) lcm/finalize
 10) lcm/release                   21) release
 11) sems-openmpi/1.8.7

**Comment by ibaned** [comment]
What CEE machine are you on?

**Comment by cmsande** [comment]
ceerws1102

**Comment by ibaned** [comment]
Your modules list include `sems-openmpi/1.8.7`, but this error is about MPD, which is a deprecated process manager used in old versions of MPICH.

It may be that you have an old version of MPICH on your system that is conflicting with what SEMS is supposed to give you.

Can you run
```bash
ctest -VV
```
and post the command line being run for the first test? That should show you the path to `mpirun` that it is trying to use.

**Comment by ibaned** [comment]
The output of
```bash
echo $PATH
```
may also be helpful

**Comment by cmsande** [comment]
The command line for the first line is:

 /projects/sierra/linux_rh6/SDK/mpi/intel/4.1/bin64/mpiexec "-np" "4" "/home/cmsande/LCM/albany-build-serial-gcc-release/src/Albany"

echo $PATH prints out the following: 

/ascldap/users/cmsande/LCM/trilinos-install-serial-gcc-release/bin:/ascldap/users/cmsande/LCM/albany-build-serial-gcc-release/src/LCM:/ascldap/users/cmsande/LCM/albany-build-serial-gcc-release/src:/projects/sems/install/rhel6-x86_64/sems/tpl/parmetis/4.0.3/gcc/6.1.0/openmpi/1.8.7/parallel/bin:/projects/sems/install/rhel6-x86_64/sems/tpl/parmetis/4.0.3/gcc/4.4.7/openmpi/1.8.7/parallel/bin:/projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/6.1.0/openmpi/1.8.7/parallel/bin:/projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/4.4.7/openmpi/1.8.7/parallel/bin:/projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/6.1.0/openmpi/1.8.7/parallel/bin:/projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/4.4.7/openmpi/1.8.7/parallel/bin:/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/6.1.0/openmpi/1.8.7/bin:/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.4.7/openmpi/1.8.7/bin:/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/6.1.0/base/bin:/projects/sems/install/rhel6-x86_64/sems/utility/git/2.10.1/sbin:/projects/sems/install/rhel6-x86_64/sems/utility/git/2.10.1/bin:/projects/sems/install/rhel6-x86_64/sems/utility/cmake/3.5.2/sbin:/projects/sems/install/rhel6-x86_64/sems/utility/cmake/3.5.2/bin:/projects/sems/install/rhel6-x86_64/sems/compiler/python/2.7.9/bin:/usr/bin:/bin:/sbin:/usr/sbin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/puppetlabs/bin

**Comment by ibaned** [comment]
Well this is definitely a problem:
```
/projects/sierra/linux_rh6/SDK/mpi/intel/4.1/bin64/mpiexec
```
For some reason Albany found `mpiexec` in the Sierra RHEL6 SDK install of Intel MPI. However, the LCM modules should have you using SEMS OpenMPI, and indeed your `PATH` shows `/projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/6.1.0/openmpi/1.8.7/parallel/bin` and nothing from `/projects/seirra`...

Could you try reconfiguring Albany and sending the output of that? you can run
```
./clean-config albany 4
```

Also, when pasting text into github, you can put three backticks before and after the text to put it in a nice monospace text box. See the "Code" tab [here](https://guides.github.com/features/mastering-markdown/).

**Comment by cmsande** [comment]
Okay, thanks for the suggestion! 
Here's the output log file from the clean-config call, if that is more useful: 
[albany-serial-gcc-release.txt](https://github.com/gahansen/Albany/files/1095444/albany-serial-gcc-release.txt)

**Comment by ibaned** [comment]
Yea, its still getting the wrong `mpiexec`:
```
CTest serial call: /projects/sierra/linux_rh6/SDK/mpi/intel/4.1/bin64/mpiexec
```

Apparently Albany gets this file path from Trilinos, so could you do the same re-configure for Trilinos and send that output please?

**Comment by cmsande** [comment]
Here is the output from trilinos 
[trilinos-serial-gcc-release.txt](https://github.com/gahansen/Albany/files/1095473/trilinos-serial-gcc-release.txt)

**Comment by ibaned** [comment]
Well Trilinos is now seeing the right `mpiexec`:
```
-- MPI_EXEC='/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/6.1.0/openmpi/1.8.7/bin/mpiexec'
```
Could you make sure to remove the existing build/install directories (the clean option should do this) and then reinstall Trilinos and reconfigure Albany? Hopefully the existing Trilinos install is old and misconfigured, and the new one will be better...

**Comment by cmsande** [comment]
Alright, so I'll call
 `./clean-config-build.sh trilinos 4` 
and then
`./clean-config-build.sh albany 4`?

**Comment by ibaned** [comment]
You can just do
```
./clean-config-build.sh trilinos 4
./clean-config.sh albany 4
```
We should check the output of the Albany config command before bothering to build Albany.
Also if you have more cores that you don't share with others, raise the number `4` to something higher like `16`.

**Comment by cmsande** [comment]
Alright thanks--Im building trilinos right now and then will do the albany config command and let you know the output.

**Comment by cmsande** [comment]
Trilinos appears to have built fine: 
[trilinos-serial-gcc-release2.txt](https://github.com/gahansen/Albany/files/1095737/trilinos-serial-gcc-release2.txt)
as did the configuration of albany: 
[albany-serial-gcc-release2.txt](https://github.com/gahansen/Albany/files/1095743/albany-serial-gcc-release2.txt) 
which now appears to be finding the mpiexec that we want

**Comment by ibaned** [comment]
Excellent, building and testing Albany now should work better.

I suspect you previously configured Trilinos with some Sierra modules loaded, but it seems better now.

**Comment by cmsande** [comment]
Alright great, thank you for your help! Building albany now and will run tests afterwards, hopefully will be in the clear

**Comment by cmsande** [comment]
tests are passing now, thanks for the help

**Comment by ibaned** [comment]
Fantastic
