### ISSUE TITLE
Eliminate copy of wsElNodeEqID connectivity

### ISSUE THREAD

**Issue by jewatkins** [gahansen/Albany#153]
The map from local to global data structures is needed in some Kokkos kernels in order to move data into and out of global Tpetra structures. As of right now, `wsElNodeEqID`, is being copied over into `wsElNodeEqID_kokkos` every time a workset gets loaded (i.e. `loadWorksetBucketInfo()` in Albany_Application.hpp). `wsElNodeEqID` should probably be changed to a Kokkos view to eliminate excessive copying and duplicate data.

**Comment by jewatkins** [comment]
I moved the copy of wsElNodeEqID into a larger scope to reduce the amount of copying but a duplicate of the data still exists.

**Comment by mperego** [comment]
If converting wsElNodeEqID to a Kokkos view saves some copying I would go for that solution. @jewatkins, do you see any drawback/complication in doing that?

**Comment by jewatkins** [comment]
I moved the copy so now it should only happen when the mesh gets updated so that should help quite a bit with that issue.

The only drawback I can see is that the structure would have some extra unnecessary space. The current structure is a series of wrapped vectors over worksets, elements, nodes per element and equations so for example, each element can have a different amount of nodes per element. If I create a view, I'd have to allocate enough space to fit the largest amount of nodes per element for all elements.

**Comment by bartgol** [comment]
Are worksets with different types of elements even supported right now? I thought different element types could only live in different worksets, and must also belong to different MeshSpecsStruct's...

Assuming what I'm saying is true, couldn't we have N separate wsElNodeEqID views, one per each mesh specs?

**Comment by ibaned** [comment]
I think @bartgol is right. a single workset should contain only elements of the exact same type (shape, basis functions, physics, etc.)
I think my suggestion on the Albany phone call was to use `std::vector<Kokkos::View<?>>`.

**Comment by ibaned** [comment]
@jewatkins  I suspect these changes also broke the PUMI Discretization because it didn't get the function implemented:
http://my.cdash.org/viewBuildError.php?buildid=1254880

**Comment by jewatkins** [comment]
If that's the case, then I don't foresee any issues. It's currently setup as a `std::vector<Kokkos::View<?>>` as Dan suggested but it's doing a copy. Let me see if I can remove the copy then. I should be able to fix the issue with PUMI too.

**Comment by jewatkins** [comment]
@ibaned I added the function to PUMI temporarily while I convert wsElNodeEqID to a Kokkos view.

**Comment by jewatkins** [comment]
wsElNodeEqID has been converted to a Kokkos view. All 381 of the tests that I currently run pass but there may be some tests that I'm missing. I'll be checking the cdash tests tomorrow but let me know if something else fails.
