### ISSUE TITLE
LCM tests: yaml dependency not checked at configure time

### ISSUE THREAD

**Issue by bartgol** [gahansen/Albany#154]
I was running the LCM tests, and I noticed they all hanged. Running them individually, I notice an error, coming from the Teuchos XML parser which clearly could not parse the yaml file.

Is yaml a required dependency for the LCM tests? If so, should we make it clear at configure time maybe? Otherwise, if yaml is only needed for a few tests (I haven't checked all the LCM tests, but giving a quick look it appears that quite a few have yaml input files), perhaps we can filter them out if yaml is not enabled?

**Comment by lxmota** [comment]
LCM now requires YAML. I believe that @ibaned introduced detection of YAML in the configuration.

**Comment by bartgol** [comment]
Well, I activated LCM, built and tried to run tests, and they were all failing. Actually hanging: the Teuchos XML reader has a broadcast inside, and while proc 0 failed to load the xml file (because it wasn't an xml file), the other processes hung there, waiting for a communication. This caused the test to hang, rather than fail and move to the next one.

**Comment by ibaned** [comment]
pretty much all LCM tests require YAML now. there may not be sufficient checks in CMake, I'm inclined to omit the entire `tests/*/LCM/` subdirectories if YAML is not enabled. Also, in the parameter list readers themselves we should have better logic to handle the case of files ending in `.yaml`.

**Comment by bartgol** [comment]
I agree with the better handling of files ending in yaml.

As for the test/*/LCM directories, on one hand, omitting them when yaml is not enabled would make the testing cleaner. On the other hand, one may not be aware of that, and think he/she fully tested LCM and be confident pushing. I think that, if LCM requires yaml, we should error out at config time if one enables LCM without having yaml enabled. It's safer for testing.

**Comment by lxmota** [comment]
OK, I committed a change that enforces the YAML requirement for LCM. If YAML is not present and LCM is enables, the configuration emits an error message that YAML is required for LCM and then stops.
