### ISSUE TITLE
Schwarz alternating fails

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#157]
http://my.cdash.org/testDetails.php?test=33350952&build=1259249

```
cuboid test has failed
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name jenga and rank 0!
have_loca == true || have_tempus == true failed at /lore/ghansen/nightly/repos/Albany/src/LCM/solvers/Schwarz_Alternating.cpp +140
```

The fix sounds easy, just letting people know (@lxmota).

**Comment by lxmota** [comment]
Ack! Yes, my fault.

Getting ahead of myself with this. I'll fix it.

Alejandro

On Jul 27, 2017, at 06:46, Dan Ibanez <notifications@github.com<mailto:notifications@github.com>> wrote:


http://my.cdash.org/testDetails.php?test=33350952&build=1259249

cuboid test has failed
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name jenga and rank 0!
have_loca == true || have_tempus == true failed at /lore/ghansen/nightly/repos/Albany/src/LCM/solvers/Schwarz_Alternating.cpp +140


The fix sounds easy, just letting people know (@lxmota<https://github.com/lxmota>).

-
