### ISSUE TITLE
Compiling Albany with Simmetrix

### ISSUE THREAD

**Issue by mjuha** [gahansen/Albany#164]
Hello,

Finally I am back into Albany, now from my new position in Colombia. Recently I licenced Simmetrix's software and I tried to compile Albany with Simmetrix following the instructions I used a few monts ago meanwhile I was in RPI, but it was not possible.  Please, someone could give me some instructions on how to do it? I´ll try to use Albany-Simmetrix in my research at Universidad de La Sabana.

The following is my configure script for Trilinos:

#!/bin/sh
  #
  export TRILINOS_HOME=/home/marioju/projects/albany/Trilinos
  BUILD_DIR=`pwd`
  INSTALL_DIR=/home/marioju/projects/albany/install/Trilinos/MPI_REL
  BOOST_DIR=/home/marioju/projects/albany/tpls
  YAMLDIR=/home/marioju/projects/albany/tpls
  SUPERLU_DIR=/home/marioju/projects/albany/tpls/SuperLU_4.3
  LIB_DIR=/home/marioju/projects/albany/tpls
  MPI_BASE_DIR=/usr/lib64/openmpi/bin
  NETCDF=/home/marioju/projects/albany/tpls
  HDFDIR=/home/marioju/projects/albany/tpls
  PARMETISDIR=/home/marioju/projects/albany/tpls/parmetis-4.0.3
  LABLAS_LIBRARIES="-lblas -llapack"
  SIM_INCLUDE=$SIM_INSTALL_DIR/include
  SIM_LIB=$SIM_INSTALL_DIR/lib/x64_rhel7_gcc48

  cmake \
      -Wno-dev \
      -D Trilinos_CONFIGURE_OPTIONS_FILE:FILEPATH=$TRILINOS_HOME/sampleScripts/AlbanySettings.cmake \
      -D Trilinos_ENABLE_SCOREC:BOOL=ON \
      -D SCOREC_DISABLE_STRONG_WARNINGS:BOOL=ON \
      -D Trilinos_WARNINGS_AS_ERRORS_FLAGS="" \
      -D CMAKE_BUILD_TYPE:STRING=NONE \
      -D CMAKE_CXX_FLAGS:STRING="-O3 -march=native -DNDEBUG" \
      -D CMAKE_C_FLAGS:STRING="-O3 -march=native -DNDEBUG" \
      -D CMAKE_Fortran_FLAGS:STRING="-O3 -march=native -DNDEBUG" \
      -D Trilinos_ENABLE_ALL_PACKAGES=OFF \
      -D Trilinos_WARNINGS_AS_ERRORS_FLAGS="" \
      -D Trilinos_ENABLE_Teuchos=ON \
      -D Trilinos_ENABLE_Shards=ON \
      -D Trilinos_ENABLE_Sacado=ON \
      -D Trilinos_ENABLE_Epetra=ON \
      -D Trilinos_ENABLE_EpetraExt=ON \
      -D Trilinos_ENABLE_Ifpack=ON \
      -D Trilinos_ENABLE_AztecOO=ON \
      -D Trilinos_ENABLE_Amesos=ON \
      -D Trilinos_ENABLE_Anasazi=ON \
      -D Trilinos_ENABLE_Belos=ON \
      -D Trilinos_ENABLE_ML=ON \
      -D Trilinos_ENABLE_Phalanx=ON \
      -D Trilinos_ENABLE_MiniTensor=ON \
      -D Trilinos_ENABLE_ROL=ON \
      -D Trilinos_ENABLE_NOX=ON \
      -D Trilinos_ENABLE_Stratimikos=ON \
      -D Trilinos_ENABLE_Thyra=ON \
      -D Trilinos_ENABLE_Rythmos=ON \
      -D Trilinos_ENABLE_Stokhos=OFF \
      -D Trilinos_ENABLE_Piro=ON \
      -D Trilinos_ENABLE_Teko=ON \
      -D Trilinos_ENABLE_STKIO=ON \
      -D Trilinos_ENABLE_STKMesh=ON \
      -D Trilinos_ENABLE_Tpetra=ON \
      -D Trilinos_ENABLE_Kokkos=ON \
      -D Trilinos_ENABLE_Tempus=ON \
      -D Kokkos_ENABLE_Pthread=OFF \
      -D HAVE_INTREPID_KOKKOSCORE=ON \
      -D Trilinos_ENABLE_Ifpack2=ON \
      -D Trilinos_ENABLE_Zoltan2=ON \
      -D Trilinos_ENABLE_MueLu=ON \
      -D Trilinos_ENABLE_STKTransfer=OFF \
      -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
      -D Tpetra_INST_INT_LONG_LONG:BOOL=ON \
      -D Tpetra_INST_INT_INT:BOOL=ON \
      -D Tpetra_INST_DOUBLE:BOOL=ON \
      -D Tpetra_INST_FLOAT:BOOL=OFF \
      -D Tpetra_INST_COMPLEX_FLOAT:BOOL=OFF \
      -D Tpetra_INST_COMPLEX_DOUBLE:BOOL=OFF \
      -D Tpetra_INST_INT_LONG:BOOL=OFF \
      -D Tpetra_INST_INT_UNSIGNED:BOOL=OFF \
      \
      -D Trilinos_ENABLE_Intrepid2=ON \
      -D Intrepid2_ENABLE_KokkosDynRankView=ON \
      \
      -D Trilinos_ENABLE_Amesos2=ON \
      -D Amesos2_ENABLE_KLU2=ON \
      -D Amesos2_ENABLE_SuperLUDist=OFF \
      -D Amesos2_ENABLE_Epetra=OFF \
      \
      -D Trilinos_ENABLE_SEACAS=ON \
      -D Trilinos_ENABLE_SEACASIoss=ON \
      -D Trilinos_ENABLE_SEACASExodus=ON \
      -D SEACAS_ENABLE_SEACASSVDI=OFF \
      -D Trilinos_ENABLE_SEACASFastq=OFF \
      -D Trilinos_ENABLE_SEACASBlot=OFF \
      -D Trilinos_ENABLE_SEACASPLT=OFF \
      \
      -D TPL_ENABLE_Matio=OFF \
      -D TPL_ENABLE_X11=OFF \
 \
      -D TPL_ENABLE_MPI:BOOL=ON \
      -D MPI_BASE_DIR:PATH=$MPI_BASE_DIR \
  \
      -D TPL_ENABLE_Pthread:BOOL=OFF \
  \
      -D TPL_ENABLE_Boost:BOOL=ON \
      -D TPL_ENABLE_BoostLib:BOOL=ON \
      -D TPL_ENABLE_BoostAlbLib:BOOL=ON \
      -D Boost_INCLUDE_DIRS:PATH=$BOOST_DIR/include \
      -D Boost_LIBRARY_DIRS:PATH=$BOOST_DIR/lib \
      -D BoostLib_INCLUDE_DIRS:PATH=$BOOST_DIR/include \
      -D BoostLib_LIBRARY_DIRS:PATH=$BOOST_DIR/lib \
      -D BoostAlbLib_INCLUDE_DIRS:PATH=$BOOST_DIR/include \
      -D BoostAlbLib_LIBRARY_DIRS:PATH=$BOOST_DIR/lib \
  \
      -D TPL_ENABLE_Netcdf:STRING=ON \
      -D Netcdf_INCLUDE_DIRS:PATH=$NETCDF/include \
      -D Netcdf_LIBRARY_DIRS:PATH=$NETCDF/lib \
  \
      -D TPL_ENABLE_HDF5:STRING=ON \
      -D HDF5_INCLUDE_DIRS:PATH=$HDFDIR/include \
      -D HDF5_LIBRARY_DIRS:PATH=$HDFDIR/lib \
  \
      -D TPL_ENABLE_Zlib:STRING=ON \
      -D Zlib_INCLUDE_DIRS:PATH=$HDFDIR/include \
      -D Zlib_LIBRARY_DIRS:PATH=$HDFDIR/lib \
  \
      -D TPL_ENABLE_BLAS:STRING=ON \
      -D TPL_ENABLE_LAPACK:STRING=ON \
      -D TPL_BLAS_LIBRARIES:STRING="$LABLAS_LIBRARIES" \
      -D TPL_LAPACK_LIBRARIES:STRING="$LABLAS_LIBRARIES" \
  \
      -D TPL_ENABLE_ParMETIS:STRING=ON \
      -D ParMETIS_INCLUDE_DIRS:PATH="${PARMETISDIR}/include" \
      -D ParMETIS_LIBRARY_DIRS:PATH="${PARMETISDIR}/lib" \
  \
      -D TPL_ENABLE_yaml-cpp=ON \
      -D yaml-cpp_INCLUDE_DIRS=$YAMLDIR/include \
      -D yaml-cpp_LIBRARY_DIRS=$YAMLDIR/lib \
  \
      -D TPL_ENABLE_SuperLU:STRING=ON \
      -D SuperLU_INCLUDE_DIRS:PATH="${SUPERLU_DIR}/include" \
      -D SuperLU_LIBRARY_DIRS:PATH="${SUPERLU_DIR}/lib" \
  \
      -D CMAKE_INSTALL_PREFIX:PATH=$INSTALL_DIR \
      -D Trilinos_EXTRA_LINK_FLAGS:STRING="-L${HDFDIR}/lib -lnetcdf -lhdf5_hl -lhdf5 -lz -lgfortran -Wl,-rpath,/home/marioju/projects/albany/tpls/lib" \
  \
      -D Trilinos_ENABLE_Moertel:BOOL=OFF \
      -D Trilinos_ENABLE_TriKota:BOOL=OFF \
      -D HAVE_INTREPID_KOKKOSCORE:BOOL=OFF \
      -D Trilinos_ENABLE_SECONDARY_TESTED_CODE=OFF \
      -D Amesos2_ENABLE_SuperLU:BOOL=ON \
  \
      -D SimMesh_INCLUDE_DIRS=$SIM_INCLUDE \
      -D SimMesh_LIBRARY_DIRS=$SIM_LIB \
      -D SimModel_INCLUDE_DIRS=$SIM_INCLUDE \
      -D SimModel_LIBRARY_DIRS=$SIM_LIB \
      -D TPL_ENABLE_SimParasolid=True \
      -D SimParasolid_INCLUDE_DIRS=$SIM_INCLUDE \
      -D SimParasolid_LIBRARY_DIRS="$SIM_LIB;$SIM_LIB/psKrnl" \
      -D TPL_ENABLE_SimField=True \
      -D SimField_INCLUDE_DIRS=$SIM_INCLUDE \
      -D SimField_LIBRARY_DIRS=$SIM_LIB \
      -D SIM_MPI='openmpi110' \
      -D SIM_BASEMPI='mpi' \
  \
  $EXTRA_ARGS \
  ${TRILINOS_HOME}

and this one for Albany:

export TRI_DIR=/home/marioju/projects/albany/install/Trilinos/MPI_REL
export ALB_DIR=/home/marioju/projects/albany/Albany
cmake \
 -D ENABLE_INSTALL=ON \
 -D CMAKE_INSTALL_PREFIX=${ALB_DIR} \
 -D ALBANY_TRILINOS_DIR=${TRI_DIR} \
 -D ENABLE_64BIT_INT=OFF \
 -D ENABLE_SCOREC=ON \
 -D ENABLE_AMP=ON \
 -D ENABLE_LCM=ON \
 -D ENABLE_CTM=ON \
 -D ENABLE_CHECK_FPE=OFF \
 -D ENABLE_ALBANY_EPETRA_EXE=OFF \
 -D ENABLE_LCM_SPECULATIVE=OFF \
 -D ENABLE_HYDRIDE=OFF \
 -D ENABLE_SG_MP=OFF \
 -D ENABLE_QCAD=OFF \
 -D ENABLE_MOR=OFF \
 -D ENABLE_STOKHOS=OFF \
 -D ENABLE_FELIX=OFF \
 -D ALBANY_APF=ON \
../

**Comment by mjuha** [comment]
This is the error I get:

CMake Error at CMakeLists.txt:856 (MESSAGE):
 
  Error: AMP option requires SCOREC/core-sim

-- Configuring incomplete, errors occurred!

**Comment by bgranzow** [comment]
I think the AMP and CTM repositories might have fallen a bit behind, as they do not have nightly tests run for them, and their respective projects have successfully ended.  Now I think about it, we either probably want to think about setting up a build that tests these capabilities or think about getting rid of them.  That is probably a decision for the core Albany development team to make.

My concern is ending up with so many dashboards that it is intractable to try to maintain them all. It might be a good option for you to set up your own nightly testing for this code if you intend to use it, as you may be the sole driver of those codes now.

I would recommend starting by re-compiling Trilinos without any SCOREC options, and then compiling SCOREC outside of Trilinos using [these](https://github.com/gahansen/Albany/wiki/Building-with-SCOREC#install-scorec-outside-trilinos) instructions.  When you compile SCOREC, you will need to enable optional Simmetrix [options](https://github.com/SCOREC/core/wiki/General-Build-instructions#configure).

To get Albany to build again, you'll need to modify some of the Albany [CMake](https://github.com/gahansen/Albany/blob/master/CMakeLists.txt#L854) logic to accurately find SCOREC/core for the AMP project, and make sure it was compiled with the appropriate Simmetrix options. Finally, you may have to wade through compilation errors that occur from changes to Simmetrix APIs depending on what version of Simmetrix you have.

**Comment by mjuha** [comment]
Brian thanks for the answer. Then according to your answer, the development of Albany-Simmetrix is done. I may try to continue the development of it, but I am afraid that it is going to be really hard to do it by myself.

**Comment by ibaned** [comment]
@mjuha I agree. I recommend you consider whether you can complete your projects using just the LCM system. If you are comfortable discussing your target problem of interest on GitHub, you can open an issue to ask how to best solve it with LCM, otherwise you can also send me an email.

**Comment by mjuha** [comment]
@ibaned  @bgranzow , the LCM project is the one I need to use now. I want to use Albany to solve thermo-mechanical problems that arises from heat treatments. But for geometry handling I need to use Simmetrix, that is the only tool I have now. I already had a license of the software. And I remember that it worked well with Albany.

**Comment by ibaned** [comment]
You can also use the PUMI discretization and translate your Simmetrix meshes to PUMI. Either way you can start by compiling the SCOREC/core repository with Simmetrix support enabled. This should give you many options of how to move forward.

**Comment by mjuha** [comment]
I´ll close the issue
