### ISSUE TITLE
Albany/LCM modules for skybridge

### ISSUE THREAD

**Issue by cmsande** [gahansen/Albany#165]
With recent updates to skybridge, the module files necessary to build/run Albany on the cluster (lcm/cluster and serial-intel-release) don't load correctly anymore. 

It looks like the default intel, openmpi, mlk, and cmake modules have changed on skybridge, so lcm/cluster is trying to access the old versions.

**Comment by ibaned** [comment]
Thanks for creating this issue, we've been discussing a solution by email.
Its actually much more complex than just the modules changing, the actual module system implementation itself has changed. In fact `lcm/cluster` will need to be changed to `lcm-cluster`.
But we have a plan and will fix this soon.

**Comment by ibaned** [comment]
@jwfoulk @lxmota just FYI this GitHub issue will track progress

**Comment by cmsande** [comment]
Has there been progress on the issue of running albany on the updated clusters?

**Comment by ibaned** [comment]
Yes, the modules should work now. Please contact Jay Foulk or Alejandro Mota for details.

**Comment by ibaned** [comment]
To spell it out, all `lcm/foo` modules are now `lcm-foo`, and one must use
```
module use --append /path/to/modulefiles
```
instead of
```
export MODULEPATH=$MODULEPATH:/path/to/modulefiles
```
on the new TOSS3 cluster environments.
