### ISSUE TITLE
Albany compilation error with CUDA KokkosNode

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#166]
Although the compilation of Trilinos has been fixed with a CUDA KokkosNode, it appears there is a build error in Albany on Ride: 

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=57195

The errors seem to be related to the following (for those who cannot access the above link): 

.../build/TrilinosInstall/include/impl/Kokkos_ViewMapping.hpp(2914): error: static assertion failed with "View assignment must have compatible layout or have rank <= 1"

Tagging @ibaned and @mperego , who I believe were involved in fixing the issue on the Trilinos side.

**Comment by ibaned** [comment]
Also mentioning @ndellingwood, who helped @mperego fix the Trilinos issue.
More error text would help, in particular the Albany line and file where this actually originates.

**Comment by rppawlo** [comment]
@ikalash - try including "Kokkos_ViewFactory.hpp" in the failing evaluator files. I had a similar problem in Drekar due to recent changes to intrepid2. This file pulls in sacado fad specializations. Without these specializations, the mapping is missing the extra derivative dimension in the underlying view, resulting in the incompatible layouts during assignment.

**Comment by mperego** [comment]
Thanks @rppawlo. I'm wondering why this happens only with a CUDA build.

**Comment by ikalash** [comment]
@ibaned: here is the log file from the Ride nightly tests where this compilation error is happening: http://www.sandia.gov/~ikalash/nightly_log_rideAlbany.txt

**Comment by ibaned** [comment]
Relevant lines from @ikalash 's log file, pointing into an evaluator
```
/home/projects/albany/build/TrilinosInstall/include/Kokkos_View.hpp(1088): error: static assertion failed with "Incompatible View copy construction"
          detected during:
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &) [with DataType=Intrepid2::ordinal_type ***, Properties=<PHX::Device>,
 RT=LO ***, RP=<Kokkos::LayoutRight, PHX::Device>]"
/home/projects/albany/repos/Albany/src/QCAD/evaluators/QCAD_PoissonSourceNeumann_Def.hpp(455): here
            instantiation of "void QCAD::PoissonSourceNeumann<PHAL::AlbanyTraits::Residual, Traits>::evaluateFields(Traits::EvalData) [with Traits=PHAL::AlbanyTraits]"
/home/projects/albany/repos/Albany/src/QCAD/evaluators/QCAD_PoissonSourceNeumann.cpp(37): here
```

**Comment by ikalash** [comment]
Right.  So, the thing is, if you add the "Kokkos_ViewFactory.hpp" include into QCAD_PoissonSourceNeumann_Def.hpp, as @rppawlo suggests, that does not fix the problem.

**Comment by ibaned** [comment]
Here is the line:
```
  Kokkos::View<LO***, PHX::Device> nodeID = workset.wsElNodeEqID;
```
Actually, I recently changed the `wsElNodeEqID` to force `LayoutRight`, thats probably what triggers this.

PSA to all Albany developers: please use `auto` as much as possible. This line should have always been:
```
  auto nodeID = workset.wsElNodeEqID
```

That ensures that no matter what the type is it will work, and prevents carpal tunnel.

**Comment by rppawlo** [comment]
> Thanks @rppawlo. I'm wondering why this happens only with a CUDA build.

I was seeing this with all node types, not just cuda.

**Comment by ikalash** [comment]
This issue has been fixed by changing the type of nodeID and workset.wsElNodeEqID throughout the code.
