### ISSUE TITLE
Belos verbose output flag not recognized when running with Tpetra (AlbanyT) executable

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#168]
It might be that this should be a Trilinos issue but I wanted to first open it as an Albany issue as a sanity check.  

I recently discovered that it appears when I run the AlbanyT (Tpetra) executable + Belos with verbosity set to output the linear solver residual every N iterations, nothing gets printed.  If I run the same exact input file with the Albany (Epetra) executable (possible only when no preconditioner is used), I get the expected verbose output.  

Here is some documentation of what I am seeing.  The input file I am running with is: Albany/tests/small/FELIX/FO_GIS/input_fo_gis_unstructT.xml .  It has the relevant Belos verbosity flags:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  <Parameter name="Output Frequency" type="int" value="20"/>
  <Parameter name="Output Style" type="int" value="1"/>
  <Parameter name="Verbosity" type="int" value="33"/>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

When run with the Albany executable, I get the output: 

Start of Continuation Step 0 : Attempting to converge initial guess at initial parameter values.

 [Basal Residual] ff = 0

************************************************************************
-- Nonlinear Solver Step 0 --
||F|| = 1.392e+06  step = 0.000e+00  dx = 0.000e+00
************************************************************************

 [Basal Residual] ff = 0 [ ]

   *******************************************************
   ***** Belos Iterative Solver:  Block Gmres
   ***** Maximum Iterations: 200
   ***** Block Size: 1
   ***** Residual Test:
   *****   Test 1 : Belos::StatusTestImpResNorm<>: (2-Norm Res Vec) / (2-Norm Prec Res0), tol = 1e-06
   *******************************************************
   Iter   0, [ 1] :    1.000000e+00
   Iter  20, [ 1] :    9.227473e-01
   Iter  40, [ 1] :    8.866300e-01
   Iter  60, [ 1] :    8.519868e-01
   Iter  80, [ 1] :    8.186798e-01
...

When run with the AlbanyT executable, I see this:

Start of Continuation Step 0 : Attempting to converge initial guess at initial parameter values.

 [Basal Residual] ff = 0

************************************************************************
-- Nonlinear Solver Step 0 --
||F|| = 1.392e+06  step = 0.000e+00  dx = 0.000e+00
************************************************************************

 [Basal Residual] ff = 0 [ ]
WARNING: LOCA::BorderedSolver::LowerTriangularBlockElimination::solve() -
Return Type = NotConverged
WARNING: LOCA::MultiContinuation::ConstrainedGroup::applyJacobianInverseMultiVector() -
Return Type = NotConverged
WARNING: LOCA::MultiContinuation::ConstrainedGroup::computeNewton() -
Return Type = NotConverged
WARNING: NOX::Direction::Newton::compute() - Linear solve failed to achieve convergence - using the step anyway since "Rescue Bad Newton Solve" is true

************************************************************************
-- Nonlinear Solver Step 1 --
||F|| = 1.272e+06  step = 5.000e-01  dx = 1.043e+03
************************************************************************

(the non-convergence is expected here b/c there is no preconditioner, so that is not an issue).  Has anyone else experienced this?  It seems to me it might be a Stratimikos problem but I wanted to get others' thoughts.

**Comment by ikalash** [comment]
@ibaned , if you have no objections, I vote for moving this to a Trilinos issue.  @jhux2 and I believe it is likely a problem with the Stratimikos interface and how it behaves with Tpetra.

**Comment by ibaned** [comment]
actually, I have run into this problem before. As you suggest, something at the higher level (probably Stratimikos?) overwrites the Belos options with a different one. I believe one has to use the Teuchos VerboseObject parameters, and those are the only ones that get through. This is just a vague memory though,  but yes it is annoying and I'm fine with bringing it up for Trilinos consideration (PS - you don't have to check with me before opening Trilinos issues :)

**Comment by aprokop** [comment]
@ibaned You think this is one of those "add the following to Belos sublist" issues?
```xml
<ParameterList name="VerboseObject">
  <Parameter name="Verbosity Level" type="string" value="low"/>
</ParameterList>
```

**Comment by ibaned** [comment]
@aprokop  yep, that looks pretty familiar. now you just have to figure out where in the parameter hierarchy it goes...

**Comment by ibaned** [comment]
It may be Belos, or Stratimikos->"Linear Solver", or something like that...

**Comment by ikalash** [comment]
Thanks, @aprokop .  I had tried this before but I wasn't putting the sublist in the right place.  If I put it under "Belos"

----------------------
<ParameterList name="Belos">
    <ParameterList name="VerboseObject">
    <Parameter name="Verbosity Level" type="string" value="high"/>
</ParameterList>
-----------------------------

it fixes the problem.  Thanks!

**Comment by bartgol** [comment]
I had the very same issue with Belos a while ago. @ikalash , did that solve the issue?
