### ISSUE TITLE
Albany compilation error due to PHX::DataLayout 

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#171]
My Albany CUDA build on Ride began failing yesterday with the error:

"PHX::DataLayout" has no member "name"

See: 
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=57584

I believe this is related to #167.

**Comment by ikalash** [comment]
Looks like this happens also on Cori with a Serial node: http://my.cdash.org/viewBuildError.php?buildid=1269479 .

**Comment by ibaned** [comment]
@rppawlo any ideas?

**Comment by rppawlo** [comment]
We are refactoring some of the base classes to allow for more flexibility (dynamic sizing of the fields). Along those lines, we simplified the DataLayout base class and removed the string names for the rank indices. The code is still in the derived implementation for MDALayout, but our new layout does not support names, so I dropped it from the base class. You could cast back to MDALayout and then call names() or I could add back the names() accessors to the base class. What is your preference?

**Comment by ikalash** [comment]
I see.  It looks like this broke all the Albany builds that build against develop (http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany), which makes sense given the change.  I think for us adding names() back to the base class would be preferable b/c we would not need to make changes to Albany; @ibaned , what do you think?

**Comment by bartgol** [comment]
I see the new implementation does not have tags for the different ranks, which is probably why there are no names associated. If there is no satisfactory way to have DynamicLayout produce an output for "name(..)", then I would keep the name method out of the base class. On this note: couldn't Phalanx create some default names for the ranks names? Something like "Tag N" or "Dim N"?

**Comment by rppawlo** [comment]
We took the names() methods out of the base class because it wasn't used in the by the general code. The concrete MDALayout used it for generating a unique id, so it shouldn't really be in the base class. I have never seen an application actually call it - Albany is the only one. All other apps are passing. So what are you using this for? All layouts and tags have ostream overloads for printing. If there is a technical reason to keep, then we can add it back, otherwise it is adding complexity/requirements to an interface that doesn't need it.

**Comment by ibaned** [comment]
Here is a summary of lines calling the `name` method of `DataLayout`:
```
Albany_StateManager.cpp
162:  else if (dl->rank() == 1 && dl->name(0) == "Cell")
164:  else if(dl->rank() >= 1 && dl->name(0) == "Node") // Nodal data
166:  else if(dl->rank() >= 1 && dl->name(0) == "Cell"){ // Element QP or node data
167:     if(dl->rank() > 1 && dl->name(1) == "Node") // Element node data
169:     else if(dl->rank() > 1 && dl->name(1) == "QuadPoint") // Element node data
172:       "StateManager: Element Entity type - " << dl->name(1) << " - not supported" << std::endl);
175:     "StateManager: Unknown Entity type - " << dl->name(0) << " - not supported" << std::endl);
268:  else if(dl->rank() >= 1 && dl->name(0) == "Node") // Nodal data
270:  else if(dl->rank() >= 1 && dl->name(0) == "Cell"){ // Element QP or node data
271:     if(dl->rank() > 1 && dl->name(1) == "Node") // Element node data
273:     else if(dl->rank() > 1 && dl->name(1) == "QuadPoint") // Element node data
276:       "StateManager: Element Entity type - " << dl->name(1) << " - not supported" << std::endl);
279:     "StateManager: Unknown Entity type - " << dl->name(0) << " - not supported" << std::endl);
425:  else if(dl->rank() >= 1 && dl->name(0) == "Node") // Nodal data
429:  else if (dl->rank() == 2 && dl->name(1) == "Side") // Element data
435:    if (dl->name(2) == "Dim")
437:    else if (dl->name(2) == "Node") // Element node data
439:    else if(dl->name(2) == "QuadPoint") // Quad point data
457:    TEUCHOS_TEST_FOR_EXCEPTION(dl->name(0) == "Node", std::logic_error, "Error! NodalData states should have dl <Node,...>.\n");
505:  stateRef.layered = (dl->name(dl->rank()-1) == "LayerDim");
```

It seems like its just trying to check the tag type of certain dimensions. Is there a different way we can do this comparison? Hopefully directly against the tag type itself?

**Comment by rppawlo** [comment]
Neat. That's definitely a valid use case. I will add this back to the base class today.

**Comment by ibaned** [comment]
Thanks @rppawlo !

**Comment by rppawlo** [comment]
Fix was just pushed.

**Comment by ikalash** [comment]
Thanks, @rppawlo !  I'll close this issue tomorrow morning once I verify that all the Albany nightlies are working correctly.
