### ISSUE TITLE
Compilation error due to change in Tempus

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#175]
It looks like a change was made to Tempus that caused a compilation error in Albany: 

[  7%] Building CXX object src/ATO/CMakeFiles/ATO.dir/evaluators/ATO_ModalObjective.cpp.o
In file included from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/Tempus_StepperForwardEuler.hpp:2:0,
                 from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/Tempus_StepperForwardEulerObserver.hpp:13,
                 from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/Tempus_StepperForwardEuler_decl.hpp:14,
                 from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/Tempus_StepperForwardEuler.hpp:1,
                 from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/Tempus_StepperFactory.hpp:13,
                 from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/Tempus_IntegratorBasic_impl.hpp:14,
                 from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/Tempus_IntegratorBasic.hpp:2,
                 from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/Piro_TempusSolver.hpp:49,
                 from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/Piro_SolverFactory_Def.hpp:67,
                 from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/Piro_SolverFactory.hpp:97,
                 from /home/ikalash/nightlyCDash/repos/Albany/src/Albany_SolverFactory.cpp:24:
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/Tempus_StepperForwardEuler_impl.hpp:21:1: error: ‘StepperForwardEuler’ does not name a type
 StepperForwardEuler<Scalar>::StepperForwardEuler(
 ^~~~~~~~~~~~~~~~~~~
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/Tempus_StepperForwardEuler_impl.hpp:32:25: error: expected initializer before ‘<’ token
 void StepperForwardEuler<Scalar>::setModel(
                         ^
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/Tempus_StepperForwardEuler_impl.hpp:43:25: error: expected initializer before ‘<’ token
 void StepperForwardEuler<Scalar>::setNonConstModel(

(see http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=58560).  I will look into this.

**Comment by ikalash** [comment]
@rppawlo , @ccober6: it looks like some changes pushed to Tempus yesterday broke our Albany builds (see above).  Before I start digging, any suggestions on what could be the problem?  I see the @ccober6 added observers to the steppers but it seems odd that that would cause an error like this.

**Comment by ccober6** [comment]
Hi Irina,

I was just looking at this.  It seemed that the <Scalar> has been stripped off from all those statements?!

Curt

**Comment by ccober6** [comment]
Hmm... that cut-n-paste failed!

It seemed that the <Scalar> has been stripped off from all those statements?!

**Comment by ccober6** [comment]
Hmm ... it did it again.

t seemed that the has been stripped off `<Scalar>` from all those statements?!

**Comment by ccober6** [comment]
Got it that time.

**Comment by ikalash** [comment]
Right, exactly, it is like it is missing the template parameter.  I thought at first you added / changed a template parameter but it does not look like that was the case...  so I am kind of puzzled as to why we are getting this error.

**Comment by ccober6** [comment]
I assume that the `<Scalar>`s are in the original file, Tempus_StepperForwardEuler_impl.hpp?

**Comment by ikalash** [comment]
I have confirmed that the following Trilinos commit is what broke the Albany build: 

https://github.com/trilinos/Trilinos/commit/208735dc0831ef2bb76e002f25b365f7c55b3162

By "original" file, I assume you mean Tempus_StepperForwardEuler_impl.hpp before this commit?  Yes, they both have that template argument.  I guess somehow the introduction of the observers messed things up, but I don't see yet how...

**Comment by ikalash** [comment]
I just tried the following: 

- Checking out Trilinos commit: https://github.com/trilinos/Trilinos/commit/b52baf71a48b6694e30ba1b81517d6dc04bee0d5 (right before the problematic commit - Albany compiles fine with this Trilinos).
- Adding the following include to Tempus_StepperForwardEuler_decl.hpp: "Tempus_StepperForwardEulerObserver.hpp"
- Copying Tempus*Observer* files added in commit https://github.com/trilinos/Trilinos/commit/208735dc0831ef2bb76e002f25b365f7c55b3162 to the tempus/src directory so those files exist for compilation.
- Reconfiguring / recompiling.

I get the error, so it seems to come from simply including one of the new observers.

**Comment by ccober6** [comment]
When you 

 * Copying TempusObserver files added in commit trilinos/Trilinos@208735d to the tempus/src directory so those files exist for compilation.

did you just copy over Tempus_StepperForwardEulerObserver.hpp?

**Comment by ccober6** [comment]
Are you doing ETI?

**Comment by ikalash** [comment]
No not in this build.  We can't use ETI when DTK is on (it is needed in this build) because DTK doesn't compile with ETI.

_Sent from my Samsung SAMSUNG-SM-G891A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ikalash** [comment]
Following up @ccober6 's comment, the issue goes away if I turn on ETI in Tempus only.  I can go ahead and change the scripts for my Albany nightlies to turn on ETI in Tempus.  It seems though that the code should compile without ETI as well - @ccober6 , @rppawlo , do you agree?  Should I move this to a Trilinos github issue?

**Comment by rppawlo** [comment]
I was able to successfully build and run all tempus tests with tempus ETI both ON and OFF. My guess is that either we are missing a test for something in tempus or tempus/piro/albany is not pulling in the right include headers.

**Comment by rppawlo** [comment]
Piro tests also compiled and ran when ETI is disabled for Tempus. Is there any chance that the Albany build is picking up an old lib from an older Trilinose  build? We might have to do a pair debugging session since I don't have an albany build available.

**Comment by ccober6** [comment]
Roger and I have been having an offline discussion, but I just noticed that I am not getting emails on this thread anymore?!  Does anyone know why?

**Comment by ibaned** [comment]
The Sandia email system has been rejecting emails from GitHub for a while now. Several people on the Kokkos team have noticed this issue.

**Comment by ikalash** [comment]
@rppawlo : right, on my machine, Trilinos with Tempus / Piro builds find too for Tempus having and not having ETI; the issue comes up when compiling Albany.  I don't think Albany is picking up an old Trilinos lib b/c the problem occurred in my nightly test harness which wipes and builds from scratch Trilinos and Albany.  I guess the most reasonable next steps would be: 1.) I provide you with instructions / scripts for how to build Albany so you can reproduce the issue, or 2.) we try to debug it on my machine via Skype + screensharing (like you suggest).  Which approach do you prefer?

**Comment by rppawlo** [comment]
@ikalash either way is fine. What is your preference? If you want to send scripts I can give it a shot tomorrow and if I have trouble then maybe we can fall back on pair programming session?

**Comment by ikalash** [comment]
@rppawlo : what you propose sounds good to me.  I will email you the cmake scripts for my Linux workstation.  I'll be working tomorrow so lets touch base then after you've had a chance to try to build the code.

**Comment by rppawlo** [comment]
@ikalash Thanks for the scripts! They worked perfect. Was able to reproduce the error. The issue was from circular includes. Fixed the observers so that they don't include the stepper headers.  All the observers actually did do the right thing with a forward declaration, but five of the observers then went and included the stepper header as well. Just had to remove these includes.

checkin-test script is running. I will leave this open for you to verify the fix in albany testing.

I still need to investigate why we don't see this in tempus and piro unit testing. Will dig into that next.

Here's the traceback for one of the observers that shows how the circular include was injected:
 
```
In file included from /ascldap/users/rppawlo/tpls/trilinos/albany/include/Tempus_StepperDIRK.hpp:2:0,
                 from /ascldap/users/rppawlo/tpls/trilinos/albany/include/Tempus_StepperDIRKObserver.hpp:13,
                 from /ascldap/users/rppawlo/tpls/trilinos/albany/include/Tempus_StepperDIRK_decl.hpp:16,
                 from /ascldap/users/rppawlo/tpls/trilinos/albany/include/Tempus_StepperDIRK.hpp:1,
                 from /ascldap/users/rppawlo/tpls/trilinos/albany/include/Tempus_StepperFactory.hpp:20,
                 from /ascldap/users/rppawlo/tpls/trilinos/albany/include/Tempus_IntegratorBasic_impl.hpp:14,
                 from /ascldap/users/rppawlo/tpls/trilinos/albany/include/Tempus_IntegratorBasic.hpp:2,
                 from /ascldap/users/rppawlo/tpls/trilinos/albany/include/Piro_TempusSolver.hpp:49,
                 from /ascldap/users/rppawlo/tpls/trilinos/albany/include/Piro_SolverFactory_Def.hpp:67,
                 from /ascldap/users/rppawlo/tpls/trilinos/albany/include/Piro_SolverFactory.hpp:97,
                 from /ascldap/users/rppawlo/junk/ALBANY/Albany/src/Albany_SolverFactory.cpp:24:
```

**Comment by ikalash** [comment]
Glad to hear the scripts worked!  Thanks for fixing this, @rppawlo !  I have verified that your fix did indeed do the trick on my machine.  Closing this issue.
