### ISSUE TITLE
CUDA builds need new lambda options

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#179]
see trilinos/Trilinos#1717.

@ikalash  your CUDA build needs new options due to Tpetra starting to use lambdas, see trilinos/Trilinos#1682

**Comment by ikalash** [comment]
Thanks, @ibaned.  I have just added the new option to my Ride script.  Will see if it passes tonight.  I cannot access the CDash website as I am on foreign travel but I still get the emails from the job. 

@jewatkins : please note that you will need to add the configure option -D Kokkos_ENABLE_Cuda_LAMBDA:BOOL=ON to your CUDA Trilinos build from now on for the code to compile

**Comment by ibaned** [comment]
Thanks @ikalash !
`Kokkos_ENABLE_Cuda_Lambda` is the one.
I'll try to remember to check the build tomorrow and let you know how it goes.

**Comment by ikalash** [comment]
Thanks, @ibaned !  If things are good, please feel free to close this issue.

**Comment by jewatkins** [comment]
@ikalash Okay no problem. Thanks!

**Comment by ikalash** [comment]
I am finally back from travel and had a chance to look at the status of the Ride CUDA Albany CDash.  Unfortunately, most of the tests are failing now whereas before we had a clean dashboard: http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany&subproject=IKTRideAlbanyCUDA .  There are failed comparisons for some tests; others time out.  Anyone have any thoughts on what might be causing this?  I modified my Trilinos configure for this dashboard as follows to get the code to compile again: 

-DTrilinos_CXX11_FLAGS:STRING='-std=c++11 --expt-extended-lambda' \
-DKokkos_ENABLE_Cuda_Lambda:BOOL=ON

**Comment by ibaned** [comment]
Since you've added the flags to compile, I'm going to close this issue and open #182 for all the test failures.
