### ISSUE TITLE
Create a build system on the clusters

### ISSUE THREAD

**Issue by jtostie** [gahansen/Albany#18]
Improve usability and the ability to collaborate. Automate the process on a select few clusters. Can be accomplished by adding testing to the clusters.

**Comment by lxmota** [comment]
@calleman21 extended the module files to work on the CEE environment. I'm also dragging @jwfoulk since he has a strong interest in making this work on the big clusters.

**Comment by rjones-sandia** [comment]
Hi Alejandro
  Jeremy has some relevant experience too. We are running Albany/Lcm on skybridge and have interest in further automating the build.
Reese

Reese Jones
rjones@sandia.gov<mailto:rjones@sandia.gov> 925 294-4744
"There's almost nothing a little Python can't help" - anonymous.

On Jan 20, 2017, at 4:53 PM, Alejandro Mota <notifications@github.com<mailto:notifications@github.com>> wrote:


@calleman21<https://github.com/calleman21> extended the module files to work on the CEE environment. I'm also dragging @jwfoulk<https://github.com/jwfoulk> since he has a strong interest in making this work on the big clusters.

-

**Comment by lxmota** [comment]
@rjones-sandia I'm glad to include Jeremy in the discussion. Does he have a GitHub account to that I can reference him in this thread?

**Comment by lxmota** [comment]
Adding @j-templeton to the discussion.

**Comment by jwfoulk** [comment]
Although I do think that while modules are probably the way to go, I would also like to have a build moving forward that enables progress in the near term. A set of configuration files (Albany, Trillions) and instructions are found in Albany/doc/skybridge-chama, but I don't seem to have any luck running larger jobs (64 processors) without throwing exceptions (as of late). In addition, the tests (for the crystal plasticity models) run rather slow. I'm glad to try other flavors of gnu and open-mpi, but it would be good to know if others have had recent success.

**Comment by lxmota** [comment]
I guess then that the first order of business here is for me to create a Trilinos build on the clusters that is available to everyone.

That way those who only need a Trilinos build can use it directly, while those that need to customize their builds can use the configuration as a template, as suggested by @jtostie .

**Comment by ikalash** [comment]
I suggest we create a CDash build on the clusters (starting with Skybridge) that people could point to if they wanted a fresh, working Trilinos.  The CDash would also identify if/when the environment changes and our cmake scripts for Trilinos/Albany do not work anymore.  I could set this up, if it is of interest.

**Comment by jtostie** [comment]
This makes sense to me as we would get feedback when the build fails.

**Comment by ibaned** [comment]
Priority list discussed at LCM meeting today:

 - [ ] `skybridge`
 - [ ] `chama`

**Comment by ibaned** [comment]
All right, pull request #143 introduces a new LCM module:
```bash
module load lcm/cluster
module load serial-intel-release
```

I've just built Trilinos and Albany, and tested Albany, using that module.
A few things to be aware of:
1. Only the `intel` compiler module is supported, because that is all I see in Sierra's modules
2. The system uses TPL installs in my home directory. I think the permissions are set properly, but someone else should try it to confirm.

**Comment by ibaned** [comment]
This was tested on `skybridge`, I suspect it also works on `chama` but not sure.

**Comment by jwfoulk** [comment]
I will give that a whirl today/tonight. Thank you!

**Comment by jwfoulk** [comment]
Hi Dan - have you checked in lcm/cluster?  I don't see it in the repository. Thanks again.

**Comment by ibaned** [comment]
@jwfoulk its in a branch. I suppose its harmless enough, I'll merge it into master.

**Comment by ibaned** [comment]
Okay, should be in master now. Sorry for the confusion.

**Comment by jwfoulk** [comment]
Hi Dan - built just fine on chama. Thank you. I will try to run some big jobs later today and keep you in the loop. Thanks again.

**Comment by jwfoulk** [comment]
Hi Dan,

I apologize for the delay. I'm finally in a place where I would like to run on the clusters and I'm having issues loading the modules. 

There are issues loading lcm/sems that are compounded when I attempt to then load serial-intel-release. Sorry to be a pain. It seems like this stems from sems-env which is found on the CEE LAN at /projects/sems/modulefiles/projects but does not seem to show on the clusters. Note that the module file does exist on skybridge but is not "available". It does not show up using the module avail command. I have not problem loading the models on the CEE Lan. My only issue stems from skybridge.

Do you have the same issue?

Many thanks,

Jay

**Comment by lxmota** [comment]
Hi Jay,

You need to do:

  module load lcm/cluster
  module load serial-intel-release

Alejandro

**Comment by ibaned** [comment]
As @lxmota says, use `lcm/cluster` on the clusters, not `lcm/sems`.

**Comment by jwfoulk** [comment]
Yes. Reading is fundamental. I should actually reference the issue and not my memory. Many apologies. Thanks!

**Comment by ibaned** [comment]
I believe this can be closed.
