### ISSUE TITLE
Schwarz alternating doesn't check if Tempus is enabled

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#189]
@ikalash the public dashboards are failing to compile because they don't have Tempus enabled and Schwartz_alternating still tries to include Piro/Tempus headers:

http://my.cdash.org/viewBuildError.php?buildid=1300930

**Comment by ikalash** [comment]
Hmmm, this must have slipped through the tracks.  I'll look at it and fix it, hopefully later today.  Thanks for calling it to my attention @ibaned. It should be much easier to fix than pesky issue #187...

**Comment by ikalash** [comment]
@ibaned : I believe I fixed the problem.  Please let me know if that's not the case.

**Comment by ibaned** [comment]
Yep public dashboard compiled today. Thanks!
