### ISSUE TITLE
LCM: make Tempus a required dependency for LCM 

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#192]
@lxmota and I decide to make LCM have a required dependency on Tempus, since that is the time-integration-package-of-choice for LCM and to reduce the number of ifdefs within LCM.  I will change the cmake logic later today to throw an error if attempting to build LCM without Tempus.  Those who build Albany with LCM on need to rebuild their Trilinos with Tempus by adding to their Trilinos configure script the following lines: 

-D Trilinos_ENABLE_Tempus:BOOL=ON \
-D Tempus_ENABLE_TESTS:BOOL=OFF \
-D Tempus_ENABLE_EXAMPLES:BOOL=OFF \
-D Tempus_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \

@plindsa , I think this will affect your MOR stuff.

**Comment by lxmota** [comment]
@ikalash There are `#ifdef ALBANY_TEMPUS` compiler directives around the dynamic Schwarz loop. But Tempus is now a requirement for LCM. I think the compiler directives can be removed.

**Comment by ikalash** [comment]
Oh yes thanks for catching that @lxmota.  I'll fix it.

**Comment by lxmota** [comment]
Done!

**Comment by ikalash** [comment]
Thanks you beat me to it!
