### ISSUE TITLE
Remove Stochastic Galerkin functionality

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#197]

**Comment by agsalin** [comment]
I removed the Stochastic Galerkin capability in one large commit.

I removed the ENSEMBLE / Multi-point capability in a second commit, so it could be added back independently.

Both are contained on the branch RemoveEnsemble.

**Comment by ibaned** [comment]
SG removal diffstat:
> 235 additions and 24,985 deletions
MP removal diffstat:
> 9 additions and 11,096 deletions
Thats pretty significant in terms of lines of code...

**Comment by ibaned** [comment]
The nightlies were pretty clean this morning. Can I merge that branch today?

**Comment by ikalash** [comment]
Fine by me.

**Comment by agsalin** [comment]
Sure.

**Comment by ibaned** [comment]
Looks like there are a few merge conflicts in `Albany_Application` #211

**Comment by ibaned** [comment]
The merge conflicts were caused by @lxmota running `clang-format` on `Albany_Application` at the same time that @agsalin was making his changes. I did a little dance and resolved them, we'll see what the nightlies say.

Thanks again @agsalin !

**Comment by bartgol** [comment]
The ALBANY_STOKHOS macro is still there. Is this desired or was the purge supposed to remove Stokhos as a dependency altogether?

**Comment by agsalin** [comment]
@bartgol : There is code to use KL expansions for parameter fields that still sits within ALBANY_STOKHOS ifdef. This is independent of the other stokhos dependencies for stochastic Galerkin. That is a separate decision of whether it is worth keeping or pruning.

**Comment by bartgol** [comment]
That's fine. I wasn't advocating for its removal. I just wanted to make sure it wasn't something that was left behind.
