### ISSUE TITLE
undefined references

### ISSUE THREAD

**Issue by nschloe** [gahansen/Albany#2]
I'm trying to fix undefined references in Albany revealed by adding
```
IF(UNIX)
  set(CMAKE_SHARED_LINKER_FLAGS "-Wl,--no-undefined")
ENDIF()
```
In QCAD, I find that a `mathVector` is used all over the place, but nowhere defined. The code comments say the definition has moved to `QCAD_MathVector.hpp`, which doesn't exist.

**Comment by ambrad** [comment]
Hi Nico,

I find the file here (not in the QCAD directory):
    Albany/src/evaluators/QCAD_MathVector.hpp

Feel free to email me individually with more questions.

Cheers,
Andrew

**Comment by nschloe** [comment]
@ambrad Thanks! I'll dig some further.
