### ISSUE TITLE
Investigate what it would take to move away from the Epetra build in LCM

### ISSUE THREAD

**Issue by jtostie** [gahansen/Albany#20]
Want to improve the development cycle.

**Comment by ibaned** [comment]
This is closely tied to trilinos/Trilinos#313

**Comment by ibaned** [comment]
the resolution of trilinos/Trilinos#1023 will allow Epetra-free Trilinos builds, which is a prerequisite for this.

**Comment by ibaned** [comment]
trilinos/Trilinos#1023 was accepted into their `develop` branch, so soon an Epetra-free build of Trilinos for Albany will be possible, which closes trilinos/Trilinos#313. I can help people with configurations to get this going. I'd say we go ahead and close this for now, but reopen if there is another obstacle to Epetra-free LCM development.
