### ISSUE TITLE
Link error in Albany Ride CUDA CDash coming from MueLu

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#201]
It looks like there is a new link error in the Albany Ride CUDA CDash coming from MueLu: 

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=61662

tmpxft_0000339c_00000000-4_MueLu_RAPFactory.cudafe1.cpp:(.text._ZN6Xpetra20TripleMatrixMultiplyIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1
--

Any information from MueLu / Albany developers to help resolve this would be helpful.

**Comment by aprokop** [comment]
@ikalash Unfortunately, I don't have access to `cdash.sandia.gov`. Can you post the error context here? @jhux2 Is this something you can take a look at?

**Comment by ikalash** [comment]
@aprokop: here is the full error 

[100%] Linking CXX executable AlbanyT
/home/projects/albany/build/TrilinosInstall/lib/libmuelu.a(MueLu_RAPFactory.cpp.o): In function `
Xpetra::TripleMatrixMultiply<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::MultiplyRAP(Xpetra::Matrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, bool, Xpetra::Matrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, bool, Xpetra::Matrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, bool, Xpetra::Matrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Teuchos::RCP<Teuchos::ParameterList> const&)':
tmpxft_0000aa71_00000000-4_MueLu_RAPFactory.cudafe1.cpp:(.text._ZN6Xpetra20TripleMatrixMultiplyIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6SerialENS1_9HostSpaceEEEE11MultiplyRAPERKNS_6MatrixIdiiS6_EEbSB_bSB_bRS9_bbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKN7Teuchos3RCPINSL_13ParameterListEEE[_ZN6Xpetra20TripleMatrixMultiplyIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6SerialENS1_9HostSpaceEEEE11MultiplyRAPERKNS_6MatrixIdiiS6_EEbSB_bSB_bRS9_bbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKN7Teuchos3RCPINSL_13ParameterListEEE]+0x61c): undefined reference to `void Tpetra::TripleMatrixMultiply::MultiplyRAP<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>::classic> const&, bool, Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>::classic> const&, bool, Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>::classic> const&, bool, Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>::classic>&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Teuchos::RCP<Teuchos::ParameterList> const&)'
collect2: error: ld returned 1 exit status

You can see the issue is when linking Albany.  If you have any thoughts, that would be helpful.  I'm happy to share with you Albany configure scripts.

**Comment by aprokop** [comment]
The issue seems to have already been filed in trilinos/Trilinos#1906, and a patch pushed to `develop`.

**Comment by ikalash** [comment]
Hmmm, the link error was still there in last night's CDash.  It started at 8PM MST.  Perhaps the push to MueLu came later?  I can try building it again right now and report if the issue is still persisting.

**Comment by ikalash** [comment]
Indeed, the link error persists with a new develop Trilinos.

**Comment by aprokop** [comment]
@lucbv Luc, would you have time to look at this?

**Comment by lucbv** [comment]
@aprokop 
@jhux2 and I just looked at it and we are pretty confident that we found the source of this error.
I am almost ready to run the checkin script, I just need to check the epetra only case first.

**Comment by ikalash** [comment]
Thanks @lucbv!  I am happy to test the Albany ride build once the commit is pushed.

**Comment by lucbv** [comment]
@ikalash I have pushed a fix on develop, let me or @jhux2 know if the problem persist on Ride.

**Comment by ikalash** [comment]
@lucbv : unfortunately the issue persists.

**Comment by lucbv** [comment]
@ikalash , I am taking another crack at it, I will keep you posted.

**Comment by lucbv** [comment]
@ikalash I pushed another commit, I will check tomorrow morning and hopefully this will fix things on our dashboard as well as yours.

**Comment by ikalash** [comment]
Thanks @lucbv.  I will check the dashboard tomorrow as well and post here the outcome.

**Comment by ikalash** [comment]
I'm not able to determine if the MueLu error has been fixed b/c now there is a Trilinos compilation error stemming from Kokkos (Kokkos_Error.cpp): 

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=61825

/.../repos/Trilinos/packages/kokkos/core/src/impl/Kokkos_Error.hpp(76): error: namespace "Kokkos::Impl" has no member "cuda_abort"

Is the Kokkos team aware of this issue?

**Comment by ambrad** [comment]
This may be relevant: https://github.com/trilinos/Trilinos/issues/1919

**Comment by lucbv** [comment]
For some reason our builds did not pick up the latest commit, I created a build locally from github and got it to compile for an OPENMP_NO_SERIAL build which should trigger the problems you are having. It built fine but we have a failing test. I will wait for @cgcgcg to be back from travel to discuss this testing issue.
Let me know if problems persist on your end?

**Comment by ikalash** [comment]
@lucbv :  I am not sure I follow.  You are suggesting i have a configure option set that you did not have that is causing the build issue?

**Comment by lucbv** [comment]
@ikalash: no, I just do not have the ability to do a CUDA build easily on my local machine so I try to emulate it with an OPENMP one.
In any case, I think that it should build normally now.

**Comment by ikalash** [comment]
Ah ok, this is what i thought you meant but wanted to double check.  I'm traveling today so I'll probably just wait to see what happens in tonight's nightlies.

**Comment by lucbv** [comment]
Sounds good, I will be on travel tomorrow until next Monday but I will check emails and GitHub so feel free to bug me some more if things are not working correctly.

**Comment by ikalash** [comment]
Everything was good in yesterday's dashboard, so I am closing this issue.  Thanks @lucbv  for your help with this!
