### ISSUE TITLE
Subfolders in evaluators

### ISSUE THREAD

**Issue by bartgol** [gahansen/Albany#209]
The folder 'evaluator' is getting big, and with a too large font size listing its content takes more than one screen. Besides, there are evaluators that do conceptually different things. So I'm thinking we should probably create subfolders in it. I came to that conclusion by looking at the evaluators folder in LCM.

My suggestion is to add these subfolders:

- evaluators/interpolation (PHAL_*Interpolation*)
- evaluators/bc (Dirichlet*, Neumann)
- evaluators/load_save (for states)
- evaluators/gather_scatter (for solution/residual/params/egiendata,coords)
- evaluators/response (all evaluators with 'Response' in it)
- evaluators/pdes (CahnHIll*, NS*, Heat*,...)
- evaluators/utils (AddNoise,Field2Norm, ConvertFieldType,DOFCell2Side,Constant...)

Better names are always welcome. Perhaps the load_save and gather_scatter could be merged into 'inout'. Or we could differentiate load/gather that are from the mesh from those that are from Tpetra vectors (and same for save/scatter). This would put gathering coordinates in the same folder of loading states.

Thoughts?

**Comment by lxmota** [comment]
I'm all for it. But then again, I'm biased because that is what LCM does.

**Comment by mperego** [comment]
I also like it.

**Comment by ikalash** [comment]
Likewise.

**Comment by bartgol** [comment]
Any suggestion/comments on how to regroup the evaluators and/or the subfolders names? Otherwise I can go ahead and open a PR, so everyone can see how it would look like...

**Comment by lxmota** [comment]
Your proposal sounds good to me. So if you make a PR I'll take a look at it.

**Comment by ikalash** [comment]
I think this issue can be closed now.  Any objections?

**Comment by bartgol** [comment]
Agreed. Closed.
