### ISSUE TITLE
Link errors in Albany CUDA build on ride

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#221]
The Albany CUDA build on ride broke again last week due to changes in Trilinos.  Specifically, we get the following link errors.  I believe the problem started Friday.

[100%] Linking CXX executable AlbanyT
libalbanyLib.a(Albany_SolverFactory.cpp.o): In function `Albany::SolverFactory::checkSolveTestResultsT(int, int, Tpetra::Vector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaUVMSpace>, false> const*, Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaUVMSpace>, false> const*) const':
tmpxft_00000adb_00000000-4_Albany_SolverFactory.cudafe1.cpp:(.text+0x84f8): undefined reference to `Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaUVMSpace>, false>::getGlobalLength() const'
tmpxft_00000adb_00000000-4_Albany_SolverFactory.cudafe1.cpp:(.text+0x8570): undefined reference to `Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaUVMSpace>, false>::get1dView() const'
tmpxft_00000adb_00000000-4_Albany_SolverFactory.cudafe1.cpp:(.text+0x88f8): undefined reference to `Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaUVMSpace>, false>::getGlobalLength() const'
tmpxft_00000adb_00000000-4_Albany_SolverFactory.cudafe1.cpp:(.text+0x8a2c): undefined reference to `Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaUVMSpace>, false>::getNumVectors() const'
tmpxft_00000adb_00000000-4_Albany_SolverFactory.cudafe1.cpp:(.text+0x8a44): undefined reference to `Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaUVMSpace>, false>::get2dView() const'
tmpxft_00000adb_00000000-4_Albany_SolverFactory.cudafe1.cpp:(.text+0x8c88): undefined reference to `Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaUVMSpace>, false>::getNumVectors() const'
tmpxft_00000adb_00000000-4_Albany_SolverFactory.cudafe1.cpp:(.text+0x9074): undefined reference to `Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaUVMSpace>, false>::getNumVectors() const'
tmpxft_00000adb_00000000-4_Albany_SolverFactory.cudafe1.cpp:(.text+0x9268): undefined reference to `Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaUVMSpace>, false>::getGlobalLength() const'
tmpxft_00000adb_00000000-4_Albany_SolverFactory.cudafe1.cpp:(.text+0x9684): undefined reference to `Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaUVMSpace>, false>::getGlobalLength() const'

**Comment by ikalash** [comment]
@ibaned : continuing our discussion from the Albany meeting.  I think now the issue is not just Tpetra_Map but other Tpetra objects, e.g., Tpetra::MultiVector.  I looked in Albany_DataTypes.cpp where Tpetra_Map, Tpetra_MultiVector, etc. are defined and that looks OK to me: 

typedef Tpetra::Map<LO, GO, KokkosNode>                               Tpetra_Map;
typedef Tpetra::MultiVector<ST, LO, GO, KokkosNode>                   Tpetra_MultiVector;

Can you please expand on your conjecture about the a mismatch b/w Tpetra_Map and Tpetra::Map causing these issues?

**Comment by ibaned** [comment]
@ikalash we should check whether these types are enabled in Tpetra at compile time.  my pull request for always 64 bits does some of this (#219).

**Comment by ikalash** [comment]
Do you mean  HAVE_TPETRA_DOUBLE and HAVE_TPETRA_INST_DOUBLE?  These are not explicitly on in the Trilinos configure script, no.  Should they be?  I actually have ETI on in the Ride tests since I am not building LCM there and hence don't need DTK.

**Comment by ibaned** [comment]
yea, and I'm more worried about the ordinal types. so if you're trying to use `LO=int` and `GO=long long`, check `HAVE_TPETRA_INST_INT_LONG_LONG`.

**Comment by ikalash** [comment]
I see.  I don't have this on in Trilinos, no.  I can try to turn it on and see what happens.

**Comment by ikalash** [comment]
Follow up comment: it seems this configuration option greatly increases the compilation time of Trilinos.  My Trilinos has been building for 6 hours (on Ride with CUDA KokkosNode) and it is still not done (at 94%).

**Comment by ikalash** [comment]
Turning HAVE_TPETRA_INST_INT_LONG_LONG on did not fix the problem.  Here are the current link errors, which appear to be Tpetra-related:

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=62469

Any thoughts / suggestions?

**Comment by bartgol** [comment]
Looks like Xpetra is involved. Perhaps the trilinos installation is missing some Xpetra ETI? (shooting in the dark here).

**Comment by ikalash** [comment]
Right.  Tagging some Trilinos people who might have some thoughts: @aprokop, @mhoemmen (though probably everyone is at supercomputing this week...).

**Comment by mhoemmen** [comment]
@ikalash could you please protect your first post's error message with triple backquotes?  It's easier to read that way.  Thanks! :-)

**Comment by mhoemmen** [comment]
@ikalash wrote:
> Do you mean `HAVE_TPETRA_DOUBLE` and `HAVE_TPETRA_INST_DOUBLE`? These are not explicitly on in the Trilinos configure script, no. Should they be?

They are enabled by default.  I don't think it's possible to turn off `Scalar=double` in Trilinos currently.  A lot of downstream solver packages' examples would fail to build.

**Comment by mhoemmen** [comment]
The link errors appear to come from Albany wanting `GO=int`, but not getting it.  The macro to check is `HAVE_TPETRA_INST_INT_INT`.

I would love to get rid of all `GO` types but `long long` (or whatever 64-bit integer type people want); that would make everyone's lives so much easier :-) .

**Comment by ikalash** [comment]
@mhoemmen : I'll try setting HAVE_TPETRA_INST_INT_INT.  Just to clarify, you mean to set this as a configure option: -DHAVE_TPETRA_INST_INT_INT=BOOL:ON, is that right?  I currently have -DHAVE_TPETRA_INST_INT_LONG_LONG=BOOL:ON, per @ibaned 's suggestion.

**Comment by mhoemmen** [comment]
@ikalash That's not a CMake option, that's a macro.  Here are the CMake options of interest:
```
-D Tpetra_INST_INT_INT:BOOL=ON
-D Tpetra_INST_INT_LONG_LONG:BOOL=ON
```
Before you do that, though, ask yourselves why you're using both `GO=int` and `GO=long long`.  That shouldn't be happening in an application.  The application should just use one `GO` type (I prefer `long long` because it is always >= 64 bits).

**Comment by ikalash** [comment]
@ibaned is working on switching the code to just do GO = long long by default.  Dan, perhaps it makes sense to hold off on this issue until your 64bit default branch gets merged to master?

**Comment by ibaned** [comment]
sure. I'm actually going to opt for `std::int64_t`, which is much clearer in its intent.

**Comment by mhoemmen** [comment]
@ibaned That's OK, but be careful to match that to the right type.  This could be `long` on some platforms and `long long` on others.  (It's always a typedef.)

**Comment by ikalash** [comment]
@ibaned : what is the time frame of merging your branch into master?

**Comment by ibaned** [comment]
@ikalash not sure since I'm at a conference and also have other projects to work on

**Comment by ikalash** [comment]
I see.  Maybe in the mean time I can try the always-64-bit branch on Ride?  Is it more or less complete, just waiting to be merged, or there are still things you are planning to do in it?

**Comment by ibaned** [comment]
It should be complete, but I haven't had much time to compile and test

**Comment by ikalash** [comment]
Ok, thanks for the info.  I think I will switch the branch on Ride to see what happens.  Are the configure options D Tpetra_INST_INT_INT:BOOL=ON -D Tpetra_INST_INT_LONG_LONG:BOOL=ON still required in the always-64-bit branch @ibaned ?

**Comment by ibaned** [comment]
Only `-D Tpetra_INST_INT_LONG_LONG:BOOL=ON` should be required, because only a 64-bit `GO` is needed

**Comment by mhoemmen** [comment]
@ibaned Current defaults are `Tpetra_INST_INT_INT:BOOL=ON` and `Tpetra_INST_INT_LONG_LONG:BOOL=ON`, so you may have to turn the first of these off explicitly if you don't want `GO=int` to be enabled.

**Comment by ikalash** [comment]
I've made some progress on remedying this issue but unfortunately there is still an error having to do with Tpetra::CrsMatrix/Operator:

/.../build/TrilinosInstall/include/Teuchos_RCP.hpp(288): error: a value of type "Tpetra_CrsMatrix *" cannot be used to initialize an entity of type "Tpetra::Operator *"

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=63199

Thoughts?

**Comment by ibaned** [comment]
`Tpetra::Operator` has template parameters just like `Tpetra::CrsMatrix`. Somehow the defaults are not the same as what we choose to define `Tpetra_CrsMatrix`.

**Comment by ikalash** [comment]
Right, but I am not sure how to fix this, especially since it is in Trilinos, not on the Albany side.  @mhoemmen , do you have any suggestions?  Is the issue due to what we are setting the Ordinal type?

**Comment by bartgol** [comment]
I saw one error at line 541 of `QCADT_CoupledPoissonSchrodinger.cpp`, related to a call to `Thyra::createVectorSpace`. That function is used in other places already (it is a basic tpetra-thyra adapter routine), and I was wondering why it failed there and not in, say, `Albany_ModelEvaluatorT.cpp`. A quick look revealed that there the routine is invoked as

`something = Thyra::createVectorSpace<ST>(some_map)`

while in QCAD you see

`something = Thyra::createVectorSpace<ST,LO,GO,KokkosNode>(some_map)`.

The difference is very minimal, but it may be that explicitly adding `LO,GO,KokkosNode` in the templates arguments rather than letting the compiler deduce them messes up with they types compatibility. Why? I don't know. But we can try to remove those and see if it gets rid of the error. Again, I'm not sure why it fails with explicit arguments. Perhaps if you don't provide the arguments, the compiler is forced to look into what Tpetra_Map is, and deduces the correct arguments? Although I thought that a typedef was going to be resolved immediately...

**Comment by mhoemmen** [comment]
@ikalash This looks like some kind of issue with forward declarations.  CrsMatrix and Operator both have the same default template parameters.

@bartgol Does `Thyra::createVectorSpace` attempt to deduce `LO, GO, Node` from the input Map?  If so, then you shouldn't need to specify them.

**Comment by ikalash** [comment]
This is extremely frustrating... :(  I am trying a clean build rather than working with the nighly one which gets deleted/regenerated each night.  It will take some time to build.  I will report back whether adding the LO, GO, Node template arguments helps.  I was thinking too that they should be deduced from map, but then I suppose there could be some maps without all the template arguments floating around.  I can also see if turning off QCAD changes anything to try to pin-point the problem.

**Comment by mhoemmen** [comment]
@ikalash wrote:
> ... but then I suppose there could be some maps without all the template arguments floating around.

The issue could be whether or not the place that uses `Thyra::createVectorSpace` sees a full class declaration of `Tpetra::Map`, or just a forward declaration.  I've seen weird stuff like this with Nalu, which uses forward declarations aggressively.

**Comment by bartgol** [comment]
@mhoemmen wrote:

> Does `Thyra::createVectorSpace` attempt to deduce `LO, GO, Node` from the input Map? If so, then you shouldn't need to specify them.

I believe so. The signature is

`template <class Scalar, class LocalOrdinal, class GlobalOrdinal, class Node>
RCP<const VectorSpaceBase<Scalar> >
createVectorSpace(const RCP<const Tpetra::Map<LocalOrdinal,GlobalOrdinal,Node> > &tpetraMap);`

So you don't need to specify the last three template arguments. However, I don't 100% understand why manually specifying them causes a problem.

@ikalash wrote:

> I will report back whether adding the LO, GO, Node template arguments helps

Just to be clear, not adding them, but rather removing them. Let the compiler deduce them. That's what happens (successfully) in `Albany_ModelEvaluatorT.cpp`, while the QCAD class explicitly specifies them.

**Comment by ikalash** [comment]
I see.  I know that Dan added arguments earlier when creating Tpetra::Maps to attempt to correct a similar problem; but now I see from the discussion why you may need them for the Map but not the CrsMatrices/Operators.  I'll post the outcome when my builds complete and I've had a chance to play with these template arguments.

**Comment by mhoemmen** [comment]
@bartgol wrote:
> However, I don't 100% understand why manually specifying them causes a problem.

That should only be a problem if they don't match the input Map.

**Comment by bartgol** [comment]
In our case they do match. But as I said, we use that method in the very same way somewhere else, and the only difference is that in the other place we do not explicitly pass the template types that can be deduced by the compiler. That is the only difference.

**Comment by ikalash** [comment]
I've rebuilt everything with QCAD turned off (to avoid this morning's problem to see if there are any other issues) and also with the following configure options in Trilinos: 

 -D Tpetra_INST_INT_LONG_LONG:BOOL=ON \
 -D Tpetra_INST_INT_INT:BOOL=OFF \

which apparently did not get added to the nightly Trilinos configure script when I switched to the always-64-bit branch of Albany.  Now I am getting the following error:

/ascldap/users/ikalash/nightlyDebug/Albany/src/adapt/AAdapt_RC_Manager.cpp(227): error: no instance of overloaded function "Tpetra::CrsMatrix<Scalar, LocalOrdinal, GlobalOrdinal, Node, classic>::insertGlobalValues [with Scalar=ST, LocalOrdinal=Tpetra_LO, GlobalOrdinal=Tpetra_GO, Node=KokkosNode, classic=false]" matches the argument list

@mhoemmen : why would insertGlobalValues not like the arguments?  Sorry to keep bugging you...  I still have a lot to learn about the inner workings of these template arguments and how they get passed around.  I hope to resolve all these issues this week once and for all.

**Comment by ibaned** [comment]
@ikalash I'm guessing that the array of global indices passed to `insertGlobalValues` contains `Albany::GO` values as opposed to `Albany::Tpetra_GO` values. Even though they are the same size, these are different types now (`long` vs `long long`) and I think thats the reason for most of the difficulties.

**Comment by ikalash** [comment]
That seems plausible @ibaned .  How do we fix them to make them consistent?

**Comment by ikalash** [comment]
I see you added the Albany::Tpetra_GO typedef to Albany_DataTypes.hpp.  Where is the code getting Albany::GO?

**Comment by ibaned** [comment]
It may be as simple as changing [this declaration](https://github.com/gahansen/Albany/blob/master/src/adapt/AAdapt_RC_Manager.cpp#L217) to be
```cpp
Teuchos::Array<Tpetra_GO> cols;
```
instead.

For your second question, in this branch `Albany::GO` is now always `std::int64_t`.

**Comment by bartgol** [comment]
@ibaned you nailed it! That's also why all the other errors were there: we were explicitly setting the template arguments to `LO` and `GO`, which did not match the ones in `Tpetra_Map,Tpetra_Operator,Tpetra_CrsMatrix`.

Perhaps a better way to do it (rather than using `GO` or `Tpetra_GO`) is to get the type from the object itself (in case someone willingly/unwillingly changes the typedefs):

` Teuchos::Array<decltype(M_)::global_ordinal_type> cols;`

This should *always* have the correct type for the matrix you use.

**Comment by ibaned** [comment]
@bartgol thats clever, I didn't know about that typedef. Either way works, in theory if it is a Tpetra data structure then it should be using `Tpetra_GO`. But yea, I think most of the errors can be fixed by switching `GO` to `Tpetra_GO` in key places.

**Comment by ikalash** [comment]
I see, so there are these mis-matched types potentially still floating around.  Does the code compile fine w/o CUDA, I am curious, or this only shows up with CUDA?  I have only tried to compile the always-64-bit branch with CUDA in hopes it will resolve other build issues that cropped up a couple weeks ago.

**Comment by ibaned** [comment]
@ikalash its possible this happens without CUDA too

**Comment by ikalash** [comment]
I think it must, but I have not tested it.  There are numerous type mismatches in the always-64-bit branch of Albany, it looks like.  I am working on fixing them with the CUDA node.  Most of the fixes are involving changing GO to Tpetra_GO.  Dan, are you OK with me pushing these fixes to the always-64-bit branch when I'm done?  I'm concerned that maybe things will break if I push them, in the case things were working for you before (or you did not try compiling, so you don't know?).

**Comment by ibaned** [comment]
@ikalash thanks! by all means please push the changes, I'm sure they will improve the situation because I did very little compiling of this branch.

**Comment by ikalash** [comment]
Ok, great.  I am a bit worried that I am changing the types somewhat blindly, but I guess the compiler detects this.  I will keep you posted @ibaned and may bug you more if I have issues.  So far things are going pretty smoothly (albeit slowly since there are so many errors).

**Comment by ikalash** [comment]
I have fixed the build errors with the always-64-bit branch but unfortunately it does not fix the original problem that this issue is about, the following link error:

[100%] Linking CXX executable AlbanyAnalysisT
nvcc_wrapper - *warning* you have set multiple optimization flags (-std=c++1* or --std=c++1*), only the first is used because nvcc can only accept a single std setting
Scanning dependencies of target AlbanyT
[100%] Building CXX object src/CMakeFiles/AlbanyT.dir/Main_SolveT.cpp.o
nvcc_wrapper - *warning* you have set multiple optimization flags (-std=c++1* or --std=c++1*), only the first is used because nvcc can only accept a single std setting
/ascldap/users/ikalash/nightlyDebug/Albany/src/Albany_ObserverImpl.hpp(13): warning: overloaded virtual function "Albany::StatelessObserverImpl::observeSolutionT" is only partially overridden in class "Albany::ObserverImpl"

/ascldap/users/ikalash/nightlyDebug/Trilinos/build/install/include/Intrepid2_BasisDef.hpp(247): warning: statement is unreachable

/ascldap/users/ikalash/nightlyDebug/Trilinos/build/install/include/Intrepid2_BasisDef.hpp(251): warning: statement is unreachable

/ascldap/users/ikalash/nightlyDebug/Trilinos/build/install/include/Intrepid2_BasisDef.hpp(255): warning: statement is unreachable

/ascldap/users/ikalash/nightlyDebug/Trilinos/build/install/include/Phalanx_Evaluator_WithBaseImpl_Def.hpp(429): warning: statement is unreachable
      
/ascldap/users/ikalash/nightlyDebug/Albany/src/Albany_ObserverImpl.hpp(13): warning: overloaded virtual function "Albany::StatelessObserverImpl::observeSolutionT" is only partially overridden in class "Albany::ObserverImpl"
    
libalbanyLib.a(Albany_SolverFactory.cpp.o): In function `.LTHUNK2148':
tmpxft_0001a4e4_00000000-4_Albany_SolverFactory.cudafe1.cpp:(.text._ZNK6Xpetra9TpetraMapIilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_4CudaENS1_12CudaUVMSpaceEEEE7getCommEv[_ZNK6Xpetra9TpetraMapIilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_4CudaENS1_12CudaUVMSpaceEEEE7getCommEv]+0x20): undefined reference to `Tpetra::Map<int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaUVMSpace> >::getComm() const'
libalbanyLib.a(Albany_SolverFactory.cpp.o): In function `.LTHUNK2149':
libalbanyLib.a(Albany_SolverFactory.cpp.o): In function `.LTHUNK2143':
tmpxft_0001a4e4_00000000-4_Albany_SolverFactory.cudafe1.cpp:(.text._ZNK6Xpetra9TpetraMapIilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_4CudaENS1_12CudaUVMSpaceEEEE19isNodeGlobalElementEl[_ZNK6Xpetra9TpetraMapIilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_4CudaENS1_12CudaUVMSpaceEEEE19isNodeGlobalElementEl]+0x18): undefined reference to `Tpetra::Map<int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaUVMSpace> >::isNodeGlobalElement(long) const'
libalbanyLib.a(Albany_SolverFactory.cpp.o): In function `.LTHUNK2142':
tmpxft_0001a4e4_00000000-4_Albany_SolverFactory.cudafe1.cpp:(.text._ZNK6Xpetra9TpetraMapIilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_4CudaENS1_12CudaUVMSpaceEEEE18isNodeLocalElementEi[_ZNK6Xpetra9TpetraMapIilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_4CudaENS1_12CudaUVMSpaceEEEE18isNodeLocalElementEi]+0x18): undefined reference to `Tpetra::Map<int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaUVMSpace> >::isNodeLocalElement(int) const'
libalbanyLib.a(Albany_SolverFactory.cpp.o): In function `.LTHUNK2141':
tmpxft_0001a4e4_00000000-4_Albany_SolverFactory.cudafe1.cpp:(.text._ZNK6Xpetra9TpetraMapIilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_4CudaENS1_12CudaUVMSpaceEEEE18getNodeElementListEv[_ZNK6Xpetra9TpetraMapIilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_4CudaENS1_12CudaUVMSpaceEEEE18getNodeElementListEv]+0x20): undefined reference to `Tpetra::Map<int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaUVMSpace> >::getNodeElementList() const'

I am not sure how to proceed...  I guess I will push my changes to always-64-bit branch Albany since I think they are required for the code to compile...  but this issue is still open.

**Comment by mhoemmen** [comment]
Is this issue relevant? https://github.com/trilinos/Trilinos/issues/1683

**Comment by mhoemmen** [comment]
See also lines 563-576 of tpetra/CMakeLists.txt: https://github.com/trilinos/Trilinos/blob/a1a7bc84a637defc79f5d64e2f7da48accd6edfd/packages/tpetra/CMakeLists.txt#L563

**Comment by bartgol** [comment]
I don't think this is the issue, but I believe we should also use `Tpetra_LO` in place of `LO` in all Tpetra types.

**Comment by ibaned** [comment]
@bartgol although that is correct in principle, both of the `LO` types should always be `int` right now.

**Comment by ibaned** [comment]
@ikalash I just tried to compile this branch in a non-CUDA build, and there were still lots of `Tpetra_GO` issues that I fixed (including these undefined references to Tpetra types with `GO=long`). Could you please try the latest 64 bit branch?

**Comment by bartgol** [comment]
True, that's why I said I don't think would fix the issue. But if we have a `Tpetra_LO` type declared, we better use it, otherwise confusion will ensue, and we would be better off with just `LO` everywhere.

**Comment by ikalash** [comment]
@ibaned : sure, I will try it now.  As I mentioned in my commit message yesterday, I only fixed the errors when LCM, ATO and MOR are OFF (they don't work in the CUDA build so they are not on).  Probably the errors you saw with Tpetra_GO were in those physics.  I'll report back what happens with a most up-to-date version of the branch.  Thanks for your help!

**Comment by ikalash** [comment]
It builds now!!!  Thanks for fixing this, @ibaned!  I will verify that the nightly build scheduled for tonight done by Jenkins is OK, and if it is, I will close this issue.

**Comment by ikalash** [comment]
Finally, this is fixed (on always-64-bit branch of Albany)!  Thanks @ibaned !
