### ISSUE TITLE
Albany build failures due to changes in Tpetra?

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#224]
The nightly tests are failing again, it appears perhaps due to changes in Tpetra:

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=62700

@mhoemmen: has the isLocallyFitted method changed?

**Comment by mhoemmen** [comment]
@ikalash I noticed that you closed this; is everything OK?

I've been removing header file includes from `Teuchos_ConfigDefs.hpp`.  I did it one header at a time, in hopes of catching potential downstream errors.  The point is to improve build time by not having the "one header to rule them all" that includes everything and stomps on the global namespace.

**Comment by ikalash** [comment]
@mhoemmen : turns out this was a false alarm, but thanks for following up!

**Comment by mhoemmen** [comment]
@ikalash Thanks!  Good news for me after coming back from visiting family :-) .
