### ISSUE TITLE
Sensitivities of transient solves

### ISSUE THREAD

**Issue by juan42** [gahansen/Albany#225]
We are trying desperately to setup a linear elasticity problem for a model calibration (or parameter fitting) case. In the steady solve we get sensitivities w.r.t the E-Modulus, which is fine, but we can not find a case where this is achieved for a transient case.

Are transient adjoint sensitivities implement in some combination we are not aware of? If yes, could you point us to the corresponding bits or input files?

If you have other suggestions (maybe the transient case is not suitable for model calibration) please let me know.

**Comment by juan42** [comment]
Thanks for the explanation!

So it is not even possible to use the old solver stack (including Rythmos) to do that?

**Comment by ikalash** [comment]
I am afraid Rythmos is not an option for elasticity, as Rythmos does not have any schemes for 2nd-order in time ODEs (e.g., Newmark Beta).  

Now, there _are_ 2nd order in time ODE integrators in Piro, e.g., Piro_Epetra_NewmarkSolver, Piro_TrapezoidRuleSolver_Def.hpp, Piro_VelocityVerletSolver_Def.hpp.  The former 2 are tpetra/thyra-based and it looks like there is some support for sensitivities there.  @gahansen is the original author of those classes - Glen, can you please weigh in?  One caveat is I am not sure to what extent the Piro 2nd order in time integrators have been verified - I believe some folks have had issues with them but I am not sure.  @ibaned , did you ever work with these solvers while at RPI?  I seem to recall the RPI guys may have been using them at some point.

**Comment by juan42** [comment]
We tried the Trapezoid Rule and Velocity Verlet solver while switching options around and both seemed to work fine. But we didn't have any luck getting sensitivities out.

**Comment by ikalash** [comment]
I am not sure if anyone has tried the sensitivities with these schemes.  You could look in Piro::TrapezoidalRule and search for sensitivities code to try to debug what is going on.
