### ISSUE TITLE
Bug in Epetra <-> Tpetra CrsMatrix converters in Petra::Converters class in parallel

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#237]
@plindsa has discovered another parallel issue in Albany having to do with Jacobians.  For certain problems, specifically thermo-mechanical problems, it appears there is an issue with the Epetra <-> Tpetra CrsMatrix converters in the Petra::Converters class - the converted matrices are not correct when run in parallel.  It is somewhat of a mystery (to me at least) why this would happen for thermo-mechanical but not other problems that I spot-checked.  Since the converters are only used when running Albany, not AlbanyT, the issue would not affect any LCM runs which are all Tpetra-based; but it should nonetheless be fixed.

**Comment by plindsa** [comment]
I have a fix for the converter that I noticed was failing (@ikalash has verified that it works), and I'll also try to check on the other converters and make any changes those need as well.
