### ISSUE TITLE
Move aeras-mdrange branch to tag

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#238]
@ibaned @jwatkins : can one of you please move the aeras-mdrange branch to a tag like we discussed at one of the albany meetings?  We have the opportunity to edit the aeras kokkos paper till jan 10 and can change the draft to mention the tag instead of the branch.

**Comment by ibaned** [comment]
Done, its here now https://github.com/gahansen/Albany/releases/tag/aeras-mdrange
