### ISSUE TITLE
Trilinos for Albany build error on Ride with CUDA KokkosNode

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#240]
Last night's Albany build on Ride did not go through due to a build error in Trilinos coming from TpetraExt_MatrixMatrix_def.hpp:

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=64991

@mhoemmen, any thoughts?

**Comment by mhoemmen** [comment]
@ikalash @csiefer2 would know what's going on with that thing :-) .  He's been working on the CUDA and OpenMP specializations.

**Comment by csiefer2** [comment]
Working on fixing it.

**Comment by ikalash** [comment]
Thanks @csiefer2 .  I'm happy to test the fix once it's ready.

**Comment by csiefer2** [comment]
Checkin script is running.

**Comment by csiefer2** [comment]
Checked in. @ikalash please close this bug if the Albany nightlies are clean tonight.

**Comment by mhoemmen** [comment]
Thanks @csiefer2 ! :D

**Comment by ikalash** [comment]
Appears to be resolved now.  Thanks @csiefer2 !
