### ISSUE TITLE
Slowdowns for tempus tests on 1/11/18

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#243]
@lxmota and I discovered that on 1/11/18, some of the Tempus tests in Albany got substantially (5x!) slower: 

Last good (fast) run: http://cdash.sandia.gov/CDash-2-3-0/testSummary.php?project=10&name=Schwarz_Alternating_Dynamics_Cubes&date=2018-01-10
First bad (slow) run: http://cdash.sandia.gov/CDash-2-3-0/testSummary.php?project=10&name=Schwarz_Alternating_Dynamics_Cubes&date=2018-01-11

Looking at the log, there were no nontrivial commits to Albany, so I believe the cause of this was on the Trillions side.  @ccober6, @sconde : I see there were some commits on 1/10 to Tempus.  Is it possible that they are the cause of this issue?  I will dig in by doing bisection on Trillions to ID the problematic commit, but I wanted to check if you have any thoughts to save me some time.

**Comment by sconde** [comment]
@ikalash are the tests running constant time step or variable? does the number of time steps taken increase?

**Comment by ccober6** [comment]
In 7f8fc084e2b8d652b18fe0451d714be62910ca04 I changed the TimeStepControl around a little bit, which I hoped did not change anything (tests passed and runtimes did not change!), but it could have changed how the timestep was selected.  Are you seeing a lot of additional output about changing the dt?

**Comment by ikalash** [comment]
@ccober6, @sconde : For these test, I am setting "Integrator Step Type: Constant", so there should not be any time-step variation.  You can have a look at the verbose output of the test here: 

1/10 run: http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3387871&build=65282
1/11 run (11x slower): http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3390813&build=65335 

I don't believe dt is changing from the output (as it shouldn't for constant integrator step type).  But you can see there are many more residual fills in the 1/11 run (4082 vs. 3159): 

1/10:  Albany Fill: Residual                                                                          2.6662e+00 (3159)
1/11:  Albany Fill: Residual                                                                          8.7333e+00 (4082)      

So it looks like more nonlinear systems are solved starting 1/11.  Let me know if you have any thoughts.  The stepper used is the Newmark Implicit d-Form. 

I'll work on figuring out which commit specifically broke things tomorrow.  I am sure it's in Trilinos since all the commits to Albany had to do with documentation / build scripts - no changes to the actual source code.

**Comment by ikalash** [comment]
For Albany developers: this issue is the reason for failures in the dashboard.

**Comment by sconde** [comment]
@ikalash @ccober6 from what I can see, the `Time Step` was changed from `1.0e-01` to `5.000e-02`. Is this the time step for stepper?

**Comment by ikalash** [comment]
Sorry, @sconde , I messed up the first link I put above.  That was for a quasistatic instead of a dynamic problem, and a different time step was used.  Here are the right links:

1/10 run: http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3387873&build=65282
1/11 run (slower one): http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3390813&build=65335

Scrap my comment about the number of residuals - they are the same as 1/10.  It seems there are the same number of time steps with the same dt, but the run is just taking much much slower. 

I have narrowed down that the issue was introduced b/w Trilinos commits:

7a4fc3167f68311303d555e529439fd32f3cf982 (fast) 
025c644d06ed78fc289505e08b1193853972a67d (slow)

For both of these I am using an up-to-date Albany, which confirms that Trilinos caused the problem, not Albany.

**Comment by sconde** [comment]
@ikalash @ccober6 That commit in Tempus is when I moved the integrator out to the observer basic. I'll have to double check again, but Tempus/Drekar tests did not slow down when I had made the changes.

My apologies for this inconvenience. I will update you once I get more information

**Comment by ikalash** [comment]
No problem, @sconde .  I have some additional information.  I will open a Trilinos issue and post it there shortly, since this is really a Trilinos problem.

**Comment by ikalash** [comment]
I have opened a Trilinos issue for this problem: https://github.com/trilinos/Trilinos/issues/2163 .

**Comment by sconde** [comment]
@ikalash @ccober6 I think I've caught my mistake. In `ObserverBasic`'s `observeAcceptedTimeStep`, the output was performed at each time steps. The conditional statement got left in the `IntegratorBasic`.

This didn't affect the tests in Tempus/Drekar as drastically as it did with Albany. So I'm not sure if it's the solution. Either way, I will open up a PR.

**Comment by ikalash** [comment]
Thanks for tracking it down, @sconde !  I'm happy to test things with your PR once it's ready to determine if your fix brings the Albany test runtiimes down to what they were before.

**Comment by ikalash** [comment]
This should be fixed now (see https://github.com/trilinos/Trilinos/issues/2163).
