### ISSUE TITLE
Accessing solution MDField in (cell, node, dim) instead of (cell, qp, dim) form inside Evaluator

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#244]
I have a question about something that should be very straightforward but may not be given Albany's design. 

I would like to have access to a solution field at the with the (cell, node, dim) layout instead of the (cell, qp, dim) inside an Albany physics evaluator.  An MDField with the (cell, node, dim) layout is created by the PHAL::GatherSolution evaluator, but then it seems when PHAL::DOFVecInterpolation is called, this field gets over-written with the same field but interpolated to the quad pts (so it now has the (cell, qp, dim) layout).  Is it possible to store somehow the original field with the (cell, node, dim) prior to the interpolation for use in an evaluator, so I do not have to duplicate the logic in PHAL::GatherSolution inside my evaluator to get the solution at the nodes?

**Comment by mperego** [comment]
@ikalash Even if the fields names are the same, if the layouts are different, the fields will be different. So I don't think that  PHAL::DOFVecInterpolation will overwrite the nodal field. After the interpolation operator both the solution on the nodes and that on the quadrature points should be available.

**Comment by bgranzow** [comment]
echoing @mperego, in past experience I noticed that Phalanx didn't overwrite fields with the same name but different data layouts. So if you're initializing an MDField member in a constructor initializer list that gets passed the `Albany::Layouts` struct with the variable name `dl`, I think you should be able to initialize the solution field as:
```
u("Field Name", dl->node_vector)
```
and the field should exist. (Assuming of course that the solution is a [vector at nodes](
https://github.com/gahansen/Albany/blob/master/src/problems/Albany_Layouts.hpp#L39).

**Comment by ikalash** [comment]
Interesting!  I guess this is part of the MDField / Phalanx magic.  Is it possible to have an evaluator depend on a field at the quad points and the same field at the nodes?  This is what I'd really like to do.  Would something like this be done then? 
```
u_node("Field Name", dl->node_vector),
u_qp("Field Name", dl->qp_vector)
```
I am used to a field depending on a string that gives its name, and it seems to me it might be problematic to have 2 fields with the same name (although the DOFInterpolation classes do just that).

**Comment by mperego** [comment]
Yes, I think it is possible to have such an evaluator. 
I think the idea of the MDField is that the name denotes the physical object and the layout the discretization used, so it is ok to use the same name for two different fields.

**Comment by ikalash** [comment]
Thanks for the tips, guys!  I'll give this a try tomorrow.

**Comment by rppawlo** [comment]
Jus tto follow up on the phalanx design. Fields are differentiated by the unique identifier string returned from the tag. Since tag is pure virtual, apps can determine how these tags are constructed. Albany uses the default Tag class in phalanx. This class builds the tag as a combination of the field name, plus the field type, plus the string identifier returned from the DataLayout class (DataLayout is also virtual so you can overload the identifier). So you can differentiate based on data layout or even scalar type. Note that the particular data layout you use can also accept a string name during construction if the tag names in two layouts are the same.

**Comment by ikalash** [comment]
Thanks for the detailed explanation, @rppawlo .  My confusion was in that I thought the unique identifier was tied to the string associated with the field.
