### ISSUE TITLE
Failing  FO_AIS_16km_MueLu test with OpenMP and CUDA KokkosNode

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#245]
The  FO_AIS_16km_MueLu  test began failing this morning in my OpenMP and CUDA builds.  Here is the verbose output: 

Ride (CUDA): http://cdash.sandia.gov/CDash-2-3-0/testSummary.php?project=10&name=FO_AIS_16km_MueLu&date=2018-01-16 
OpenMP: http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3401217&build=65545 

@mperego can you please have a look?  I think this is likely related to your checkins yesterday.

**Comment by mperego** [comment]
@ikalash I don't see how my changes could have affected this test but not all the other FELIX tests. Unfortunately the error message does not tell much to me. Do we have an OpenMP build on a machine I can access to? e.g. the cee machines?

**Comment by ikalash** [comment]
@mperego: my OpenMP build is on my workstation, camobap.ca.sandia.gov.  I will give you an account on the machine and follow up offline about how to access the build there.

**Comment by mperego** [comment]
@ikalash It seems this is related to this trilinos/Trilinos#2161.
If you agree would hold off this until that issue is fixed.

**Comment by mperego** [comment]
Actually, I'm not sure is related. I'll keep looking into this

**Comment by mperego** [comment]
@ikalash It is a MueLu issue. I tried using Ifpack2 and it worked fine.

**Comment by ikalash** [comment]
Oh ok thanks for diagnosing the problem.  Is there already an open  muelu issue or  i should open one?

**Comment by mperego** [comment]
There is one (trilinos/Trilinos#2161) not sure it is exactly the same issue.

**Comment by ikalash** [comment]
OK, this is the one you referenced earlier.  I will watch that issue and see if it fixes this problem.  Thanks.

**Comment by ikalash** [comment]
It appears this has finally been fixed by @crtrott - see https://github.com/trilinos/Trilinos/issues/2161#issuecomment-370274598 .  Thanks, Christian!!
