### ISSUE TITLE
Compile error after changes to PHAL_Utilities_Def.hpp

### ISSUE THREAD

**Issue by lxmota** [gahansen/Albany#247]
@ibaned After commit https://github.com/gahansen/Albany/commit/7660bba3effb1ab19302330dc32f8b5f681272b4 I get the following compile error:

`/home/amota/LCM/Albany/src/./PHAL_Utilities_Def.hpp:224:31: error: ‘reconstructLayout’ is not a member of ‘Kokkos::Impl’
   auto layout = Kokkos::Impl::reconstructLayout(src.layout(), src.rank());
                               ^~~~~~~~~~~~~~~~~
/home/amota/LCM/Albany/src/./PHAL_Utilities_Def.hpp:224:31: note: suggested alternative:
In file included from /home/amota/LCM/trilinos-install-serial-gcc-release/include/Intrepid2_Types.hpp:52:0,
                 from /home/amota/LCM/trilinos-install-serial-gcc-release/include/Intrepid2_Polylib.hpp:100,
                 from /home/amota/LCM/Albany/src/./Albany_StateInfoStruct.hpp:24,
                 from /home/amota/LCM/Albany/src/./disc/Albany_AbstractDiscretization.hpp:22,
                 from /home/amota/LCM/Albany/src/./PHAL_Workset.hpp:26,
                 from /home/amota/LCM/Albany/src/./PHAL_AlbanyTraits.hpp:303,
                 from /home/amota/LCM/Albany/src/evaluators/pde/PNP_PotentialResid.cpp:7:
/home/amota/LCM/trilinos-install-serial-gcc-release/include/Kokkos_DynRankView.hpp:211:3: note:   ‘Kokkos::Experimental::Impl::reconstructLayout’
   reconstructLayout( const Layout& layout , iType dynrank )
   ^~~~~~~~~~~~~~~~~
In file included from /home/amota/LCM/Albany/src/./PHAL_Utilities.hpp:210:0,
                 from /home/amota/LCM/Albany/src/evaluators/pde/PNP_PotentialResid_Def.hpp:11,
                 from /home/amota/LCM/Albany/src/evaluators/pde/PNP_PotentialResid.cpp:10:
/home/amota/LCM/Albany/src/./PHAL_Utilities_Def.hpp: In function ‘typename std::enable_if<Kokkos::is_dynrankview_fad<Kokkos::Experimental::DynRankView<D, P ...> >::value, typename Kokkos::Experimental::DynRankView<DataType, Properties>::non_const_type>::type PHAL::create_copy(const string&, const Kokkos::Experimental::DynRankView<D, P ...>&)’:
/home/amota/LCM/Albany/src/./PHAL_Utilities_Def.hpp:243:27: error: ‘reconstructLayout’ is not a member of ‘Kokkos::Impl’
   auto ml = Kokkos::Impl::reconstructLayout(sl, real_rank);
                           ^~~~~~~~~~~~~~~~~
/home/amota/LCM/Albany/src/./PHAL_Utilities_Def.hpp:243:27: note: suggested alternative:
In file included from /home/amota/LCM/trilinos-install-serial-gcc-release/include/Intrepid2_Types.hpp:52:0,
                 from /home/amota/LCM/trilinos-install-serial-gcc-release/include/Intrepid2_Polylib.hpp:100,
                 from /home/amota/LCM/Albany/src/./Albany_StateInfoStruct.hpp:24,
                 from /home/amota/LCM/Albany/src/./disc/Albany_AbstractDiscretization.hpp:22,
                 from /home/amota/LCM/Albany/src/./PHAL_Workset.hpp:26,
                 from /home/amota/LCM/Albany/src/./PHAL_AlbanyTraits.hpp:303,
                 from /home/amota/LCM/Albany/src/evaluators/pde/PNP_PotentialResid.cpp:7:
/home/amota/LCM/trilinos-install-serial-gcc-release/include/Kokkos_DynRankView.hpp:211:3: note:   ‘Kokkos::Experimental::Impl::reconstructLayout’
   reconstructLayout( const Layout& layout , iType dynrank )
   ^~~~~~~~~~~~~~~~~
`

**Comment by ibaned** [comment]
@lxmota okay, we can revert that for now then, but it will be needed once the next Kokkos promotion goes up (February)

**Comment by lxmota** [comment]
Sounds good to me.

**Comment by lxmota** [comment]
Revert https://github.com/gahansen/Albany/commit/b12b4e2bc3ca4fb59b2d24963ea78faa5c15fe90
for the time being.
