### ISSUE TITLE
Lots of failing FELIX tests

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#249]
A lot of FELIX tests started failing last night: 

http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlyfailed&buildid=65661

@mperego , could this be related to your merge?  I noticed that all of them except the MueLu one are running the Albany (Epetra) executable, which would not have been tested in my Ride test yesterday (with CUDA, we only run AlbanyT).

**Comment by mperego** [comment]
It could.. but I had tested it on Jenga and my machine and they were working fine. I'll have a look at it.

**Comment by ikalash** [comment]
Thanks, @mperego.  It looks like the comparisons are failing for all the tests.

**Comment by mperego** [comment]
OK, it's not because of my commits. It should be fixed now.

**Comment by ikalash** [comment]
Oh...  that was Jerry's commit.  Sorry about that, I blamed you in error.  Thanks for fixing it!

**Comment by mperego** [comment]
No worries! It did not take me much to find and fix it.
