### ISSUE TITLE
LCM: Modules broken for Intel compiler on SEMS

### ISSUE THREAD

**Issue by lxmota** [gahansen/Albany#254]
Something changed in the SEMS environment that broke the modules system for the Intel compiler, thus the failures in CDash for this build.

Looking at it, it seems that the mixture of Sierra and SEMS modules worked by sheer luck, and that a clean up is in order.

I think that the best way to move forward is to try to base the LCM modules on the SEMS platform on Sierra modules, which seem to be more stable that the SEMS modules. Hopefully that won't turn out to be too difficult.

**Comment by bartgol** [comment]
I haven't been able to use intel compilers (whatever version) in sems ever since I switched to the RN (O(3)months ago). It seemed to be related with a problem with the verification of the intel license file. Notice that the sems intel compilers on the ON work fine though.

**Comment by lxmota** [comment]
I managed to finally fix this but it took some digging. There are just too many modules available on SEMS and many are broken.
