### ISSUE TITLE
Compilation errors due to missing headers

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#256]
@ibaned : there are now some compilation errors about missing headers after your commit https://github.com/gahansen/Albany/compare/2c2611b508b1...59c5563efc10 .  Can you please have a look and fix it?  It looks like the adapt code you removed is still called all over the place in Albany when Epetra is on.

**Comment by ikalash** [comment]
Here is how the errors look like: https://my.cdash.org/viewBuildError.php?buildid=1357261 .

**Comment by ibaned** [comment]
Yea I'm just reverting this. Removing code from Albany takes more time than I have available.

**Comment by ikalash** [comment]
Thanks, @ibaned .  Unfortunately now there are link errors: 

```
[ 97%] Linking CXX executable AlbanyDakotaT
../libalbanyLib.so: undefined reference to `Albany::TpetraBuild'
collect2: error: ld returned 1 exit status
src/LCM/CMakeFiles/TopologyBase.dir/build.make:287: recipe for target 'src/LCM/TopologyBase' failed
make[2]: *** [src/LCM/TopologyBase] Error 1
CMakeFiles/Makefile2:3223: recipe for target 'src/LCM/CMakeFiles/TopologyBase.dir/all' failed
make[1]: *** [src/LCM/CMakeFiles/TopologyBase.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../libalbanyLib.so: undefined reference to `Albany::TpetraBuild'
collect2: error: ld returned 1 exit status
```

I think you may need to revert your other commit yesterday as well about the extern bool TpetraBuild.

**Comment by ibaned** [comment]
da8eb9601
