### ISSUE TITLE
CISM-Albany and MPAS-Albany build error due to Albany::BuildType

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#263]
Looks like the checkins yesterday having to do with setting the Albany::BuildType broke CISM-Albany and MPAS-Albany builds on Cori/Edison: 

https://my.cdash.org/viewBuildError.php?buildid=1364286

Tagging @mperego , who is probably interested in the MPAS ones. 

@tjfulle : can you please have a look at this?  CISM and MPAS are codes we've interfaces Albany to (I've explained to you offline how CISM-Albany works).

**Comment by ikalash** [comment]
Looks like this is happening in my no-Epetra and OpenMP builds as well: 

http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany&subproject=IKTAlbanyNoEpetra
http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany&subproject=IKTAlbanyFunctorOpenMP

whereas everything is good with my full build.  My guess is the new variable was only tested in a full build?

**Comment by tjfulle** [comment]
@ikalash I just got the github notification about this today.  Is it still a problem?

**Comment by ikalash** [comment]
Nope, I fixed it.

**Comment by tjfulle** [comment]
@ikalash said:

> My guess is the new variable was only tested in a full build?

I'm afraid I don't know the difference between a full build and not-full build.  Is there a standard build[s] that should be tested before pushing and/or accepting PR (apologies if this is described in some manual somewhere)?

**Comment by ikalash** [comment]
@tjfulle : In this case by "full" I meant one that has Epetra; but a branch that has Epetra may not be "full" in the sense that it may enable only certain physics.  So that phrase was really confusing/misleading, sorry.  

There is no manual sadly...  (we wish!).  I do not think any one person is expected to test all possible Albany configurations before pushing, as there are a lot (and some like the CUDA one are highly specialized and can only run on certain platforms) and some require other codes (e.g., CISM-Albany).  In general we use the tests to find issues - sometimes people will push something that will break in one build, and not another, which becomes apparent in the tests.  So I think the thumb is if you have a big commit / PR that you think might break something, to keep an eye on the dashboard / issues the next day to see if that indeed happened.  

BTW, my nightly test jobs send an email to a group of people summarizing what happened.  If you'd like, I can add you to the list of recipients.
