### ISSUE TITLE
Failing Tempus tests

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#272]
It looks like all the Albany Tempus tests began failing last night due to a missing "Zero Initial Guess" parameter: 

http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlyfailed&buildid=68338

For detailed output from one of the tests, please see:

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3545697&build=68338

@sconde: I saw there were some Tempus checkins relating to this over the weekend but I just got back from foreign travel so I am not up to speed on things.  Has the PL syntax for tempus changed again so I need to add this new "Zero Initial Guess" parameter?

**Comment by sconde** [comment]
@ikalash the same problem with Drekar. I have a PR in Trilinos that should fix this
