### ISSUE TITLE
Tpetra::Map destructor warning printed for Albany tests

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#275]
I noticed that starting this morning, all (I believe) Albany tests have this warning printed: 

```
WARNING: Tpetra::Map destructor (~Map()) is being called after Tpetra::finalize() has been called.  This is user error!  This may happen if you create a Tpetra::Map (or RCP or shared_ptr of a Tpetra::Map) at the same scope in main() as Tpetra::finalize().  Don't do that.  Please refer to GitHib Issue #2372.
```

It looks like the warning was added to Tpetra yesterday (see https://github.com/trilinos/Trilinos/issues/2372 ).  We should try to understand what we're doing wrong with the Tpetra::Map destructor.  @tjfulle, would you be willing to look at this, as someone well-acquainted with Tpetra and also working on Albany maintenance?

**Comment by tjfulle** [comment]
@ikalash, I'll look in to this.

**Comment by ikalash** [comment]
Thanks so much, @tjfulle !

**Comment by ikalash** [comment]
It looks like all the print statements about the deallocation of Tpetra::Map went away in last night's build.  @tjfulle , did you do something to fix this?  I don't recall seeing any Albany commits about it, but it's possible I missed them.

**Comment by tjfulle** [comment]
@ikalash, no I didn't fix anything, but I meant to update this issue.  @mhoemmen pushed an update to Tpetra (https://github.com/trilinos/Trilinos/commit/546f3e4786f203d5950d797df4f1832aa2a00135)  that fixed the warnings

**Comment by ikalash** [comment]
I see.  But is there still an underlying issue, just the output has been suppressed?

**Comment by mhoemmen** [comment]
@ikalash If you don't see the warning message any more, then you are using Map correctly :-) .

**Comment by mhoemmen** [comment]
Map's destructor checks the following prerequisites:
  - Is Kokkos still initialized?
  - If the Map's Comm is an MpiComm, is MPI still active (initialized and not finalized)?

If any prerequisite is NOT satisfied, Map's destructor prints a warning message to Process 0 in the Map's communicator (assuming that MPI is still active, else Map tries its best).

**Comment by ikalash** [comment]
Great!  I love it when problems go away on their own :).
