### ISSUE TITLE
Failing nightly Albany tests

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#280]
A number of nightly test builds started failing this week.  This is due to a change in MOR involving making RBGen a required package.  To fix the issue, the following line:
    
    -D Anasazi_ENABLE_RBGen:BOOL=ON

needs to be added to the Trilinos cmake script (or MOR needs to be turned off in Albany).  I added this line to one of the Trilinos dashboard configure scripts, but I do not own this script, so I am not sure if I added it to the right place / got all the relevant builds.  I will check the CDash tomorrow.  Owners of CDash tests: if your builds are failing, please fix them by adding this line or turning off MOR.

**Comment by ikalash** [comment]
Who owns the following nightly builds 

AlbanyIntel
Albany64BitClang
Albany64Bit
Albany64BitDbg

(http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany&date=2018-03-28 ).  @ibaned , @gahansen : do you guys own them, or know who does?  Can you please enable Anasazi_ENABLE_RBGen in the Trilinos configure scripts that these builds use, per resolving this issue?

**Comment by ibaned** [comment]
@gahansen owns these and has been out all this week. He should be back next week.

**Comment by gahansen** [comment]
Thanks Irina!

Sorry for my delay in responding to this issue. I refreshed the dashboard scripts on the test machine. Your commit 2cab67fa added this new option to the script in question so the build should pick that up and run correctly this evening.

I'll verify that the dashboard is clean tomorrow and close this issue if it is. Thanks much for your help with this!

**Comment by ikalash** [comment]
No worries, Glen.  Sounds good, thanks.

**Comment by gahansen** [comment]
The dashboard build did not succeed due to my still specifying yaml as a dependency (forgot to address that yesterday). I fixed that this AM - if the dashboard cleans up tomorrow I will close this issue.

**Comment by ikalash** [comment]
I believe this is good now.
