### ISSUE TITLE
Rebaseline failing LCM tests

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#282]
A bunch of LCM tests began to fail this morning, due to this commit https://github.com/gahansen/Albany/commit/67b534a55adab1afec5f5a19f3e870b7e3ee15b4 (as expected), and need to be rebaselined.  Here is a summary of the failing tests: http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlyfailed&buildid=69089 .

**Comment by ikalash** [comment]
@guybergel : it looks like a subset of these tests is still failing, e.g., 

http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlyfailed&buildid=69153

Can you please have a look?

**Comment by ikalash** [comment]
Looks like most of the tests are fixed now except MechanicsTensileTet10_STK:

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3601626&build=69561

It looks like there is a failing comparison b/c the mean value changed slightly.  Should this test be rebaselined too, or is there another underlying issue?

**Comment by gahansen** [comment]
There are quite a few tests failing on the RPI Clang build:

https://my.cdash.org/viewTest.php?onlyfailed&buildid=1404063

I didn't triage this, but timing of the failure and the tests involved might indicate some relationship with this issue #282. There appears to be a significant error with some of these, I see a serious looking error being reported:

*** glibc detected *** /lore/ghansen/nightly/build/Albany64BitClang/src/AlbanyT: double free or corruption (fasttop): 0x000000000d1b2820 ***

Please see:

https://my.cdash.org/testDetails.php?test=38925524&build=1404063

for more context.

**Comment by lxmota** [comment]
Probably just rebaselined.

I’ll take a look at it later.



On Apr 16, 2018, at 08:08, Irina K. Tezaur <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like most of the tests are fixed now except MechanicsTensileTet10_STK:

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3601626&build=69561

It looks like there is a failing comparison b/c the mean value changed slightly. Should this test be rebaselined too, or is there another underlying issue?

**Comment by lxmota** [comment]
I see a lot of failures with clang as well, but I believe these are unrelated to this issue. In my own clang platform, the tests complain that they cannot find the corresponding exodus input files. It appears that mpirun is not being called correctly.

**Comment by gahansen** [comment]
On the Albany64BitClang test at RPI - we had 13 tests fail Apr 11, a build failure on the 12th, and 26 fail the 13th. Looking at the CrystalPlasticity_OrientationOnMesh_np4 test there, it appears to have diff-ed on the 11th:

https://my.cdash.org/testDetails.php?test=38829466&build=1401536

but on the 13th it started die-ing with the above error ("double free"):

https://my.cdash.org/testDetails.php?test=38872937&build=1402673

From these logs, I think the code gets past the exodus input - I think the log on the 11th shows a successful run and just a diff coming from exodiff. These Clang runs have been pretty stable as I look back on the dashboard history - this Clang test was all green from March 22 to Apr 2.

I don't think the double free issue is related to mpi - the executable appears to have run to completion on the 11th and then something happened to result in this run-time error on the 13th on this particular test. Actually, most of the test failures appear to print a message like:

*** glibc detected *** /lore/ghansen/nightly/build/Albany64BitClang/src/AlbanyT: double free or corruption (fasttop): 0x000000000c7e46a0 ***

I'll try and bisect down to the specific commit where the behavior changed when I get a chance.

**Comment by lxmota** [comment]
I believe I have fixed all these.

There was an outlier left, MechanicsTensileCT, which I re-baselined.

Also, all the tests in clang everywhere were failing because of this: https://github.com/gahansen/Albany/commit/0c1b1f463ba0c9dc76728bbfc52f689a7e24a27a
