### ISSUE TITLE
Albany builds at RPI failing "PCU_Get_Comm()"

### ISSUE THREAD

**Issue by gahansen** [gahansen/Albany#283]
An Albany build at RPI started failing yesterday - here is the detailed compile error log:

https://my.cdash.org/viewBuildError.php?buildid=1395100

The first message of consequence appears to be:

repos/Trilinos/SCOREC/stk/apfExodusOutput.cc:55:56: error: 'PCU_Get_Comm' was not declared in this scope

CC: @ibaned @cwsmith

**Comment by cwsmith** [comment]
The build was fixed https://github.com/SCOREC/core/issues/148#issuecomment-379045107 and the board is clean:
![clean](https://user-images.githubusercontent.com/1024438/38636369-f9604c88-3d95-11e8-9f65-7ff5c16abd42.png)
