### ISSUE TITLE
Force correct setting of internal variables for inelastic LCM problems + Tempus variable time-stepping 

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#286]
There is currently a possible issue when using variable time-stepping from Tempus for inelastic LCM problems: if the time-step is cut by Tempus due to some internal Tempus criterion for cutting the time-step, in particular, not due to a failed NOX solve, the internal states Albany will use will not be correct.  This is relevant for inelastic material models.

**Comment by lxmota** [comment]
Fixed by Greg Phlipot
