### ISSUE TITLE
LCM build fail: std::sqrt is not constexpr

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#288]
```
LCM/models/ACEice_Def.hpp:214:20: error: constexpr variable 'SQ23' must be initialized by a constant expression
```
Unfortunately, `std::sqrt` is still not a `constexpr` function in C++, so `SQ23` must either be changed to just `const` or initialized with some precomputed constant... I consider this a bug in the C++ standard but for now we have to work around it.

**Comment by lxmota** [comment]
Ah, I fixed this before I saw the issue.

The relevant commit: https://github.com/gahansen/Albany/commit/fe887a00adb38c9f39eb2a887458f28aec78d1dc
