### ISSUE TITLE
properly handle meshes getting smaller

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#29]
This is actually a Trilinos issue as the relevant code is in Piro at this point, but its really only used by Albany. There are bits of code that assume adaptivity only makes the mesh bigger, and cause serious failures when the mesh gets smaller.

I'll try to code a patch while I still remember where that code is, this issue can track our progress.

@mjuha @bgranzow @gahansen

**Comment by ibaned** [comment]
I just pushed trilinos/Trilinos@ff0a166, which may help with this situation.

@mjuha, could you try these changes when possible on your problematic case with error bound 0.1 ? unfortunately, because of some Intrepid2 changes, you must be careful to use Albany at version fe7f2ea if you are going to compile with the Trilinos develop branch. If the fix is not urgent, we could wait a few days for Trilinos develop to be merged into master.

**Comment by ibaned** [comment]
Well, although I think my changes were right, they seem to be insuffient.

@mjuha, could you follow these steps ?

1. confirm that with error bound 0.1 your mesh does get smaller
2. create a small serial test case that demonstrates the same issues
    (adaptation makes the mesh smaller, incorrect solution).
3. run that serial test case under Valgrind

**Comment by mjuha** [comment]
@ibaned , I just check it and I know why your change, although correct, it is insufficient. There are two adaptation process that are performed during the simulation:
1) Adapt mesh and do not add new layer. In that case the mesh get smaller. (i.e, from 511,976 nodes to 443,079 nodes). 
2) Adapt mesh and add layer. In this case the mesh get bigger. (i.e., from 443,079 nodes to 806,297 nodes)

**Comment by ibaned** [comment]
Can you confirm whether you see the wrong solution in one or both of those cases ?

**Comment by mjuha** [comment]
Dan, the wrong solution is happening only for the second case.

**Comment by ibaned** [comment]
Okay, then we are following entirely the wrong trail; this has to do with the solution values in the new layer and not with the smaller-mesh logic. I'm going to close this issue because it deals with the mesh getting smaller, and we've done what we can in that direction for now.
