### ISSUE TITLE
Nightly test of Albany with up-to-date SEMS modules

### ISSUE THREAD

**Issue by bartgol** [gahansen/Albany#290]
I have the impression that Albany is *not* being tested against the current sems modules. I am getting errors when running on my machine (where I use sems), due to some issue with netcdf (I have a ticket open with the sems team, since I believe there's something wrong with the netcdf installation).

I think we are testing *old* sems modules (i.e., before the big update late last year). These modules are still available (meaning that the installation folder is there), but do not show up as modules (so one has to manually adjust his/her own paths to load them). I think the sems team intention is to shift everyone to the new installations. E.g., netcdf4.4.1 is the only module available, though an installation of netcdf 4.3.2 is still available.

Am I wrong? If not, should we set up a nightly test with up-to-date sems modules?

**Comment by ikalash** [comment]
My tests don’t use the sems modules.  This is because I run fedora os and the  sems modules don’t work with this flavor of Linux.  Same goes gor @lxmota ‘s tests.

**Comment by gahansen** [comment]
I could pretty easily add a new test on CEE that is similar to the Albany64Bit dashboard run that uses the CEE modules instead of custom TPLs. Actually, could probably just change that one to use SEMS - I don't think that this test is testing anything else very unique. Anyone have additional thoughts or issues?

@bartgol - could you please pass me the module commands for these if you know what they are on CEE?

**Comment by lxmota** [comment]
The LCM modules system that we use on Fedora and Ubuntu also works for SEMS. I run nightly tests on my own CEE LAN workstation with both GCC and the Intel compilers. See the entries `*_SEMS_*` in the nigtlhy Albany dashboard.

I'm not sure that we are loading old or new SEMS modules. On any SEMS platform, using the LCM modules to compile with GCC in release mode will load the following modules:

```
Currently Loaded Modulefiles:
  1) lcm-common                      12) sems-openmpi/1.10.1
  2) sems-env                        13) sems-boost/1.63.0/base
  3) sems-python/2.7.9               14) sems-zlib/1.2.8/base
  4) sems-cmake/3.5.2                15) sems-hdf5/1.8.12/parallel
  5) sems-git/2.10.1                 16) sems-netcdf/4.4.1/exo_parallel
  6) lcm-sems                        17) sems-parmetis/4.0.3/parallel
  7) lcm-initialize                  18) sems-superlu/4.3/base
  8) lcm-serial                      19) lcm-tpls
  9) sems-gcc/6.1.0                  20) lcm-finalize
 10) lcm-gcc                         21) release
 11) lcm-release

```
Some of these modules were written by us (see `Albany/docs/LCM/modulefiles`) and some are SEMS modules. @ibaned helped us do some serious heavy lifting in generalizing these modules to work on multiple platforms. The supported platforms so far are: Fedora, Ubuntu, Scientific Linux, SEMS, and Sandia HPC clusters (chama, skybridge, I have not tried serrano).

We only test LCM, though.

**Comment by bartgol** [comment]
@lxmota those modules seem up to date. I am curious whether you see any failure in the tests that use serial input mesh, like Ioss2D_SerialInput. Debugging my failures I got to the conclusion that there is a problem with sems-netcdf/4.4.1/exo_parallel, but you may prove me wrong.

Also, is this the sems installation on the SRN or the SON? I think they may be different, since intel compilers don't work on the SRN but do work on the SON (though that may just be an issue with ip protocols, not related to the actual installation).

**Comment by lxmota** [comment]
We test on the SRN.

No, we don't see any issues with serial mesh:

http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlypassed&buildid=69967

Also, for us, the Intel compiler works:

http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany&subproject=albany_SEMS_ceerws1006_serial-intel-release

**Comment by bartgol** [comment]
Ok. thanks. Then I can close this, and investigate somewhere else.
