### ISSUE TITLE
Implementation of Neumann boundary condition of Pressure

### ISSUE THREAD

**Issue by hillyuan** [gahansen/Albany#293]
I tested the functionality of Neumann boundary condition of Pressure. The results is bad and I think its implementation is wrong. Attached are the details
[Implementation of Neumann boundary condition of PRESS.pdf](https://github.com/gahansen/Albany/files/2007258/Implementation.of.Neumann.boundary.condition.of.PRESS.pdf)

**Comment by ikalash** [comment]
@ibaned : I see you assigned this issue to me, but I've actually never worked with or used the pressure Neumann BC.  I looked at the PDF attached and I'm not sure why there are these scalings by the area.  I believe the original author of this BC was @gahansen .  Glen, do you have any thoughts on what could be going wrong here?

**Comment by ibaned** [comment]
@ikalash yea, I was more just throwing in a list of people who might be able to point us in the right direction, not necessarily expecting any particular person to apply fixes. It actually worked out because you knew @gahansen was the person to talk to.

**Comment by ikalash** [comment]
No worries.  I believe @jwfoulk and @lxmota may have used this BC for LCM, and might be able to comment on whether it works correctly.

**Comment by gahansen** [comment]
I suspect that I am the person who inflicted the current pressure boundary condition upon us. Unfortunately, the logic of the current implementation (if there is any) escapes me today. I'd be glad to work with @hillyuan and fix the implementation and add his problem as a test. We might just do that and then work with others (@jwfoulk and @lxmota ?) on any resulting failures of other tests if no one has reservations.

**Comment by hillyuan** [comment]
I modified relevent code and the results seems good. Please check my pull request.

**Comment by hillyuan** [comment]
Even if this problem be solved, there is still a problem related with computation performance left. 

In the above calculation, we need a non-normalized normal vectors of the area where external pressure acts upon. It is complished by Intrepid2 function getPhysicalSideNormals. The implementation of Albany, however, loooks like
------------------
calculate non-normalized normal vectors( using function getPhysicalSideNormals) --> normalize it ( using function scalarMultiplyDataData) --> Multiply the length of non-normalized normal vectors ( using function multiplyMeasure)
--------------------
I think the result is just the vector that getPhysicalSideNormals obtains and thus above calculation steps maybe useless.

**Comment by gahansen** [comment]
@hillyuan - I merged in your changes and updated the tests to run with the default 4 ranks in the nightly tests, but I cannot get them to pass. Could you please take a quick look?

**Comment by hillyuan** [comment]
Sorry! It's my fault. I havn't check this one. It is fixed in my last pull request.

**Comment by gahansen** [comment]
@hillyuan - Thanks very much! I merged your changes and the tests are clean for me also. I wanted to add some documentation to these tests that record the equation that you sent, so I made a README.md file and placed it in the directory that contains the tests. I am doing something incorrect in the point load at the end of the beam in the README. Could you please take a look and advise on what might be wrong in my description of the "input_comp.yaml" problem? Also, I note that the result obtained with the tet4 elements is different than the tet10 - indeed you use a value of 

Test Values: [-0.1454]

Do you know why this is the case?

**Comment by hillyuan** [comment]
tet4 is much stiffer than tet10, in another work, we should try to avoid using tet4 in structural deformation analysis. The test cases here is to confirm the implementation of Pressure on different element. It can be also considered as a test about accuracy of different elements. (I've compred the results with Abaqus)

In fact, I've also tested Hex<8> element. The reference result of Albany is -0.2609, much worse than Abaqus C3D8I's -0.3691.

**Comment by hillyuan** [comment]
It's great for you to add Readme for the test. I notice it include the formula of force at tip. But no such kind of tests currently there. Are you going to add some afterwards?

**Comment by gahansen** [comment]
I merged the above pull request. I will work in improving the documentation some tomorrow as the tests failed today because of a Trilinos issue.

I might take a look at the Hex<8> element result some more, it is a little troubling that the results are that bad on that element.

I am looking into your comments above, on simplifying the implementation to only use getPhysicalSideNormals. I will try this and give an update tomorrow.
