### ISSUE TITLE
Failing FO_GIS_GisWedgeAdjointSensitivity nightly test due to changed in extruded mesh specifications

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#302]
Last week, the FO_GIS_GisWedgeAdjointSensitivity test started failing due to the "Field Origin" = "Output" option not being valid anymore: 

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3704649&build=71551 

@bartgol : can you please have a look at this and change it to the right option?

**Comment by bartgol** [comment]
Hi Irina,

I fixed this input file, but only in a branch that I was hoping to merge soon (containing some bug fix in GenericSTKMeshStruct as well as a bunch of stuff in FELIX Hydrology).

If it's ok with you, I will not fix this bug in master, and wait till I merge the branch (should be a matter of a day or two).

**Comment by ikalash** [comment]
@bartgol that should be fine.  I'll try to keep an eye on the nightlies and close the issue when it gets resolves (feel free to close it yourself if you see the test starting to pass in the nightlies).

**Comment by bartgol** [comment]
Merged the branch. Let's see how the dashboard is tomorrow.

**Comment by bartgol** [comment]
I don't see this error anymore. Closing.
