### ISSUE TITLE
New behavior of installation

### ISSUE THREAD

**Issue by bartgol** [gahansen/Albany#303]
Commit d696274 changed the behavior regarding installation.

I think the new version always sets INSTALL_ALBANY to TRUE (for recent cmake releases), This causes cmake to try to copy stuff to an install directory at config time (see src/CMakeLists.txt, line 1075), assuming that CMAKE_INSTALL_PREFIX is valid and writable. I never set CMAKE_INSTALL_PREFIX, cause I don't need/want to install Albany, so it defaulted to /usr/local. But even if it was a writable valid path, I don't want albany stuff to silently be copied somewhere I don't want.

I'm not sure if the correct solution is to bring back ENABLE_INSTALL or to remove that line (and probably other). But as is, I think the current behavior is not ok.

Tagging @gahansen , since he did the commit, so he may have more insight.

**Comment by bartgol** [comment]
Note: an easy fix (I think) is to replace the lines 81-97 of the main CMakeLists.txt with

```
SET (INSTALL_ALBANY FALSE CACHE BOOL "Whether Albany should be installed")
IF (INSTALL_ALBANY)
  IF (${CMAKE_VERSION} VERSION_GREATER 2.8.8 OR ${CMAKE_VERSION} VERSION_EQUAL 2.8.8)
    MESSAGE("")
    MESSAGE("Installation files for Albany will be created")
    MESSAGE("-- install location = ${CMAKE_INSTALL_PREFIX}")
    MESSAGE("")
    set(BINARY_INSTALL_DIR bin)
    set(INCLUDE_INSTALL_DIR include)
    set(LIB_INSTALL_DIR lib)
    include(CMakePackageConfigHelpers)
  ELSE()
    MESSAGE("")
    MESSAGE("Installation has been requested, but cannot continue")
    MESSAGE("-- Please upgrade CMAKE to version >= 2.8.8")
    MESSAGE("")
  ENDIF()
ENDIF()
```

**Comment by gahansen** [comment]
Very interesting. I was not aware that files/directories would be created during the config process, only during "make install" . Just to confirm, did you see this when you configured after the offending commit? I'll revert and rethink this if that happened.

**Comment by bartgol** [comment]
Yes, I saw this right after the offending commit.

**Comment by bartgol** [comment]
Whoops! I forced pushed an amend to the last commit I made (it was very shortly after the commit, so I thought I took the change), and I accidentally included the fix to the CMakeLists... Do I get a yellow card?

Anyhow, if you take a look at it, let me know if there's something that does not convince you.

**Comment by gahansen** [comment]
Sorry about this problem. I was working to eliminate that option to streamline the SPACK build

https://github.com/spack/spack/pull/8332#discussion_r192413705

but I did not realize that we depended on it for other reasons. Are you OK with where the code stands now? I am good with where things stand. We can reopen this issue if any problems are outstanding.

**Comment by bartgol** [comment]
Sure, it's fine with me.

**Comment by ikalash** [comment]
I was on foreign travel until today so I have been out of the loop.  It looks like my nightlies that do a make install are failing, e.g., http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=72017 .  What is the resolution?  Does the install happen automatically now?

**Comment by ikalash** [comment]
I figured it out, please disregard.
