### ISSUE TITLE
[Question] PDEs with grad (d/dt) terms in Albany

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#304]
Has anyone implemented a set of PDEs in Albany in which the weak form contains grad (du/dt) term?  It seems this would be straight forward to get these terms by simply calling constructDOFVecGradInterpolationEvaluator on the dot variables, e.g.: 

fm0.template registerEvaluator<EvalT>
(evalUtils.constructDOFVecGradInterpolationEvaluator(dof_names_dot[0], offset));

then registering the new term (e.g., UGrad_dot) with the right layout in the relevant problem evaluator.

I wanted to make sure I'm not missing any possible caveats this approach may have.

**Comment by bartgol** [comment]
Yes, I don't see anything wrong with doing that. It follows from the definition of the FE function, I think.

**Comment by ikalash** [comment]
@bartgol : cool, thanks.  I'll give it a try.
