### ISSUE TITLE
Lack of Albany_config.h

### ISSUE THREAD

**Issue by bartgol** [gahansen/Albany#311]
Is there a reason why we shouldn't have something like an Albany_config.h file? I find it useful to have a file in the build directory to check whether a compile definition was enabled or not. Sure, I can compile with VERBOSE=ON, and see all the -D stuff passed to the compiler, but a header file is imho a nicer solution, which allows me to see what's enabled and also what was _enablable_ but not enabled...

Any thought about this?

**Comment by jewatkins** [comment]
That sounds useful to me.

**Comment by bartgol** [comment]
I'll make a PR for this then.

**Comment by bartgol** [comment]
PR #317 took care of this.
