### ISSUE TITLE
Albany data types reorganization/cleanup

### ISSUE THREAD

**Issue by bartgol** [gahansen/Albany#312]
I'd like to reorganize the albany data types. In particular I would like to

1) split Albany_DataTypes.hpp into multiple files, like Albany_ScalarOrdinalTypes.hpp (ST,LO,GO,Tpetra_GO,Tpetra_LO), Albany_TpetraTypes.hpp (all tpetra typedefs), Albany_SacadoTypes.hpp (all sacado types). I would include all of them in Albany_DataTypes.hpp for bwd compatibility, but will like to use only what I need in some files (e.g., discretization probably does not need to know about fad types).

2) Put _all_ typedefs inside Albany namespace. This makes life safe, in case some upstream package decides to define ST or RealType one day (even if defined to the same thing, it would still issue a warning). In PHAL_AlbanyTraits.hpp, place a `using namespace Albany` to inject all names, so that all evaluators will still compile (they expect types to be available, and they do not live in Albany namespace).

3) Remove some include/typedefs (like row-matrix transposer or thyra wrappers) that are used in a limited portion of the code, and include them only where needed. The row-matrix transposer, for instance, is only used in ATO/ATO(T)_Solver.cpp.

I think this will help to keep the code cleaner (and compilation time under control probably) when embarking on the thyra-refactor ship...

Thoughts? Objections?

**Comment by jewatkins** [comment]
This sounds good to me.

**Comment by bartgol** [comment]
Ok, I'll make a PR.

**Comment by bartgol** [comment]
Ok, I'm working on this, but I'm faced with a dilemma.

First, I think that having so many types injected in the global namespace is not a good practice for a large library. Especially a library that does support install (and therefore be used from outside as a library).

So, I split the Albany_DataTypes.hpp file into a few Albany_XYZ.hpp headers (ScalarOrdinalTypes, ThyraTypes, TpetraTypes, SacadoTypes,..), and the all `Albany_DataTypes.hpp` includes all of them for backward compatibility (though I think one should only include the types that are needed; for instance, no tpetra types in ~90 of PHAL evaluators, and no Sacado types in the discretization). I put every type in there inside the Albany namespace. That causes all uses of these types to be wrong from other namespaces (aka, PHAL, AAdapt, STK, FELIX, LCM, ATO,...). One has therefore to either inject all names in the namespace (but where to do that for, say, FELIX, since there is no FELIX 'main' header file?), inject the names as they are used (if few types, it is doable), or use the fully qualified name, like `Albany::RealType`.

Honestly, I think ALL namespaces should be nested inside the Albany namespace, since they make little to no sense as standalone namespaces (they have at least a few types/functions that are taken from the Albany namespace) or standalone packages (I don't think you can run any package without PHAL, which makes no sense without Albany).

So my first choice would be to nest ALL namespaces inside Albany, which would fix the names issue. However, I'm not sure if this is desirable, especially considering it would touch roughly ALL files in Albany.

The quick and dirty solution would be to add the line `using namespace Albany;` inside `Albany_DataTypes.hpp`, which would inject back all names in the global namespace, but this kind of defies the idea of having them inside the Albany namespace to start with.

So I guess the question is: should all Albany types be left in the global namespace (I worry especially about 'common' type names, such as `ST`. or `RealType`, or `LO` and `GO`), or should Albany types lie inside a safe Albany namespace? If the latter is chosen, how to deal with all the namespaces not nested within Albany?

**Comment by jewatkins** [comment]
If we are going to continue supporting Albany install then I would agree that creating an Albany namespace makes the most amount of sense. Also if a namespace is using Albany data types, I don't see an issue with wrapping it with an Albany namespace (I would think that's the cleanest option). I suppose the only concern would be downstream apps which are currently using Albany install but I wouldn't be familiar with any of those. Maybe someone else can provide some insight.

**Comment by ikalash** [comment]
CISM-Albany uses the install of Albany, so we want to make sure that interface works correctly if there are changes to how the install works.  Other Albany-interfaced codes that might use the install are: MPAS-Albany @mperego , PFlotran @tjfulle , Peridigm @djlittl .  If they do, the code owners (tagged above) might want to chime in.

**Comment by bartgol** [comment]
This was partially addressed by PR #323. Though it did not wrap all data types in the Albany namespace, at least they got divided depending on the conceptual area. I think the discussion about the namespace is deeper than just data types organization, so I'm going to close this.
