### ISSUE TITLE
Compilation errors in nightly tests due to changes yesterday

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#318]
My nightly builds failed due to some of the changes yesterday.  One of the errors is in the CISM-Albany interface: 

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=73304 

The unrecognized class FelixToGlimmer is in a file that exists in the CISM code (interfaced to Albany) which is required to compile Albany with the CISM interface.  Is there an easy fix?

**Comment by bartgol** [comment]
Given the timing, it _may_ be related to the Albany_config_h branch I merged yesterday. However, the error 'could not load cache' seems to be unrelated.

Still, I will double check the cism interface; perhaps I forgot to include Albany_config.h somewhere.

**Comment by bartgol** [comment]
3 seconds were enough to see it's a mistake on my side. Quick hotfix coming up in master. Closing now, but reopen if tomorrow you see the commit didn't fix it.

Thanks!

**Comment by ikalash** [comment]
Thanks, @bartgol!  This fixed the problem.

**Comment by ikalash** [comment]
Spoke a little too soon...  did the capability to do an install of Albany go away?  This is required for CISM to build against Albany.  I get the following error when I try to do make install after make: 
```````````````````````
Install the project...
-- Install configuration: ""
CMake Error at src/cmake_install.cmake:36 (file):
  file INSTALL cannot find
  "/home/ikalash/nightlyCDash/repos/Albany/src/Albany_config.h".
Call Stack (most recent call first):
  cmake_install.cmake:37 (include)


Makefile:73: recipe for target 'install' failed
make: *** [install] Error 1
```````````````````````````

**Comment by bartgol** [comment]
Ah, my bad. Another hotfix coming soon.

**Comment by ikalash** [comment]
Thanks @bartgol , seems all is good now.
