### ISSUE TITLE
Hydrostatic test case failure on GPU

### ISSUE THREAD

**Issue by jewatkins** [gahansen/Albany#319]
There's an illegal memory access error in the hydrostatic test cases for the cuda build on ride. @bartgol Do you think it might have something to do with ADValue()? I'll look into it to see if I can get more info.

**Comment by bartgol** [comment]
It may be related to yesterday's PR. Where does the error happen?

**Comment by bartgol** [comment]
I saw the cdash error. Not quite clear what generates it, and where it is. My guess is another missing include of Albany_config.h _before_ some CUDA macro in Albany is used. I'll try to build on white and see what happens.

**Comment by jewatkins** [comment]
It seems to run okay if I remove ADValue() from [Hydrostatic_SurfaceGeopotential](https://github.com/gahansen/Albany/blob/master/src/Aeras/evaluators/Aeras_Hydrostatic_SurfaceGeopotential_Def.hpp). Not sure why.

**Comment by jewatkins** [comment]
I think ADValue just needs to be compiled for device. Seems to work if it's a device function.

**Comment by bartgol** [comment]
Good catch! I'm surprised no other test fails thought. `ADValue` is used in quite a few other places.

**Comment by bartgol** [comment]
Ah, but no other device places probably...

**Comment by jewatkins** [comment]
Yeah the other places probably aren't tested on device.
