### ISSUE TITLE
CellSpecs structure

### ISSUE THREAD

**Issue by bartgol** [gahansen/Albany#329]
Is this really used anywhere? I grepped and it is only used for the return type of getMeshDynamicData...which is not used anywhere. Besides, the class is odd, storing some private variables that are never used, like an instance of Albany::Layouts (which forces to include Albany_Layouts.hpp, which doesn't contribute to make the very complicate chain of includes in Albany smalller).

**Comment by agsalin** [comment]
Sorry, this isn't familiar. The "Dynamic" part sounds more like Glen. 

My philosophy has been: If you can rip it out and the tests pass, then rip it out.

**Comment by ibaned** [comment]
@gahansen ?
I agree with @agsalin , unless @gahansen says otherwise I'd just remove the thing.

**Comment by bartgol** [comment]
Sweet. Thanks!

**Comment by bartgol** [comment]
In Albany_APFMeshStruct.hpp there's a comment saying that meshDynamicData is `Information that changes when the mesh adapts`. However, the only information from CellSpecs that is public (via getters) is the number of vertices, nodes and quadrature points. I take it this would be useful (somehow) in case of meshes with multiple blocks. However, I believe Albany cannot support multiple meshspecs (though it _appears_ designed to support it).

**Comment by gahansen** [comment]
I'm with @agsalin also, lets remove it and verify that the following nightly tests are OK. If so, we are in good shape I think. I'm probably the one that started on that logic path but I don't recall my thinking now so there is no reason to keep that around in my opinion.

**Comment by bartgol** [comment]
My guess is that you wanted to make some of the MeshSpecsStruct info available in a self-explanatory structure. In case of multiple blocks, one would have had to loop over the CellSpecs to get each block's cell specs, rather than looping through the mesh specs array, then query the cell topology inside. It seems it was more of a 'convenience' structure, so we may be able to get away without it even if some remote code paths use it.
