### ISSUE TITLE
Code path with WRITE_MASS_MATRIX_TO_MM_FILE defined in ModelEvaluatorT

### ISSUE THREAD

**Issue by bartgol** [gahansen/Albany#341]
Has anyone activated this macro recently? I am looking at the code inside it (while refactoring for thyra), and I have the impression that the Mass operator is aliasing W_op_outT, and therefore the jacobian W_op_outT will always be overwritten by the mass matrix.

**Comment by ikalash** [comment]
I’m aware of this issue.  It’s been like that from the beginning making the dumping of the mass hacks (user has to run the computation separately to dump the mass and the jacobian).  It would be great to fix it.  I never got around to it I guess.

**Comment by bartgol** [comment]
Ah, ok, thanks. Well, I guess one way to fix it would be to evaluate the mass matrix _before_ the jacobian. Do you think that's an acceptable solution?

**Comment by ikalash** [comment]
Yes that should work.  Very few people use this option so it wouldn’t affect most computations. I would add also an ifef to dump the stiffness matrix to MM in the same way.  Normally I hack the mass MM dumping code to dump the stiffness if I need it.

**Comment by bartgol** [comment]
I will let you add the stiffness part (not sure what the coeffs should be there). I will swap mass and jacobian so that the jacobian is not lost.

**Comment by ikalash** [comment]
To get the stiffness one would set alpha =0, beta =1, omega = 0 (first 3 arguments to computeGlobalJacobianT).

**Comment by bartgol** [comment]
@ikalash I am trying to abstract away from the Tpetra stuff in as much code as possible. When you save the mass matrix, you also save row and column map. Do you need those? If you do, could it be enough to export range and domain maps? I wanted to write a generic call, where I export range and domain vector spaces, but those are built on the range and domain maps of the underlying matrix, rather than row and column map. For the range, this _should_ be the same, but the column map is _not_ the same as the domain one. Since I'm not sure what you use the column map for, I can't say if switching to the domain would be fine.

**Comment by bartgol** [comment]
@ikalash nevermind: I read your comment saying that the code should be run in serial, in which case row and range are the same, and so are domain and column. Problem solved.

In the next chunk of thyra refactor I am taking care of this, so I'm closing.

**Comment by ikalash** [comment]
Great, thank for working on this @bartgol !
