### ISSUE TITLE
Build errors when compiling with CISM

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#344]
There is a build error when compiling with CISM: 
https://my.cdash.org/viewBuildError.php?buildid=1486565 .  The error mentions an invalid use of incomplete type.  Usually this happens when classes aren’t declared in the right place.  I’m a bit puzzled why renaming things last week (I don’t think anything in the CISM files was renamed) would cause this type of error.  @bartgol any thought?  I’m traveling today so I won’t be able to look at it tomorrow.

**Comment by bartgol** [comment]
I'm puzzled. It seems as the files in `${CISM_INCLUDE_DIR}` are not included (and possibly not even built).

However, I'm also puzzled by cdash. It reports 0 error at config time, but clicking on it reveals a cmake error, which seems quite unusual. So unusal that almost seems like a system error.

**Comment by ikalash** [comment]
The files in cism include dir are not in the albany repo but needed for the compilation.  It looks like there was a compilation failure on my machine too so its not specific to nersc.  I'm on my phone right now so I can't check details.  I'll take a look tomorrow when I return to the office.

**Comment by bartgol** [comment]
Where can I get the cism repo, so I can test on my machine?

**Comment by ikalash** [comment]
You can clone it here: git@github.com:ACME-Climate/cism-piscees.git.  It is the felix_interface branch.  Note that the repo is private.  I’m not sure you have access.  @agsalin can give you access or I can put the code somewhere for you to copy.

**Comment by bartgol** [comment]
I think the former option would be easier, if @agsalin agrees.

**Comment by agsalin** [comment]
I added @bartgol to piscees-developers team.

**Comment by ikalash** [comment]
Now there is a cism build failure.  I'll look at it tomorrow.

**Comment by ikalash** [comment]
Update: I've gotten CISM to compile finally.  Unfortunately all the tests fail, either due to regression comparisons failing or due to seg faults.  I am not sure what changes in the code in the past week led to this...

**Comment by ikalash** [comment]
I will close this issue since the build is fine now, and open a separate one about the CISM Albany test failures.
