### ISSUE TITLE
ACE check broke nightlies

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#352]
```
have_both_ace == true failed at /scratch/lcm/LCM/Albany/src/LCM/problems/MechanicsProblem.cpp +162
```
This is being triggered on a bunch of definitely-not-ACE tests.

**Comment by lxmota** [comment]
Sorry. I’m on it.

On Aug 13, 2018, at 09:28, Dan Ibanez <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #352<https://github.com/gahansen/Albany/issues/352> to @lxmota<https://github.com/lxmota>.

**Comment by ikalash** [comment]
Can this issue be closed?  I think ACE isn't in master anymore.

**Comment by lxmota** [comment]
Yes.

**Comment by bartgol** [comment]
Wait, I still see plenty of stuff in LCM/evaluator/ACE. And it is compiled when I enable LCM. Is that not supposed to be the case?

**Comment by lxmota** [comment]
ACE is just a subset of LCM. I removed the stale evaluators.

**Comment by bartgol** [comment]
Thanks @lxmota I forgot to update my master, that's why I still saw it. :)
