### ISSUE TITLE
Numerous test failures in Albany nightlies as of this morning

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#358]
There are numerous test failures in Albany as of this morning: 

http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlyfailed&buildid=75093

Most of them seem to be failures when running exodiff for LCM problems, but a few seem to have to do with reading in an Exodus file to restart from, e.g. http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3880312&build=75103:
```
p=2: *** Caught standard std::exception of type 'std::runtime_error' :
 ERROR: Variable type counts are inconsistent. See processor 0 output for more details.
p=3: *** Caught standard std::exception of type 'std::runtime_error' :
 ERROR: Variable type counts are inconsistent. See processor 0 output for more details.
p=0: *** Caught standard std::exception of type 'std::runtime_error' :
 ERROR: Number of nodeset variables is not consistent on all processors.
        Database: th1d_tpetra.exo
 	Processor 0 count = 3
 	Processor 1 count = 0
 	Processor 2 count = 0
 ```
It looks like there were no non-trivial checkins to Albany master this week, so I think the failures are due to changes in Trilinos.  Anyone want to investigate this?

**Comment by ibaned** [comment]
One possible culprit could be trilinos/Trilinos#2930. If someone has an Albany build handy they could try reverting that merge commit in Trilinos and recompiling.

**Comment by bartgol** [comment]
That was merged 3 days ago though. Did the nightlies fail yesterday? I'm working from home, so I can't check myself.

**Comment by ikalash** [comment]
The past 2 days Albany did not build due to issues in Trilinos (first STK, then Tpetra).  Last successful Albany build was Monday 8/20 (http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany&date=20180820).  Unfortunately I won't have time to look into this until the weekend/early next week since I'm stuck in meetings most of the day today/tomorrow.

**Comment by bartgol** [comment]
I may have some limited time to check it out tomorrow.

**Comment by ikalash** [comment]
I had a chance to look into this today (so no need to do so, @bartgol ).  Reverting Trilinos commit 1d835e3595226bebef56c28862e4e8425af9431e does fix the failing tests, as conjectured (note that one needs to revert Albany commit ec49134eca1f73cea691c4d24e256fe29332cd56 for the code to compile with the Trilinos revert).  So it was indeed a Trilinos STK-related PR that broke the tests.  I will go ahead and open a Trilinos issue.

**Comment by ikalash** [comment]
Update: the LCM exodiff tests that are still failing require rebaselining or changes to how element variables like Cauchy stresses are handled in their code due to changes in STK - see discussion here: https://github.com/trilinos/Trilinos/issues/3377#issuecomment-421462209 .  We should talk about how to proceed at next week's Albany meeting.

**Comment by ikalash** [comment]
@lxmota : I have a proposed fix that isn't as risky as overwriting all the *gold files but is more time consuming.  I could change only the strings in the *exo.gold file that have changes using ncgen/ncdump.  I just tried it on a test case and it worked.  Are you opposed to doing this?  I can try to do it in the evenings this week (I'm sick of seeing so many failures in the cdash, and it's getting hard to separate / keep track of the exodiff failures from other failures, I am finding).

**Comment by ibaned** [comment]
Won't the issue just resurface as soon as any gold file is regenerated by running Albany?

**Comment by ikalash** [comment]
I'm not sure what you mean.  We can run Albany to regenerate the gold file, I'd just be a little wary of doing that given that the tests have been failing for so long b/c if there are some minor differences in the data in the gold file besides just the names of the fields (from the STK change), we can overlook that.

**Comment by ibaned** [comment]
I think you ran a test using the latest Albany and a version of Trilinos prior to the STK changes right? I would think that if an Albany test passed in that configuration, then the only thing making it fail on CDash is the field names. At least for those tests, the gold files should be safe to regenerate.

**Comment by ikalash** [comment]
I did do that at some point.  Not doing this now.  I think it's a necessary test that with the old Trilinos the test passed.  Then I'd want to take the current output *exo file and exodiff it with the one created with the old Trilinos (to be careful) before rewriting the *gold file to rebless it.  You'd have the same issue of field names conflicting though with the exodiff b/w the current *exo file and the older-Trilinos *exo file.

**Comment by lxmota** [comment]
Go for it.

On Sep 19, 2018, at 10:51, Irina K. Tezaur <notifications@github.com<mailto:notifications@github.com>> wrote:


@lxmota<https://github.com/lxmota> : I have a proposed fix that isn't as risky as overwriting all the *gold files but is more time consuming. I could change only the strings in the *exo.gold file that have changes using ncgen/ncdump. I just tried it on a test case and it worked. Are you opposed to doing this? I can try to do it in the evenings this week (I'm sick of seeing so many failures in the cdash, and it's getting hard to separate / keep track of the exodiff failures from other failures, I am finding).

**Comment by ikalash** [comment]
Ok, thanks @lxmota .

**Comment by ikalash** [comment]
This issue has been resolved.  I opened one minor follow-on issue pertaining to the rebaselining of the SurfaceElementLocking tests (#365 ).
