### ISSUE TITLE
Failing SCOREC/PUMI tests

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#360]
I noticed while looking at the dashboard this morning that a number of SCOREC/PUMI tests have been failing for awhile:
```
Heat3DPUMI_Tpetra_RegressFail 
SCOREC_ElastAdapt_SPR_Tpetra 
SCOREC_ElastAdapt_SPR_Tpetra_postParma 
SCOREC_ElastAdapt_SPR_Tpetra_postZoltan 
SCOREC_ElastAdapt_Necking_SERIAL_Tpetra 
SCOREC_ElastAdapt_Necking_Tpetra 
SCOREC_J2Adapt_Tpetra
SCOREC_MechWithTemp_Unif_Tpetra 
Dynamics_SCOREC_Adapt_Tpetra 
```
The first one (Heat3DPUMI_Tpetra_RegressFail ) started failing on July 16; the rest started failing on July 27.  The tests are failing in the AlbanyIntel, Albany64BitClang and Albany64BitDbg builds in the internal dashboard (http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany&date=20180814).  Some but I believe not all of these builds are debug builds, but someone would have to confirm this.  It looks like a subset of the tests are failing on the external (RPI?) Jenga machine: https://my.cdash.org/viewTest.php?onlyfailed&buildid=1504515 (the Jenga tests haven't posted for awhile for some reason, though, and also it seems the history for the external CDash goes back only to August - not sure if we ran out of space or what happen).

Folks interested in the SCOREC tests might want to get this issue resolved.  Are the tests run elsewhere, e.g., at RPI on a machine other than Jenga?  Do they pass there?

**Comment by ikalash** [comment]
@mperego : speaking of Jenga, it looks like the Peridigm tests are failing there.  I think that's the only place Peridigm is tested.  Did you and @djlittl  want to do something about the failures?

**Comment by ikalash** [comment]
Towards resolving issue #399, I am looking at the SCOREC tests that still fail.  It seems one of the tests, Heat3DPUMI_Tpetra_RegressFail is actually supposed to fail!  This is based on the following logic in CMakeLists.txt:
```
 add_test(NAME ${testName}_Tpetra_RegressFail
     COMMAND ${SerialAlbanyT.exe} inputRegressFail.yaml)
  set_tests_properties(${testName}_Tpetra_RegressFail PROPERTIES WILL_FAIL TRUE)
```
and the fact that back when the tests was reported as passing in July it was failing (http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3793807&build=73455) whereas now it is reported as failing when it is actually passing (http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=4140422&build=79139 ).  Tagging those who might have been responsible for creating the test: @gahansen , @ibaned , @maxrpi .  What should the behavior be for this test?  Was it checked in to try to debug something?  It seems kind of bizarre to have a test designed to fail...

**Comment by ibaned** [comment]
@ikalash here is the history and rationale for that test: at some point in the past couple years, we discovered that the regression test system (that compares some value like average solution to a known value in the input file) didn't do its job, in the sense that if the comparison failed, Albany would still succeed and the CTest test would look like it passed. This CTest test, on purpose, compares its solution to an incorrect value, and the Albany executable itself should fail. Then we use `PROPERTIES WILL_FAIL` to tell CTest to negate the meaning of failure, so that when Albany fails the CTest test will pass. If the CTest test is failing, then it means that Albany's mechanism for failing when the solution value doesn't equal the expected one is broken.

**Comment by ikalash** [comment]
Ah yes, I remember discussing this at the Albany meetings. 

Ok, I have identified which commit broke this test: it was this one 

https://github.com/gahansen/Albany/commit/01b128f64b0ef7571a18d0e18a8908279ff7ba5d

by @mperego back in July.  However, note the issue referenced in the commit message, namely #322.  It involved somewhat of a philosophical discussion of whether the WILL_FAIL option should be allowable.  It's not entirely clear to me from reading the discussion what was the consensus...  is the WILL_FAIL option still allowable?

**Comment by mperego** [comment]
@ikalash I was confused by this test as well in issue #322, but then Dan explained us that the test is supposed to fail (and in that case it is reported as passing). If now it is passing and it is reported as failing, then something got wrong at some point after my fix you mentioned.

**Comment by ikalash** [comment]
@ibaned , yes I know.  Mauro and I have found the error and fixed it last night.  The capability wasn't working correctly for tests with no parameters.  WILL_FAIL works and is tested, and I intend to create more testing of that capability (#403).

**Comment by ikalash** [comment]
Looks like I was able to resolve all these across the builds, with the exception of the Clang build, but that is due to an issue with FPEs in the material models that is broader than SCOREC/PUMI (#406) .
