### ISSUE TITLE
Internal Albany CDash site down

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#361]
It appears the internal Albany CDash site went down today: http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany .  Is anyone able to access this page?  @gahansen , @ibaned : do you know what is going on with CDash?

**Comment by ibaned** [comment]
No clue... but I was able to access another project's results on the same site earlier today.

**Comment by ikalash** [comment]
@ibaned : can you please confirm that you can't access the Cdash Albany cite?  I wanted to make sure it's not just me.

**Comment by ibaned** [comment]
Yea I'm seeing the same problem

**Comment by ikalash** [comment]
Ugh...  @gahansen I think you're the owner of the CDash site / subscription.  Could you please look into what is going on, perhaps with the help of the CSUs in CSRI?

**Comment by ikalash** [comment]
CDash is still down.  It looks like there are issues pushing to it by the nightly tests starting today (not surprisingly since it is down).  They look like this depending on the machine:
```
 Failed to connect to cdash.sandia.gov port 80: No route to host
```
(on my workstation camobap).
```
   Upload file: /ascldap/users/ikalash/LCM/trilinos-build-serial-intel-release/Testing/20180914-0600/Configure.xml to http://cdash.sandia.gov/CDash-2-3-0/submit.php?project=Albany&FileName=skybridge-login5___skybridge-login5___20180914-0600-Nightly___XML___Configure.xml&MD5=3c5df95b5eb84d4d1b2e379eaf082392 Size: 66539
   Submit failed, waiting 10 seconds...
   Retry submission: Attempt 1 of 3
   Submit failed, waiting 10 seconds...
   Retry submission: Attempt 2 of 3
   Submit failed, waiting 10 seconds...
   Retry submission: Attempt 3 of 3
```
(on skybridge).
