### ISSUE TITLE
Albany compilation errors

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#369]
@bartgol it looks like your PR yesterday broke the Albany builds.  Can you please fix it?

**Comment by bartgol** [comment]
Working on it.

**Comment by bartgol** [comment]
I'm running the tests right now

@ikalash heads up: when I run with your piro patch, I get segfaults in a handful of Tempus tests. I reverted the patch, and those tests pass. You may want to double check what's going on before merging #trilinos/Trilinos#3567

The offending tests are:

TransientHeat2D_Tpetra_Tempus_BackwardEuler_NOXSolver
TransientHeat2D_Tpetra_Tempus_RK4
TransientHeat2D_Tpetra_Tempus_NoPiro_RK4
CahnHillElast2D_Tpetra_Tempus

**Comment by ikalash** [comment]
Shoot...  I thought I fixed that.  Thanks, I will take a look.

**Comment by ikalash** [comment]
@bartgol : so did you test this by just using the file I sent you a few days ago or by checking out the piro_tempus_fix_observer branch of Trilinos?  The PR you're referring to is based on the latter which has a minor change from the file I sent you to deal with this seg fault issue.

**Comment by ikalash** [comment]
I just double checked again and the tests pass for me with the change in the piro_tempus_fix_observer branch of Trilinos in the PR, so I think things are good; let me know if you find otherwise.

**Comment by bartgol** [comment]
@ikalash I only used the patch you sent. So it may be it was missing some other stuff.

**Comment by bartgol** [comment]
100% tests passed after the fix.

**Comment by ikalash** [comment]
Ah ok.  Yes, it was indeed missing some logic that can cause a seg fault in some cases.  I realized that when creating the PR for Trilinos.  Thanks for checking though!
