### ISSUE TITLE
MALI infrastructure work

### ISSUE THREAD

**Issue by mperego** [gahansen/Albany#374]
There is some infrastructure work needed in Albany LandIce to improve the overall MALI (MPAS-Albany LandIce) code:
1) Use the new boundary conditions instead of using PHAL::Neumann in the MPAS Interface
2) Use the ExtrudedSTKMeshStruct instead of the MpasSTKMeshStruct in the MPAS Interface
3) Make MALI compile with shared libraries. This might need a little bit of refactoring and avoid declaring some function as extern in the c++ interface (in MPAS repo).

We can split this in different issues if needed.

**Comment by bartgol** [comment]
For 3., do you mean getting MPAS to link to a shared albanly library? If so, then we can also put the files that define the extern function into a third small library and link as `mpif90 main_mali.F90.o -lalbanyLib.so -llibrary_with_extern_definitions.so`. That should work too, no?

**Comment by mperego** [comment]
@bartgol yeah I think you are right. But I'm not sure we really need to declare those functions as extern.

**Comment by bartgol** [comment]
I think the mpas infrastructure now works. We did not fulfull point 2 in @mperego 's list, but the interface works, so I'm going to close this for now.
