### ISSUE TITLE
Compilation error on Ride from Tpetra::getDefaultComm call

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#375]
Here is the error - it started today and I think has to do with @bartgol 's changes on Friday:

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=77325

I tried to add some includes (Tpetra_Core.hpp, Tpetra_DefaultPlatform.hpp) which did not help.  Perhaps there are some limitations to how the routine works with CUDA?

**Comment by ikalash** [comment]
@bartgol : I checked Tpetra_Core.hpp in the Trilinos install and 
```
Teuchos::RCP<const Teuchos::Comm<int> > getDefaultComm ();
```
does appear there.  Let me try submitting the job again through Jenkins to see what happens.  Sometimes weird errors like this do pop up in a build for no apparent reason, then go away.

**Comment by bartgol** [comment]
Yeah, could be a node glitch. I cannot think of any issue on our end that would cause the error...

**Comment by ikalash** [comment]
I just ran the Ride job again and it worked just fine...  so seems the failure was not a real one.  Sorry for bugging you about it @bartgol !

**Comment by bartgol** [comment]
No worries. Glad it worked out.

**Comment by ikalash** [comment]
I spoke too soon...  this issue is still showing up, not only on Ride but also on Waterman (so it is a CUDA issue).  @bartgol ,  do  you have SRN access?  If so you should be able to get accounts on Ride and Waterman.

**Comment by bartgol** [comment]
I do not have access to RIDE (they denied my request). I have access to waterman, thoguh. I will check there.

**Comment by ikalash** [comment]
Thanks @bartgol .  The nightly testing output / scripts can be found here on waterman: /home/projects/albany/waterman .  Here is the link to the most recent CDash page showing the error: http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=77388 .

**Comment by bartgol** [comment]
@ikalash I don't have access to the albany folder. I do not belong to the wg-albany metagroup. I see you are an admin of that mg. Could you please add me?

**Comment by ikalash** [comment]
@bartgol : done.  You should have access immediately based on a similar experience a couple weeks ago when I added Jerry to the metagroup.

**Comment by jewatkins** [comment]
@bartgol @ikalash I just tried adding `Tpetra_Core.hpp` and it seemed to work on my build on waterman. Let's see if that fixes it.

**Comment by ikalash** [comment]
I tried this yesterday on Ride and still got the problem - very strange.  Lets hope this fixes it!

**Comment by bartgol** [comment]
I grepped Tpetra_Core.hpp in the install folder, and indeed is only included by `Tpetra_*Platform.hpp` (which are deprecated), and by `Tpetra_Map_def.hpp`. So it _does_ make sense that manually including it fixes things. Not sure why it wouldn't fix things on ride though...

**Comment by ikalash** [comment]
Lets see what the nightlies reveal tomorrow with Jerry's fix.

**Comment by bartgol** [comment]
Also, I'm not sure why this does not yield errors on other platforms. To be fair, `Tpetra_Core.hpp` is also included by a handful of other headers in Trilinos. However, I doubt those files end up including `Tpetra_Core.hpp` only on non-gpu builds...

**Comment by ikalash** [comment]
I agree, that is a mystery...

**Comment by ikalash** [comment]
Looks like now there is a MueLu link error: http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=77530 .

**Comment by jewatkins** [comment]
I just checked my build and I don't get a linking error. Not sure what it could be. The only major difference I see is that I turn off `MueLu_ENABLE_Tutorial`. I'm also not building from scratch so I suppose that could contribute.

**Comment by ikalash** [comment]
Hmmm, the tutorial should not affect the build.   I think I will open a Trilinos issue...  I don't see how the problem can be on the Albany side.

**Comment by bartgol** [comment]
@ikalash Did the link error happen more than once? I saw nodes behaving randomly in the past, and report errors that were just related to nodes' fluctuations. I would wait to see the same error happen at least twice before opening an issue.

**Comment by ikalash** [comment]
@bartgol : it happened on both ride and waterman last night

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=77600
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?onlydeltap&buildid=77574

This seems to suggest it's a real issue.  Anyway, I can wait to see if it occurs again tomorrow.

**Comment by bartgol** [comment]
Ok. Do waterman and ride share filesystem? If so, may be a glitch. If they are completely separeted, then it may be already enough to warrant an issue.

**Comment by jewatkins** [comment]
Yeah they share a filesystem. I think waiting until tomorrow morning seems reasonable.

**Comment by jewatkins** [comment]
Looks like we still have the same issue.

**Comment by bartgol** [comment]
Looks like there's a parsing error:

`undefined reference to `Tpetra::CrsMatrix >::setAllValues(Kokkos::View, Kokkos::MemoryTraits<0u> > const&, Kokkos::View, Kokkos::MemoryTraits<0u> > const&, Kokkos::View, void> const&)'`

The angle brackets are all messed up.

**Comment by ikalash** [comment]
I think we should open a Trilinos issue.  I will do so shortly.

**Comment by ikalash** [comment]
Closing this issue since is has morphed into another one.  Please see the following Trilinos issue for discussion about the MueLu link problem: https://github.com/trilinos/Trilinos/issues/3772
