### ISSUE TITLE
Switch Albany tests from xml to yaml 

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#376]
Requires no extra TPLs or changes to the code.  After the chance, code will still work with xml if someone wishes to use it.  Please comment here if there are any objections.  I plan to work on this this week.

**Comment by ikalash** [comment]
I have completed the changes from xml to yaml for all Albany problem.  So finally Albany is xml-free :).  

One thing to note when working with XML is it does not allow arrays of zero length.  So if you have a line like:

Response Fields: [] 

you'll get a run-time error.  The fix is to just delete the line causing the problem.

**Comment by bartgol** [comment]
@ikalash  I have a question on yaml, and I figured I tracked the answer here, so others can see it.

In the input files I see doubles stored with full decimal precision, even for integers. E.g., I see 

`Water Density: 1.00000000000000000e+03`

while I would expect

`Water Density: 1000.0` or `Water Density: 1.0e3`

to be good enough. Does it matter? Do I _have_ to use full decimal precision if I want the number to be read as a double?

**Comment by ikalash** [comment]
@bartgol : good question.  Either of the alternatives you provide are fine for yaml.  I think the reason it was written the way it was is that is how the xml2yaml utility does the conversion.

**Comment by bartgol** [comment]
Ah, that makes sense. And it also explains why certain numbers have a weird rounding, like '1.000000000000000012e+00`

**Comment by ikalash** [comment]
Yes, sorry for the confusion!
