### ISSUE TITLE
Compilation error when building MPAS interface

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#381]
A compilation error cropped up last night when building the MPAS interface:

```
repos/Albany/src/LandIce/interface_with_mpas/Albany_MpasSTKMeshStruct.cpp:200:3: error: 'ebNameToIndex' was not declared in this scope
```
See, for example, https://my.cdash.org/viewBuildError.php?buildid=1557220 .  @bartgol , I think this is related to your PR yesterday.  Can you please have a look?

**Comment by mperego** [comment]
Thanks @ikalash. Yes, it s related to that PA. @bartgol and I are working on it. It might a little while because we are also changing a few things in MPAS interface as well. Anyway, if it is taking longer than expected we'll simply fix the compilation error.

**Comment by ikalash** [comment]
No problem, thanks.

**Comment by bartgol** [comment]
I think this has been solved, so I'm closing.
