### ISSUE TITLE
Nightly build errors in PHAL_Neumann_Def.hpp

### ISSUE THREAD

**Issue by jewatkins** [gahansen/Albany#382]
```
Albany/src/evaluators/bc/PHAL_Neumann_Def.hpp:844:3: error: ‘fT’ was not declared in this scope
fT = workset.fT;

Albany/src/evaluators/bc/PHAL_Neumann_Def.hpp:853:3: error: ‘JacT’ was not declared in this scope
JacT = workset.JacT;
```
It looks like there's some `ALBANY_KOKKOS_UNDER_DEVELOPMENT` guards causing it in the header file. @bartgol We could probably just move/remove the guards but I'll let you handle it because I know you've been working on cleaning some of this up. I assume everyone is building Albany with Kokkos at this point (don't think it would compile without it).

**Comment by bartgol** [comment]
Yes, Mauro ran into this with the mpas branch on my fork. The code compiled fine on my machine, but I guess I was ending up in a different branch of the `#ifdef ALBANY_KOKKOS_UNDER_DEVELOPMENT`.

Speaking of which: do we have plans to remove that cpp if? I think the time is mature, and it would improve code maintainability, avoiding further issues like this.

**Comment by bartgol** [comment]
Yes, those are much more readable macros. I never know whether `ALBANY_KOKKOS_UNDER_DEVELOPMENT` means 'this branch is trying to use kokkos' or 'kokkos is under development, so don't use it'. I always have to look at the code to figure it out...

**Comment by jewatkins** [comment]
I have the same issue. When I first started using it, I assumed two completely different branches. I quickly realized that not everyone used it the same way. We definitely need to at least clean it up. One of us could try to tap general Albany funds to do a code wide cleanup. I'll create a separate issue.

**Comment by bartgol** [comment]
Sorry @lxmota , I think that was my fault. Both @jewatkins and @mperego ran into this problem, but I forgot to push a bugfix. I will do it today.

**Comment by jewatkins** [comment]
It looks like this was fixed by requiring `ALBANY_KOKKOS_UNDER_DEVELOPMENT` to be on. Let's work towards cleaning up this macro in #385.
