### ISSUE TITLE
Failing FO_GIS tests on waterman

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#384]
The following FO_GIS tests began failing on waterman on Oct. 17:

```
FO_GIS_GisPopulateMeshes 
FO_GIS_GisUnstructuredPerformance_Tpetra
FO_GIS_GisUnstructuredTpetra 
FO_GIS_GisAdjointSensitivityTpetra 
FO_GIS_GisAdjointSensitivityBasalFrictionTpetra 
FO_GIS_GisAdjointSensitivityStiffeningBasalFrictionTpetra 
FO_GIS_GisSensSMBwrtBetaTpetra 
FO_GIS_GisCoupledThicknessTpetra
```
The error is one that typically appears when netcdf wasn't built with parallel netcdf and a test is being run with 'Use Serial Mesh = true':
```
 Expr '!(Teuchos::is_null(m_database) || !m_database->ok(true))' eval'd to true, throwing.
 Error occured at: stk_io/stk_io/InputFile.cpp:142
 Error: ERROR: Could not open database '../ExoMeshes/gis_unstruct_2d.exo' of type 'exodusII'
 ```
I am wondering if something happened on waterman with the modules on 10/17 that caused this to start happening.  Not sure what else would trigger it.  We could change the problems to run with 'Use Serial Mesh = false' I suppose to get around this.  This would require checking in the decomp'ed files.

**Comment by bartgol** [comment]
Another option is to add a custom target, whose job is simply to decomp the mesh in N parts, with N being the number of ranks we use in the tests (might be we have two of those values).

**Comment by ikalash** [comment]
That’s a good idea @bartgol .  We do it already for some LCM problems.

**Comment by jewatkins** [comment]
Any progress on this? The first instance of this error is while populating the 3D meshes in http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=4075350&build=78324 and it looks like this:
```
EXODUS: ERROR: Attempting to open the classic NetCDF file:
	'gis_unstruct_2d.exo'
	 failed. The netcdf library supports PNetCDF files as required for parallel readinf of this file type, so there must be a filesystem or some other issue 
```
so I think pnetcdf is there and it might be a system issue. Are these tests the only ones that use pnetcdf? If we switch to using a decomp'd mesh to fix this, that may mean we no longer support the `Use Serial Mesh` option. Not sure if we want to go that route or not.

**Comment by jewatkins** [comment]
It looks like there's some LCM tests which use this option so I'd be okay with switching these tests to a decomp'd mesh if there's no other reason to keep the serial mesh option.

**Comment by mperego** [comment]
I like to have the option to use a serial mesh. If it is too hard to maintain it I'm fine that though.

**Comment by bartgol** [comment]
Based on experience, the error reported has to do with an issue in the installation of netcdf/pnetcdf. Waterman should be using sems though, which should be working.

**Comment by jewatkins** [comment]
waterman uses a version of netcdf/pnetcdf that was built June 30th (just checked the lib dates). The last time all tests were passing on waterman was Nov. 6th so I don't think it has to do with the library installations. I don't think the modules change that often.

**Comment by jewatkins** [comment]
I just tested some of these cases on a fresh Albany build on waterman and they work okay... I'm not sure what could happen in the nightlies that could cause the error.

**Comment by bartgol** [comment]
Perhaps the nightlies used some verison of netcdf that is no longer there. If there was a system netcdf, it would be then used (I had this issue on my laptop in the past, and the system version was not parallel). I checked and waterman does not have system netcdf libraries. But perhaps something along these lines.

I am not at sandia, so I can't check the dashboard, but it would be interesting to see the nightlies config log, to see what netcdf library trilinos detects.

**Comment by jewatkins** [comment]
It looks like it's grabbing the right one. Also, I used the Trilinos nightly install to build Albany and it seemed to work so I don't think it's the Trilinos build/install.

**Comment by bartgol** [comment]
Then I'm out of ideas. I blame it on Murphy, and claim the build is not broken.

**Comment by jewatkins** [comment]
Just tested the exact same executable and it worked (although there seems to be some other errors).

**Comment by bartgol** [comment]
[This](https://en.wikipedia.org/wiki/Heisenbug) is happening.

**Comment by jewatkins** [comment]
Sounds about right.

**Comment by jewatkins** [comment]
I somehow willed this bug into submission because the nightlies are all passing now.
