### ISSUE TITLE
Aeras does not compile and/or tests fail if MeshScalarT!=RealType

### ISSUE THREAD

**Issue by bartgol** [gahansen/Albany#391]
I ran into this issue when working on the thyra refactor branch. I wanted to extensively test the library, in order to not leave anyone in deep water, but ran into trouble with Aeras' _shallow water_ equations (pun intended).

The compilation errors stem from the fact that in several occasions the assumption MeshScalarT=RealType is made (especially when filling the jacobian).

Upon replacing uses of MeshScalarT with ADValue(MeshScalarT), the code compiled, but some tests failed due to NaN in the jacobian.

I am not sure how to proceed with this. I understand that Aeras never uses the capabilities of mesh depending on parameters/solution. On the other hand, I'd like users to be able to build/run the code without problems. One solution could be to disable Aeras or error out if at config time one requests the feature of the mesh depending on parameters/solution.

@ikalash , tagging you, since you are the maintainer of Aeras.

**Comment by ikalash** [comment]
Hmmm.  Not sure what is going on here.  I'd be interested to see where the assumptions are made.  I guess I can find it by pulling your branch and searching for ADValue(MeshScalarT) within the Aeras dir?  

One thing that comes to mind is that while the Aeras project is underway, I did put in a capability to create the Jacobian without requiring AD as a speed-up for the explicit case (the practical use case for Aeras).  Most of the tests do not exercise this capability however, and there are still some implicit tests.  I'd like to try to understand the NaNs but if we decide to punt on this, we should be able to switch all the explicit tests to not use AD, and to turn off the implicit tests (to keep the practical use case).  Maybe we should do the former anyway now that I think about it.

**Comment by bartgol** [comment]
Per our discussion in #356, I'm going to punt on this, inhibiting the simultaneous enabling of Aeras and funky mesh options.
