### ISSUE TITLE
Issue in Intrepid2::evaluate() call from PHAL::Neumann for robin BC

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#401]
This is a spin-off issue from #398.

It looks like one of the errors in the Alb64BitDbg build is an improper call to the Intrepid2::evaluate() routine by giving it a DynRankView with rank 3 instead of the expected rank 2: 

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=4143796&build=79149

This shows up for the robin BC tests, as the one above.  The problematic code is here: https://github.com/gahansen/Albany/blob/master/src/evaluators/bc/PHAL_Neumann_Def.hpp#L443-L463 .  The issue seems to have come in when the relevant DynRankViews were augmented to have an extra dimension corresponding to the DOF number as part of @bartgol 's cleanup of the PHAL::Neumann class.  A fix should be to use subviews.  I just talked to @mperego and he believes, Luca, you already have a fix to this issue in one of your branches - is that correct?  In any case, opening this issue to document the problem.

**Comment by bartgol** [comment]
I thought I fixed this, but I can't find the commit anywhere. What I thought I did is to simply do the fol loop by hand, without calling Intrepid2.  Subviews should work as well, assuming Intrepid2 can handle strided views.

**Comment by ikalash** [comment]
Could you please fix it if you did it once before?  I haven't worked much with DynRankViews so it would take me awhile to figure out the usage / proper extraction of subviews.

**Comment by bartgol** [comment]
Testing the fix right now.

**Comment by ikalash** [comment]
Perfect, thanks Luca!  I am up to my eyeballs with failing tests that I am trying to fix!!

**Comment by bartgol** [comment]
If we switch to organization soon, we can set up a travis-ci build with a check on all incoming PRs. Then we'll cathc most of the problems before they end up in master.

**Comment by mperego** [comment]
@bartgol, I remember looking at this at your desk and you fixed that with subviews. I think it is better to use Intrepid2 when possible.

**Comment by bartgol** [comment]
I am using Intrepid2 and subviews. I don't recall doing it before though. I blame my old age.

**Comment by bartgol** [comment]
After the commit I still get tests failing, but I _think_ it's for different reasons, so I closed the issue in the commit.

**Comment by ikalash** [comment]
What is failing for you?  I thought I got things pretty clean with PHAL::Neumann, with this being the only remaining unresolved issue.

**Comment by bartgol** [comment]
The mixed_paramT test still fails (randomly) because of a nan that sometimes is there, sometimes it is not there. Could one of you try to manually run it a few times? If it really has a non-deterministic outcome, it may just have randomly passed for you guys...

**Comment by bartgol** [comment]
Uh, when the test passes, I get that the mean of the solution is 3.213831168105e+278. It is nan when it fails (because of FPEs). My suspicion is that there's a problem with the solution mean, which sometimes ends up in a nan, sometimes not. Could be a leftover from the thyra refactor.

**Comment by ikalash** [comment]
This is issue #402 which I opened last night.  I believe this PR is @mperego 's fix: https://github.com/trilinos/Trilinos/pull/4041 .

**Comment by mperego** [comment]
Yeah, the mean should be correct now. I also pushed your commit a2f6f09c6a02 that should help.
I tried on my workstation a dozen of times (w/ the Piro fix) and it doesn't fail. Let's see tomorrow the Dashboard

**Comment by bartgol** [comment]
Oh, so I need to wait for the trilinos fix to get in develop, right?

**Comment by mperego** [comment]
Yeah, and it seems there are some problems with the Trilinos testing.. hope it will be merged by the end of the day.
