### ISSUE TITLE
Failures / nans in SteadyHeatConstrainedOpt2D_Dirichlet_Mixed_ParamsT

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#402]
There is some weird behavior with the SteadyHeatConstrainedOpt2D_Dirichlet_Mixed_ParamsT on some platforms.  Below is a summary of where the test passes/fails from CDash (http://cdash.sandia.gov/CDash-2-3-0/testSummary.php?project=10&name=SteadyHeatConstrainedOpt2D_Dirichlet_Mixed_ParamsT&date=2018-12-11) 

- ride.sandia.gov -  Failed sensitivity comparison
```
Sensitivity Test 0,0: 1.554342036747e-01 != -1.981199378320e-01 (rel 1.000000000000e-03 abs 1.000000000000e-08)
 ``` 
- cee-compute013 (Albany64Bit) - Failed due to FPE after the following is printed 
```
 Sensitivities (0,1) for Distributed Parameters:  (two-norm)
         6.397564008086e-02
``` 
- skybridge-login5 - Failed due to nan sensitivity followed by FPE
```
 Sensitivities (0,0):!
                     -nan
 Sensitivity Test 0,0: -nan != -1.981199378320e-01 (rel 1.000000000000e-03 abs 1.000000000000e-08)
```
- waterman.sandia.gov - Failed sensitivity comparison
```
Sensitivity Test 0,0: 1.554342036747e-01 != -1.981199378320e-01 (rel 1.000000000000e-03 abs 1.000000000000e-08)
```
- cee-compute020 (Albany64BitDbg) - Failed due to nan sensitivity + FPE
```
 Sensitivities (0,0):!
                     -nan
```
- cee-compute016 (Albany64BitClang) - seems to fail for no obvious reason 
- ceerws1006 - Failed due to nan sensitivity followed by FPE
```
Sensitivities (0,0):!
                      -nan
```
- cee-compute018 (AlbanyIntel) - Failed due to bad termination of program  

It looks like based on the skybridge build (which has been fairly consistent) the failures there started 11/29.  What is interesting is they seem inconsistent - some nights, it passes, others it does not (e.g. on 12/2 it passed http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany&date=2018-12-03&subproject=albany_cluster-toss3_skybridge-login5_serial-intel-release whereas on 12/4 it failed http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlyfailed&buildid=78914).

I am concerned that there is a more fundamental issue underlying this test - it appears that since the test was created in late July, the MeanValue printed was either nan or O(10^100) on most (but interestingly enough not all - on ride it's 0) platforms: http://cdash.sandia.gov/CDash-2-3-0/testSummary.php?project=10&name=SteadyHeatConstrainedOpt2D_Dirichlet_Mixed_ParamsT&date=2018-07-24 ).  This points to the test being buggy.  Note that the same behavior is not observed for the Epetra version of the test.  

@mperego graciously agreed to have a look at this - thanks Mauro!

**Comment by ikalash** [comment]
Seems this problem has been resolved.  Thanks @mperego !

**Comment by mperego** [comment]
Great!
