### ISSUE TITLE
Use of Intrepid(2) RealSpaceTools

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#41]
@jtostie, in commit 55f111b you left a comment

```
THE INTREPID REALSPACE TOOLS AND FUNCTION SPACE TOOLS NEED TO BE REMOVED
```

I was wondering what the reasoning behind this comment is.
The reason I'm bringing it up now is I'm having issues getting the (now Intrepid2) RealSpaceTools to work with `const ScalarT` arguments, and I'm wondering if instead of trying to fix them I should be replacing them with something else.

**Comment by jtostie** [comment]
In practice, the setting of the container sizes necessary to use the RST and FST is error prone, and honestly I was tired of trying to debug it. This is related to the way the workset size is computed and the impact it has on the container sizes. The alternative is to implement the same operations locally, often using MiniTensor objects, which is cleaner and more readable, and much less prone to memory and indexing errors.

**Comment by mperego** [comment]
I'm probably biased, but I would think we could take more advantage of Intrepid2. There is a lot of work happening in Itrepid2 and downstream (e.g. Kokkos Kernels) and if we stick to Intrepid2 and properly use their functions we could take advantage of that, especially regarding portability.
Dan, if you want I can help you with the issue you are having right now.

**Comment by mperego** [comment]
@ibaned Just saw your related issue in Trilinos.

**Comment by ibaned** [comment]
@mperego could you please take a look at trilinos/Trilinos#1030 ? Thanks !

**Comment by ibaned** [comment]
The resolution of trilinos/Trilinos#1030 also resolves this issue in the near term.
