### ISSUE TITLE
Where does Albany::StateStruct::FieldDims dims get set? 

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#411]
This is a question to fellow Albany developers. 

I am trying to figure out where Albany::StateStruct::FieldDims dims gets set within Albany, for the purpose of swapping some of entries for the QPTensorFieldType.  Specifically, currently for this layout, we have; 

dim[0] = nCells, dim[1] = nQP, dim[2] = nVec dim[3] = nVec 

I would like to change this to 

dim[0] = nCells, dim[1] = nVec, dim[2] = nVec dim[3] = nQP

but I am having a hard time tracking down the origin of dims.

**Comment by bartgol** [comment]
They're set by the StateManager, during the state registration. See [](https://github.com/gahansen/Albany/blob/0f77a088be22e3d103cf52c6e920df0bf0fe101e/src/Albany_StateManager.cpp#L246).

**Comment by ikalash** [comment]
Thanks @bartgol that is helpful.  I am somewhat stumped by one thing I am observing having to do with dims.  

I am trying to change the code so that the qp_tensor fields are written to the mesh having the layout (nDim, nDim, nQPs).  Currently it is written out as having the layout (nQPs, nDim, nDim).  I emphasize that I only care about changing the layout in the output mesh; not within the code.  Therefore I do not want to change the qp_tensor field layout in the code (https://github.com/gahansen/Albany/blob/master/src/problems/Albany_Layouts.cpp#L55).  

The relevant line to make the change I want to make should be this one: 
https://github.com/gahansen/Albany/blob/master/src/disc/stk/Albany_GenericSTKFieldContainer_Def.hpp#L146-L147

My change would change these lines to:
```
stk::mesh::put_field_on_mesh(*qptensor_states.back() ,
metaData->universal_part(), dim[1], dim[2], dim[3], nullptr);
```
(where dim[1] = nDim, dim[2] = nDim, dim[3] = nQPs). 

What puzzles me is this change seems to change the dim variable throughout the code.  Specifically, in Albany_StateManager.cpp (https://github.com/gahansen/Albany/blob/master/src/Albany_StateManager.cpp#L736), it turns out that the dims entries gets swapped, so that dims[1] = nQPs, dims[2] = nDim, dims[3] = nDim.  It is as though the layout gets changed through the stk::mesh::put_field_on_mesh call, and I don't see why that would happen.  Clearly I am missing something - any thoughts?

**Comment by bartgol** [comment]
So you want the QP index to stride fastest? I'm puzzled by the `put_field_on_mesh` signature: I would assume that `put_field_on_mesh(field, part, n1, n2, n3)` would mean that n3 strides faster, in which case the QP index should _already_ stride faster (since we have dim[3], dim[2], dim[1] in the function call). Is that not the case?

Another thing to keep in mind as you do this change (but maybe you already worked it out) is the `computeWorksetInfo` method of the STK discretization: around line 2076 we copy data from the stk field into the albany state array. If you swap the dimensions when you put the field in the mesh, you also need to re-work out the indexing math when copying data from the 1d stk array into the n-d albany state.

**Comment by ikalash** [comment]
@bartgol I don't think about it in terms "striding faster".  The issue is that of how qp_tensor fields relevant for LCM, e.g., Cauchy_Stress, appear in the exodus output file.  Lets assume the layout is (nDim, nDim, nQP), as it is now, with nDim = 3 and nQP = 8.  Then the field will appear as follows in the exo file:

Cauchy_Stress_1_1
Cauchy_Stress_2_1
Cauchy_Stress_3_1
...
Cauchy_Stress_3_24

(Alan Williams explained it very well here: https://github.com/trilinos/Trilinos/issues/3377#issuecomment-421420928 ). These names are not nice b/c it is not clear which component/quadrature point each field corresponds to.  It would be much better to have the names look like: 

Cauchy_Stress_1_1
Cauchy_Stress_1_2
Cauchy_Stress_1_3
...
Cauchy_Stress_1_9
...
Cauchy_Stress_8_1
...
Cauchy_Stress_8_9 

The way to achieve this *should* be as simple as swapping dim[1] and dim[3] in the stk::mesh::put_field_on_mesh call for the qp_tensor layout.  

I'm aware of the line in computeWorksetInfo you are pointing to, and agree it would need to be changed, but that code actually is not called for the problems I am running (nodal_states.size = 0 as the states are not nodal but rather elemental).  By this change
```
stk::mesh::put_field_on_mesh(*qptensor_states.back() ,
metaData->universal_part(), dim[1], dim[2], dim[3], nullptr);
```
I get the following exception thrown.  
```
 /home/ikalash/nightlyCDash/repos/Albany/src/Albany_StateManager.cpp:1153:
 Throw number = 1
 Throw test that evaluated to true: !(dims[2] == dims[3])
```
It is as though the dims in Albany_StateManager.cpp is getting pulled from the layout given to put_field_on_mesh, which I don't understand.  dims is coming from 
```
 Albany::StateArrayVec& esa                  = sa.elemStateArrays;
```
where the elemStateArrays comes from Albany_STKDiscretization.cpp: https://github.com/gahansen/Albany/blob/master/src/disc/stk/Albany_STKDiscretization.cpp#L2331-L2339 .  Here the BucketArray (effectively a shards array) should come from the qp_tensor layout (https://github.com/gahansen/Albany/blob/master/src/problems/Albany_Layouts.cpp#L55), no?  Am I misunderstanding how the shards arrays work?

**Comment by bartgol** [comment]
Ah, that 'dims' is not coming from the state manager, but the mesh. And the line I pointed you to is not the right one. As you noticed, that's for nodal states. But around [this line](https://github.com/gahansen/Albany/blob/9479157a493bb65fd85bcb7e4397d90530e12f43/src/disc/stk/Albany_STKDiscretization.cpp#L2331) the same thing happens for element-based arrays. Here, I _think_ the dimensions are set according to what's in the stk mesh. These dimensions then end up being read in the state manager's call you reported, yielding an exception.

Have you fixed the computeWorksetInfo method yet? If not, I would bet it's right there...

**Comment by ikalash** [comment]
Oh, yes, there are a lot (probably too many) dims floating around the code - sorry about the confusion.  

I finally found what I was looking for with your help :).  If you (or anyone else is interested), this is the relevant code (https://github.com/gahansen/Albany/blob/master/src/disc/stk/Albany_BucketArray.hpp#L126-L131):
```
else if (f.field_array_rank() == 3) {
        int dim0 = stk::mesh::find_restriction(f, b.entity_rank(), b.supersets()).dimension();
        stride[0] = dim0;
        stride[1] = get_size<Tag2>(b) * dim0;
        stride[2] = stk::mesh::field_scalars_per_entity(f, b);
}
```
I guess put_mesh_on_field modifies the underlying mesh (which makes sense in retrospect), so if I swap dim[1] and dim[3] when I call stk::mesh::put_field_on_mesh, that changes dim0 in the above code from 3 to 8.  That causes all sorts of issues downstream.  The solution is to force dim0 to be 3 for this example (or more generally get_size<Tag1>(b), I think).  That achieves the desired layouts in the output exodus file and allows the code to run through.  

Now, this is for one example; I may need to make other changes for other problems, which I need to check. 

Anyway, thanks for your help, needed to talk this one through with someone who has worked with these damn stk objects!
