### ISSUE TITLE
Increase default workset size in Albany

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#43]
Currently, the default workset size in Albany is 50, which is quite small.  Is anyone opposed to increasing the default value?  This is of particular interest for a build with a CUDA KokkosNode - many of the tests time out when run on a GPU b/c the workset size is too small, meaning the GPU does not have enough work to do relative to copies that are done.  

If people agree to increase the default workset size, what is a reasonable value to use?  Should we have an #ifdef Kokkos_ENABLE_Cuda that sets the default workset size (e.g., workset size = -1, which puts everything in 1 workset) to an even larger value when running on GPUs?  One possible issue with this is that a problem may not fit on a GPU with workset size = -1, but I would think this would not happen for the ctest tests, as these are supposed to be small.  @jewatkins , any thoughts?

**Comment by mperego** [comment]
I agree on increasing the default workset size (this will help to mitigate the overhead of the Intrepid2 functions) . 
However, I think it is best not to put workset size = -1 in all the tests (even for CUDA only builds) because then the case of multiple worksets per process is never tested.

**Comment by ibaned** [comment]
I think its early to base the default specifically on the GPU use case. I suspect Albany usage of GPU memory is nowhere near optimal yet. A while back I raised the default from 50 to 1000 for the PUMI Discretization; I propose we do the same for STK and see how things go from there. I am certain there are test problems with >1000 elements, so multiple worksets would still get exercised.

**Comment by ikalash** [comment]
I am fine with 1000.  @ibaned , can you please make this change if there are no objections?  I'll assign the issue to you.  It will be interesting to see how the CUDA test results change with this increase in workset size.

**Comment by ibaned** [comment]
so my memory was off and PUMI was using ten thousand, but I changed it everywhere to one thousand. I'm closing this for now, lets reopen if it needs changing again or I broke something.

**Comment by agsalin** [comment]
Dan: I'm getting errors in my nightly build from this change. For Example:
  examples/FELIX/FO_GIS/input_fo_gis_unstruct.xml 

Error has to do with type -- not clear why you chose to free it from an <int>.

> 
> p=0: *** Caught standard std::exception of type 'Teuchos::Exceptions::InvalidParameterType' :
> 
>  Error!  An attempt was made to access parameter "Workset Size" of type "int"
>  in the parameter (sub)list "Albany Parameters->Discretization"
>  using the incorrect type "Albany::AbstractMeshStruct::{unnamed type#1}"!
>  
>  Throw number = 1

**Comment by mperego** [comment]
Hi Andy, that has been fixed (see #47).
