### ISSUE TITLE
Create instructions for building / running Albany with CUDA KokkosNode on WiKi

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#45]
@jewatkins , can you please do this, e.g., for the Ride machine, for both the P100s and K80s?

**Comment by jewatkins** [comment]
Done. Building instructions can be found [here](https://github.com/gahansen/Albany/wiki/Building-Albany-on-Ride-or-White). Executing instructions can be found [here](https://github.com/gahansen/Albany/wiki/Executing-Albany-on-Ride-or-White). I have yet to add example scripts for MPI+OpenMP. I'll save that for later. I'll close this issue for now but feel free to open it again if there's any problems.
