### ISSUE TITLE
Failing FELIX tests due to change in default workset size

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#47]
The following FELIX tests failed in last night builds due to the change in default workset size: 

 FO_GIS_GisUnstructured 	
FO_GIS_GisCoupledThickness 	
FO_GIS_GisManifold 	
 FO_GIS_GisRestartUnstructured 	
FO_GIS_GisAdjointSensitivity 
FO_GIS_GisWedgeAdjointSensitivity 	
 FO_GIS_GisAdjointSensitivityBasalFriction 	
FO_GIS_GisAdjointSensitivityStiffeningBasalFriction 	
 FO_GIS_GisSensSMBwrtBeta 	
 FO_GIS_GisSensSMBwrtBetaRestart

It looks like the errors are all the same: 

Test output

Albany_IOSS: Loading STKMesh from Exodus file  ../ExoMeshes/gis_unstruct_2d.exo

Using decomposition method 'RIB' on 4 processors.

p=0: *** Caught standard std::exception of type 'Teuchos::Exceptions::InvalidParameterType' :

 Error!  An attempt was made to access parameter "Workset Size" of type "int"
 in the parameter (sub)list "Albany Parameters->Discretization"
 using the incorrect type "Albany::AbstractMeshStruct::{unnamed type#1}"!
 
 Throw number = 1

See http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlydelta&buildid=47874 (SRN CDash).

**Comment by mperego** [comment]
Fixed. ( af1cd136ff894beff0a91692f46703b75c0c44de).
