### ISSUE TITLE
Setting of Workset Size in input file for ATO::2Matl tests does not appear to be working

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#48]
A few of the ATO tests began to fail last night with the change in default workset size due to having been baselined against a gold file generated with workset size = 50 and tight exodiff tolerances.  I attempted to fix the tests by setting the workset size = 50 in the input file (adding the line <Parameter name="Workset Size" type="int" value="50"/> under "Discretization) but it does not appear to work -- when I print workset size in Albany::IOSSSTKMeshStruct, it is > 50.  I have verified that commit 2eb2559f23cca3b7979d07f952687944ac17be7f (change in workset size default value) is what broke this test.  @ibaned , can you please look into why the workset size value specified in the input file does not overwrite the default value in the code for these tests?

**Comment by ibaned** [comment]
I think you should consider it a separate bug that you get a different answer with a different workset size. Is there any known reason why workset size could affect results at all ? Anyway, I'll look at the input parameter issue.

**Comment by ikalash** [comment]
I agree.  This is a question for @jrobbin, the author of ATO.  I'll take this up with him.  It looks to me like the solutions are slightly off in the 4th decimal point with the different workset size.  I don't know enough about the physics and gold file to say if this is significant and why this is workset dependent.  If you could look at the input issue for now, that would be great.  We want the user to be able to control the workset size from the input file for all physics in Albany, if this is desired.

**Comment by djlittl** [comment]
My experience is that different work set sizes can produce diffs that are roughly the same as the diffs you get from running on different numbers of processors.  I think the root cause is subtle changes in order of operations, etc.

________________________________

**Comment by ibaned** [comment]
Why are these tests only active if Albany is not in 64-bit mode ? This is the fifth time I've had to rebuild Albany trying to compile ATO...

**Comment by ikalash** [comment]
@jrobbin is the author of ATO and the one who put in that logic so he can best answer this question.  My guess is the logic was put in as a precaution, since the original Epetra-only code was not meant to run for huge problem requiring 64-bit int GOs.  I will check if the examples can be activated in a 64-bit build, and turn them on there, if they work.  Sorry for the frustrations this is causing, @ibaned ....

**Comment by ibaned** [comment]
@ikalash it looks like the parameter was just in the wrong place in the input file. ATO is confusing because it has "Discretization" lists for all the subproblems, and then a separate one outside of "Problem". Commit 04592a5 should fix this.

**Comment by ikalash** [comment]
I see -- I missed this detail.  Thanks for fixing it, @ibaned !
