### ISSUE TITLE
cudaFree(m) error for FELIX Epetra tests run on GPUs (CUDA KokkosNode)

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#55]
Some Albany FELIX Epetra tests with a CUDA KokkosNode (on GPUs) run to completion, then throw a cudaFree(m) error: 

terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaFree(m) error( cudaErrorCudartUnloading): driver shutting down /home/ikalash/nightlyCDash/build/TrilinosInstall/include/Sacado_DynamicArrayTraits.hpp:172
Traceback functionality not available

[ride11:96460] *** Process received signal ***
[ride11:96460] Signal: Aborted (6)
[ride11:96460] Signal code:  (-6)
[ride11:96460] [ 0] [0x100000050478]
[ride11:96460] [ 1] /lib64/libc.so.6(abort+0x280)[0x10000e680d70]
[ride11:96460] [ 2] /home/projects/pwr8-rhel73-lsf/gcc/5.4.0/lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x1f4)[0x10000e4eb174]
[ride11:96460] [ 3] /home/projects/pwr8-rhel73-lsf/gcc/5.4.0/lib64/libstdc++.so.6(+0xa7b44)[0x10000e4e7b44]
[ride11:96460] [ 4] /home/projects/pwr8-rhel73-lsf/gcc/5.4.0/lib64/libstdc++.so.6(+0xa61c8)[0x10000e4e61c8]
[ride11:96460] [ 5] /home/projects/pwr8-rhel73-lsf/gcc/5.4.0/lib64/libstdc++.so.6(__gxx_personality_v0+0x2b8)[0x10000e4e7078]
[ride11:96460] [ 6] /home/projects/pwr8-rhel73-lsf/gcc/5.4.0/lib64/libgcc_s.so.1(+0xbc54)[0x10000e87bc54]
[ride11:96460] [ 7] /home/projects/pwr8-rhel73-lsf/gcc/5.4.0/lib64/libgcc_s.so.1(_Unwind_Resume+0x174)[0x10000e87c844]
[ride11:96460] [ 8] /home/ikalash/nightlyCDash/build/AlbBuild/src/Albany(_ZN6Kokkos4Impl25cuda_internal_error_throwE9cudaErrorPKcS3_i+0x5e0)[0x15b9c400]
[ride11:96460] [ 9] /home/ikalash/nightlyCDash/build/AlbBuild/src/Albany(_ZN6Sacado3Fad4DFadIdED1Ev+0x68)[0x126a70a8]
[ride11:96460] [10] /lib64/libc.so.6(+0x435a4)[0x10000e6835a4]
[ride11:96460] [11] /lib64/libc.so.6(exit+0x24)[0x10000e6835f4]
[ride11:96460] [12] /lib64/libc.so.6(+0x24708)[0x10000e664708]
[ride11:96460] [13] /lib64/libc.so.6(__libc_start_main+0xc4)[0x10000e6648f4]
[ride11:96460] *** End of error message ***
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaFree(m) error( cudaErrorCudartUnloading): driver shutting down /home/ikalash/nightlyCDash/build/TrilinosInstall/include/Sacado_DynamicArrayTraits.hpp:172
Traceback functionality not available

(see http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=2628151&build=47923 on the Sandia SRN CDash for more details).  This seems to be related to UVM not playing nicely with statics, perhaps the fact that cleaning up of statics depends on the link order with UVM.

**Comment by etphipp** [comment]
Is there a static Fad object somewhere?  It appears to be trying to delete the derivative data after UVM has been shut down.

**Comment by ikalash** [comment]
There very well could be somewhere, but @jewatkins and I had a hard time figuring out where -- we think it might be in Trilinos, not Albany (is that possible?).  I am actually visiting CSRI this week; if you are around tomorrow (and ride is back up), maybe we could look at it together?

**Comment by etphipp** [comment]
I'm not sure if I will be in tomorrow or not.  I will let you know if I am.

**Comment by ikalash** [comment]
Sounds good.

**Comment by ikalash** [comment]
This issue was occurring only for tests running with the Albany (Epetra) executable.  It was verified that the same tests ran fine w/ the AlbanyT executable, suggesting the problem had to do with Epetra + CUDA not playing nicely together.  In fact, they are not meant to play nicely together necessarily, and the user should not be running the Epetra Albany executables with CUDA.  A fatal error will be thrown when trying to build Albany w/ Epetra + CUDA KokkosNode following a commit I made today.
