### ISSUE TITLE
Set up LCM CDash tests for procyon, proxima, antares and spica machines

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#57]
I will do this, once @lxmota has a chance to clean up the algol CDash tests I created to use the modules on the various LCM machines.

**Comment by ikalash** [comment]
@lxmota , can you please modify your cronjob on algol to execute the CDash scripts I created there when you get the chance?  I noticed that that machine has not been pushing results to the CDash site, I think b/c the job was never turned on.  Thanks.

**Comment by lxmota** [comment]
@ikalash Ys, I still have to do this. I want to make it so it works for Trilinos as well.

**Comment by ikalash** [comment]
Ok.  The scripts I wrote currently will build both Trilinos and Albany, then run Albany scripts.  Your cronjob script should just have: 

cd /home/lcm/LCM/nightlyCDash
bash nightly_cron_script_LCMrelease.sh

The scripts assume there is already a Trilinos and Albany checked out here: /home/lcm/LCM .  It's worth trying to clean up the scripts to load all the paths from your modules, rather than have them hard-coded in ctest_nightly.cmake.frag.

**Comment by ibaned** [comment]
I'm trying to write CMake versions of the LCM build scripts in this branch:
https://github.com/gahansen/Albany/tree/lcm-cdash
its taking some time though.

**Comment by ikalash** [comment]
@lxmota, can we close this issue?  It looks like there are nightly tests for proxima and algol.  My guess is this is sufficient since the other machines are very similar (same OS, TPLs, etc.).

**Comment by lxmota** [comment]
Yes! It went under the radar.
