### ISSUE TITLE
backlog software

### ISSUE THREAD

**Issue by jtostie** [gahansen/Albany#6]
As a developer, I want to incorporate a system to track stories in a backlog

**Comment by jgfouca** [comment]
SEMS team offers Jira.

**Comment by agsalin** [comment]
waffle.io is an option

**Comment by jtostie** [comment]
zube.io also might work and integrates pretty easily with GitHub Issues. Seems similar.

**Comment by jtostie** [comment]
Jim, thanks for the info!

**Comment by ibaned** [comment]
for what its worth, I've started using waffle.io to track my Albany work.

**Comment by ibaned** [comment]
seems like Github themselves just released an alternative:

https://github.com/gahansen/Albany/projects/1

**Comment by jtostie** [comment]
Thanks @ibaned.

I have looked at waffle.io and zube.io, which are nice. Since each of these works through the GitHub Issues, I don't think it will matter much. I will keep this open so that we can track experiences in this thread.

**Comment by gahansen** [comment]
Jake, did you get a chance to look at the new Github approach that @ibaned mentioned in his Sep 15 comment? What would be your thoughts on the project diving in and trying that for a while to see how it works for us?

**Comment by ibaned** [comment]
I've set up a few more projects in a way that will probably work well here:

https://github.com/gahansen/Albany/projects

I think what I'll do is close this issue in the near future, to be reopened if this initial approach runs into trouble.

**Comment by jtostie** [comment]
@ibaned, I agree with this.
