### ISSUE TITLE
Remove "-w" from Albany CFLAGS in dashboards

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#62]
Currently several dashboards configure Trilinos with the "-w" flag which silences all warnings, and Albany automatically uses the same CFLAGS as Trilinos. What I'd like is for compiler warnings in Albany to show up, because if they had then issue #34 would have been caught much earlier. That means either allowing warnings in both Trilinos and Albany or overriding the flags for Albany.

@gahansen thoughts ?

**Comment by bartgol** [comment]
Agreed.

**Comment by lxmota** [comment]
Agreed 10X.

**Comment by ibaned** [comment]
I think this is done now, at least for the public dashboard.
