### ISSUE TITLE
some CDash builds can't find Piro

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#71]
The `IKTAlbany32BitNoEpetra` and `IKTAlbanyFunctorOpenMP` builds both report that Piro could not be found. @ikalash can you look into this ? Otherwise I could do it but I'd need access to the machine.

**Comment by ikalash** [comment]
I always fix my nightlies if they fail.  When it says "Piro not found", it means Trilinos was not done building at the time my scripts tried to build Albany.  For some reason, it took forever to check out Trilinos last night, so it was not fully built when some of my Albany builds started.  I just tried it now and it checked out fast, as usual.  I am guessing there may have been a network issue at SNL/CA last night at the time my jobs started.

**Comment by ibaned** [comment]
oh okay... I didn't know they were separate cron jobs...
