### ISSUE TITLE
Enable Yaml input

### ISSUE THREAD

**Issue by lxmota** [gahansen/Albany#74]
Enabling Yaml input in Albany will significantly improve the readability of input files.

All input in Albany is done through Teuchos ParameterLists, which already support Yaml parsing provided that Trilinos is compiled with TeuchosCore_ENABLE_yaml-cpp:BOOL=ON.

**Comment by lxmota** [comment]
Added support for Yaml input for LCM. Other applications can easily use this. See commit message above. Leaving issue open for the time being just in case.

**Comment by ibaned** [comment]
@lxmota thank you for doing this !
It did cause a few compile issues though, mostly because Teuchos did things in a non-standard way:

http://my.cdash.org/index.php?project=Albany&date=2017-02-25

I think I have fixed this in 5be9b58.

**Comment by lxmota** [comment]
Thanks for fixing the YAML detection code.

**Comment by lxmota** [comment]
I'm closing this one as duplicate of #21. The discussion should continue there.
