### ISSUE TITLE
Remove extraneous TpetraBuild global bool variable

### ISSUE THREAD

**Issue by lxmota** [gahansen/Albany#75]
This global variable pollutes all executables even when they have nothing to do with Tpetra/Epetra.

At least I'll try to get rid of it from LCM executables.

**Comment by bartgol** [comment]
I believe this is now solved. Should we close?

**Comment by tjfulle** [comment]
I believe #261 makes this issue obsolete.

**Comment by bartgol** [comment]
Agreed. Closing.
