### ISSUE TITLE
Transition to Intrepid2 refactor code

### ISSUE THREAD

**Issue by rppawlo** [gahansen/Albany#78]
Is Albany completely switched over to the intrepid2 refactor branch? We see a ton of warnings on cuda builds of phalanx and to fix these I need to get rid of the KOKKOS_FORCEINLINE_FUNCTION macros on the MDField ctors. We needed these for the original Intrepid2 design where temporary MDFields were constructed on device. But the refactor branch uses the DynRankView directly so we should be able to make the switch. I've tested the code against all applications except Albany and everything is passing. Can I push this change? Does anyone want to test Albany first? The changes are in my github repo (rppawlo/Trilinos) on the branch cuda_warnings_1123. 

This commit also changes the default index type in phalanx from uint to int to improve performance on cuda. It is a compile time parameter in phalanx so you can switch the type at configure if you still want UINT.

**Comment by ibaned** [comment]
I think the answer is yes (I always build it with the refactored Intrepid2), but the probably @mperego is the best person to answer definitively.

**Comment by mperego** [comment]
I agree. I think it is safe enough for you to push the change.

**Comment by rppawlo** [comment]
great! Thanks!
