### ISSUE TITLE
FELIX failing comparisons

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#82]
Beginning 3/14/17, FELIX tests in Irina's nightly builds began failing due to failed comparisons:

http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlyfailed&buildid=49805

I believe this has to do with Dan's push to Albany to correct the problem that regression comparisons were not being made.

**Comment by mperego** [comment]
These failings are unrelated with Dan's commit, and they appeared as a consequence of Trilinos commit 83cc5d0. 
Albany commit 7211eae4e should fix the issue.

**Comment by ibaned** [comment]
@mperego Thanks for figuring this out !
I just updated your comment so it will link to the Trilinos commit.

**Comment by mperego** [comment]
Thanks!
