### ISSUE TITLE
Stop using globs in CMakeLists

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#87]
see the [NOTE](https://cmake.org/cmake/help/v3.3/command/file.html?highlight=glob) in the CMake documentation, replicated here:

```
Note: We do not recommend using GLOB to collect a list of source files from your source tree. If no CMakeLists.txt file changes when a source is added or removed then the generated build system cannot know when to ask CMake to regenerate.
```

This recently affected Trilinos when a new header file was added. As a best practice, we should replace any use of globs in Albany with explicit lists of files.

**Comment by jtostie** [comment]
I am responsible for some of this in LCM (maybe that's the only place it happens, I don't know). I get the point that the CMake documentation is making. For historical context, my motivation was usability and efficiency, as the Albany configuration step was easier and cheaper than having to touch the CMake files.

I wold not be opposed if someone removed the GLOBs.

**Comment by ibaned** [comment]
done with this for now.

**Comment by ibaned** [comment]
By the way, I just found out Tpetra has a really funny way of dealing with this:

https://github.com/mhoemmen/Trilinos/blob/e65e32851308f68158928cfc2bd8e0518df379a4/packages/tpetra/core/src/CMakeLists.txt#L368
