### ISSUE TITLE
Internal Compiler Errors gcc 4.7.2

### ISSUE THREAD

**Issue by bgranzow** [gahansen/Albany#9]
Hello!

I am compiling Albany at this SHA: da7c212
using the gcc compiler: powerpc64-bgq-linux-g++ (BGQ-V1R2M4-160620) 4.7.2
on a BlueGene/Q system

When compiling, I receive the following three warnings :

(1) J2MiniSolver.hpp:85:8: warning: inline function ‘void LCM::J2MiniKernel<EvalT, Traits>::operator()(int, int) const [with EvalT = PHAL::AlbanyTraits::DistParamDeriv; Traits = PHAL::AlbanyTraits]’ used but never defined [enabled by default]

(2 )ParallelNeohookeanModel.hpp:64:8: warning: inline function ‘void LCM::NeohookeanKernel<EvalT, Traits>::operator()(int, int) const [with EvalT = PHAL::AlbanyTraits::Residual; Traits = PHAL::AlbanyTraits]’ used but never defined [enabled by default]

(3) CrystalPlasticityModel.hpp:81:8: warning: inline function ‘void LCM::CrystalPlasticityKernel<EvalT, Traits>::operator()(int, int) const [with EvalT = PHAL::AlbanyTraits::Jacobian; Traits = PHAL::AlbanyTraits]’ used but never defined [enabled by default]

and then the gcc compiler seg-faults with the error message:

ConstitutiveModelInterface.cpp: In lambda function:
ConstitutiveModelInterface.cpp:12:1: internal compiler error: in get_expr_operands, at tree-ssa-operands.c:1035

It think that this may be a known issue with the gcc 4.7 compiler:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53137

When I comment out code related to these  three constitutive models (J2MiniSolver, CrystalPlasticity, and ParallelNeohookean) in the ConstitutiveModelInterface, the Albany build completes successfully.

This is really a machine specific issue, as the Albany source is valid C++11 and is known to compile and run successfully with more recent compilers, however it is very unlikely that the compiler on the system I am using will be updated anytime in the near future.

I see two potential options :
(1) I carry on commenting out models that trigger this compiler bug, or perhaps keep a second branch of Albany in parallel to this one
(2) Optionally enable these constitutive models via CMake

Does anyone have any thoughts on this? Thanks for the input!

**Comment by jtostie** [comment]
Hi Brian,

My initial reaction is that we should pursue option (2) above. The features in these models that are causing issues were added in our effort to move towards kokkos compatibility. It seems like we could create a flag based on known compiler versions.

I don't like the fact that you have to comment out code to get things to compile.

Any other thoughts @lxmota ?

**Comment by lxmota** [comment]
Yes, I agree that the preferred option is (2).

**Comment by jtostie** [comment]
Brian, as per our conversation today, go ahead and take a stab at providing an internal flag and appropriate code guards. Please let me know if you encounter any issues.

**Comment by bgranzow** [comment]
Hi Jake.  This commit
https://github.com/bgranzow/Albany/commit/a852c9d3398de7cc6a10bf9006e60ef9601aa78c
on my fork of Albany seems to have resolved the issues for me, while not adversely affecting normal Albany builds.

Specifying -D DISABLE_LAMBDAS=ON in the Albany config script optionally disables the three models which were problematic with the gcc 4.7.2. compiler. The variable defaults to OFF and should maintain the previous behavior by default.

This is a pretty easy fix to apply, but it might make the upcoming merges we discussed more difficult than they need to be.  My plan is to hold off applying these changes until those merges are complete. Sound reasonable?

**Comment by jtostie** [comment]
Hi Brian, looks good to me, and what you suggest sounds reasonable. When the upcoming kokkos related merges occur in the LCM source, we can test and hopefully close this issue.

**Comment by ibaned** [comment]
@bgranzow says w.r.t. 3a53f55:
> Unfortunately, these changes did not resolve the error associated with #9 when I compiled at this ocmmit 64558eb.

My guess is this has more to do with how `ParallelConstitutiveModel<...>::computeStateParallel(...)` is implemented, not really how it was instantiated.

**Comment by ibaned** [comment]
@branzow here is another attempted fix for you to try: efa6968. Its in the `dont_capture_this` branch. Since the compiler bug has to do with a lambda capturing the `this` pointer, I tried to avoid doing that.

**Comment by bgranzow** [comment]
The 'dont_capture_this' branch compiles without any warnings, and is more correct than the workarounds I suggested. I'm marking this issue fixed, even though the changes need to be merged.

Thanks @ibaned!
