### ISSUE TITLE
CEE LAN build fails because it can't find YAML

### ISSUE THREAD

**Issue by jtostie** [gahansen/Albany#93]
Using the LCM environment tools I do the following:

% source Albany/doc/LCM/build/modules-sems.sh
% module load serial-gcc-release
% ./clean-config-build.sh trilinos 20

I get the following:

(...configuration stuff...)
Processing enabled TPL: yaml-cpp (enabled explicitly, disable with -DTPL_ENABLE_yaml-cpp=OFF)
-- Searching for libs in yaml-cpp_LIBRARY_DIRS=''
-- Searching for a lib in the set "yaml-cpp":
--   Searching for lib 'yaml-cpp' ...
-- ERROR: Did not find a lib in the lib set "yaml-cpp" for the TPL 'yaml-cpp'!
-- ERROR: Could not find the libraries for the TPL 'yaml-cpp'!
-- TIP: If the TPL 'yaml-cpp' is on your system then you can set:
     -Dyaml-cpp_LIBRARY_DIRS='<dir0>;<dir1>;...'
   to point to the directories where these libraries may be found.
   Or, just set:
     -DTPL_yaml-cpp_LIBRARIES='<path-to-libs0>;<path-to-libs1>;...'
   to point to the full paths for the libraries which will
   bypass any search for libraries and these libraries will be used without
   question in the build.  (But this will result in a build-time error
   if not all of the necessary symbols are found.)
-- ERROR: Failed finding all of the parts of TPL 'yaml-cpp' (see above), Aborting!

-- NOTE: The find module file for this failed TPL 'yaml-cpp' is:
     /gpfs1/jtostie/LCM/Trilinos/cmake/TPLs/FindTPLyaml-cpp.cmake
   which is pointed to in the file:
     /gpfs1/jtostie/LCM/Trilinos/TPLsList.cmake

TIP: Even though the TPL 'yaml-cpp' was explicitly enabled in input,
it can be disabled with:
  -DTPL_ENABLE_yaml-cpp=OFF
which will disable it and will recursively disable all of the
downstream packages that have required dependencies on it.
When you reconfigure, just grep the cmake stdout for 'yaml-cpp'
and then follow the disables that occur as a result to see what impact
this TPL disable has on the configuration of Trilinos.

CMake Error at cmake/tribits/core/package_arch/TribitsProcessEnabledTpl.cmake:127 (MESSAGE):
  ERROR: TPL_yaml-cpp_NOT_FOUND=TRUE, aborting!
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1644 (TRIBITS_PROCESS_ENABLED_TPL)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:202 (TRIBITS_PROCESS_ENABLED_TPLS)
  cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:93 (TRIBITS_PROJECT)

**Comment by jtostie** [comment]
Note: I get the same thing if I do the following

% module load cee_serial-gcc-release

**Comment by ibaned** [comment]
@jtostie  I'm closing in on the source of this... could you send a bit more info ? These would be great:
1. the full configure output
2. the contents of the `clean-config-build.sh` script
3. where the `serial-gcc-release` module comes from

**Comment by jtostie** [comment]
Hi @ibaned,

Going backwards, `serial-gcc-release` comes from `Albany/doc/LCM/modulefiles`
Also, 1. and 2. can be found in the attached.
[ccb.txt](https://github.com/gahansen/Albany/files/868698/ccb.txt)

**Comment by ibaned** [comment]
Thanks !
I found the module, but `ccb.txt` seems truncated. It only has 26 lines.

**Comment by jtostie** [comment]
Sorry about that (typo in my redirect). Try this one.
[ccb.txt](https://github.com/gahansen/Albany/files/868765/ccb.txt)

**Comment by ibaned** [comment]
Okay, I see the configure output, which is good.
I'm surprised that it says:
```
-- Trilinos_USE_BUILD_ENV=''
```
instead of
```
-- Trilinos_USE_BUILD_ENV='SEMS'
```
as it does when I use the `checkin-test-sems.sh` script from Trilinos.
I probably still need your `clean-config-build.sh` script though to know how your setup is supposed to work.

**Comment by jtostie** [comment]
Well, I just tried to add 
`-- Trilinos_USE_BUILD_ENV='SEMS'`
to the config script, but that didn't solve the issue.

`clean-config-build.sh` are all defined in
`Albany/doc/LCM/build/build.sh`

@lxmota is probably the right point of contact.

**Comment by lxmota** [comment]
Yes, the LCM build script is in

`Albany/doc/LCM/build/build.sh`

that script reads the Trilinos configuration from

`Albany/doc/LCM/build/trilinos-config.sh`

and the Albany configuration from

`Albany/doc/LCM/build/albany-config.sh`

perhaps introducing `Trilinos_USE_BUILD_ENV='SEMS'` into `trilinos-config.sh` will help.

Let me know how I can help with this.

**Comment by ibaned** [comment]
Just as a note to myself, I suspect there is something missing in this file:
cmake/std/sems/SEMSDevEnv.cmake
That is just speculation right now, I haven't gotten back to this yet.

**Comment by jtostie** [comment]
@lxmota, note that I already tried to include the `Trilinos_USE_BUILD_ENV='SEMS'` without success.

**Comment by ibaned** [comment]
There are a lot of confusing things about these scripts.
It looks like you're supposed to have an `$LCM_DIR` like this:
`$LCM_DIR/Albany`
`$LCM_DIR/Albany.wiki`
`$LCM_DIR/Trilinos`
I set that up with git clone. so far so good.
I then do the following setup from inside `$LCM_DIR`:
```bash
source Albany/doc/LCM/build/modules-sems.sh
export LCM_DIR=$PWD;
export MODULEPATH=$MODULEPATH:$LCM_DIR/Albany/doc/LCM/modulefiles
```
I tried several ways of constructing `clean-config-build.sh`, for sake of discussion lets say I did this:
```bash
ln -s Albany/doc/LCM/build/build.sh clean-config-build.sh
```
Now I try to run it:
```bash
[daibane@cee-build012 LCM]$ ./clean-config-build.sh trilinos 8
./clean-config-build.sh: line 3: ./env-single.sh: No such file or directory
```
Similarly, inside `Albany/doc/LCM/build/env-single.sh there is the line:
```bash
export LCM_DIR=`pwd`
```
So it seems like the scripts in `Albany/doc/LCM/build/` actually want to be run in `$LCM_DIR`.... should I copy them over there ?
Can someone please explain in more detail how one is supposed to setup this environment ?

**Comment by calleman21** [comment]
@lxmota can give you more details, but if you run Albany/doc/LCM/install/albany-lcm-symlinks.sh in $LCM_DIR, that should get you set up properly. There are some instructions in Albany/doc/LCM/install/INSTALL.pdf

**Comment by ibaned** [comment]
Thanks @calleman21 !

**Comment by ibaned** [comment]
With those helpful pointers I finally replicated @jtostie 's error.

**Comment by lxmota** [comment]
@ibaned Sorry I forgot to give more specific instructions and for the confusion that this caused. @calleman21 thanks for the help.

The definitive source documenting the usage of those scripts, as @calleman21, pointed out is:

`https://github.com/gahansen/Albany/blob/master/doc/LCM/install/INSTALL.pdf`

**Comment by ibaned** [comment]
I believe I've made some progress and Trilinos is now compiling for me. One thing I noticed is that these scripts really didn't used the loaded SEMS modules at all, i.e. things like Boost and Netcdf were still being found in places like `/usr/lib64`. I've made some local changes to the scripts so that everything is based off the SEMS environment. If that sounds like something acceptable to existing users of these scripts, I can push those once I confirm the build finishes.

**Comment by lxmota** [comment]
@ibaned By all means feel free to make changes to the scripts. I would just request that the modifications are such that they can still be used on our Fedora environment. You should still have an account on our Algol machine to test this. The idea is that we use the scripts on both our Fedora environment and SEMS. Hopefully this won't be too difficult, but let me know if you need help.

To be able to use the scripts both in SEMS and in our environment, @calleman21 created separate module files for the SEMS environment. All these module files are in

`https://github.com/gahansen/Albany/tree/master/doc/LCM/modulefiles`

As you can see there, the number of module files has exploded beyond control, so sooner or later I will have to think about a way to reduce their number. But in the meantime, we could create separate modules for the SEMS environment as @calleman21 started to do with the `cee_serial-gcc-*` module files.

As described in the `https://github.com/gahansen/Albany/blob/master/doc/LCM/install/INSTALL.pdf` guide mentioned above, the idea is that one can keep many builds at the same time by loading the appropriate module. For instance, `module load openmp-gcc-debug` would prepare the environment and create separate build directories for Trilinos and Albany to be compiled with GCC using OpenMP in debug mode. Likewise, `module load serial-clang-release` would be needed to compile single-thread versions with Clang in release mode and so on.

**Comment by ibaned** [comment]
I'll make the assumption that CEE machines always use SEMS and see if I can make my changes portable.

**Comment by lxmota** [comment]
I think that is a reasonable assumption for this.

**Comment by ibaned** [comment]
By the way, where would I find `yaml-cpp` on a Fedora system ?

**Comment by lxmota** [comment]
`/usr/include/yaml-cpp` for headers
`/usr/lib64` for libraries on a 64-bit system

**Comment by ibaned** [comment]
Okay, I'm done with a big refactor of these scripts (mainly the modules). Please see #101 and comment what you think. This should resolve YAML issues on both platforms.

**Comment by ibaned** [comment]
#101 has been merged. I think I closed this too quickly.

@jtostie please try with the new modules. The workflow is now:
```bash
module load lcm/sems
module load serial-gcc-release
./clean-config-build.sh trilinos 20
```

**Comment by lxmota** [comment]
It works for me on the CEE LAN. I just did:

```
module load lcm/sems
module load release
```

And currently the Albany tests are running.

**Comment by jtostie** [comment]
This works for me as well. The Albany tests are running.

**Comment by ibaned** [comment]
Excellent ! I'll close this again. Please open a separate issue if something goes wrong with the new scripts.
