### ISSUE TITLE
Some crystal plasticity tests failing after conversion from XML to YAML

### ISSUE THREAD

**Issue by lxmota** [gahansen/Albany#95]
@calleman21 @jwfoulk @jtostie 

Please help me fix the CP failing tests after the conversion from XML to YAML. Some of them appear to fail because of differences in the exodus files. It appears that the XML to YAML conversion introduced some slight variations in the solutions due to changes in the floating point representation of some parameters, but I'm not completely sure.

The failing tests are:
	  5 - CrystalPlasticity_ElasticShear2d_Tpetra (Failed)
	  6 - CrystalPlasticity_PlasticShear2d_Tpetra (Failed)
	  7 - CrystalPlasticity_ElasticShear3d_Tpetra (Failed)
	  8 - CrystalPlasticity_ElasticShearRotated3d_Tpetra (Failed)
	  9 - CrystalPlasticity_SingleSlip_Explicit_Tpetra (Failed)
	 10 - CrystalPlasticity_SingleSlip_Implicit_Tpetra (Failed)
	 11 - CrystalPlasticity_SingleSlipHard_Explicit_Tpetra (Failed)
	 12 - CrystalPlasticity_SingleSlipHard_Implicit_Tpetra (Failed)
	 13 - CrystalPlasticity_SingleSlipHardMinusRecovery_Implicit_Tpetra (Failed)
	 17 - CrystalPlasticity_SingleSlipOffKilterLoading_Tpetra (Failed)
	 27 - CrystalPlasticity_QuadSlip (Failed)
	 28 - CrystalPlasticity_DislocationDensityHardening (Failed)
	 29 - CrystalPlasticity_MultiFamily (Failed)
	 30 - CrystalPlasticity_ThermallyActivatedSlip (Failed)
	 31 - ScharzBarCPMatrixFree_np1 (Failed)
	 32 - ScharzBarCPModified_np1 (Failed)
	 46 - CrystalPlasticity_MPS (Failed)

**Comment by jtostie** [comment]
In order to help I need resolution to #93.

**Comment by jtostie** [comment]
Also, philosophically, I think it's bad practice to push a change that breaks tests.

**Comment by calleman21** [comment]
I have verified that at least one test fails due to changes in floating point representation. @lxmota can the conversion process be done so that the precision is maintained? Also, the xml comments seem to have been deleted in the conversion process. Does the converter have the capability to convert these to yaml comments? Otherwise, the conversion undoes a significant amount of work that went into documenting the tests.

**Comment by lxmota** [comment]
I'll revert the conversion as it has many failing tests.

**Comment by lxmota** [comment]
OK, @calleman21 asked not to revert the conversion for crystal plasticity. Unfortunately, that means that the conversion will stand, because it would extremely difficult to disentangle it from the rest.

**Comment by lxmota** [comment]
@jtostie Guilty as charged. I agree that it's bad practice. Unfortunately I didn't see any other way to move things forward quickly. Of course, I could be very wrong about that.

@calleman21 I'm not sure that the floating point precision or the comments can be preserved. Maybe @ibaned can comment about this?

**Comment by ibaned** [comment]
I did worry about the floating-point precision when I saw the original code. I think we may be able to do  something about that. I have no idea for comments; the trouble is that these converters are based on the intermediate representation of a `Teuchos::ParameterList`, so anything that doesn't get stored in that object is forgotten.

@calleman21 can you point to one representative example of before/after floating point values that broke the test ?

**Comment by ibaned** [comment]
@calleman21 nevermind about the example, I'll just look over your commit 5e8ded1

**Comment by calleman21** [comment]
@ibaned To help speed up your search, tests/large/LCM/CrystalPlasticity/DislocationDensityHardening/ is such a test.

**Comment by ibaned** [comment]
@calleman21  I see several values that lose a lot of precision. I think I can raise the floating-point precision in the YAML writer, that code change for that should be easy. I'll try to do it soon and mention my status in this thread.
Comments, however, will likely require a lot more work. I'll look through what is supported by the various pieces of code to see if there is a way forward.

**Comment by lxmota** [comment]
I would recommend that when writing floating point values in ASCII form to use 16 digits of precision. That would always cover the double precision case which seems to be the format of choice for the foreseeable future.

https://en.wikipedia.org/wiki/IEEE_floating_point#Basic_and_interchange_formats

**Comment by ibaned** [comment]
Yep, thats what I did. The basic change was easy, and has been submitted as trilinos/Trilinos#1181. The good news is that we should not have to wait for the full merge into master, because the converters are not part of the testing process. If you want to repair your YAML files, please checkout the branch referenced in trilinos/Trilinos#1181 and use that to compile Albany and the converters, then run the converters.

**Comment by lxmota** [comment]
The commit https://github.com/gahansen/Albany/commit/c3fa89d61b3bc9d219a8fcec0fedf9bb27940dba fixes this. All CP tests pass now. Thanks @calleman21 for helping with this!

**Comment by ibaned** [comment]
I think having high-precision XML->YAML conversion is still important.
I've revised trilinos/Trilinos#1181 with feedback from the Teuchos team and it should be close to acceptance. As before, if you build Trilinos with the changes from the Pull Request and then build the Albany `xml2yaml` program, it should output YAML values with 17 digits of precision.
