### ISSUE TITLE
HMC test does not run after conversion from XML to YAML

### ISSUE THREAD

**Issue by lxmota** [gahansen/Albany#96]
@jrobbin Please help me fix the HMC test that refuses to run after converting all LCM inputs from XML to YAML to improve usability. I had to temporarily deactivate the tests because it appears to be caught in some sort of infinite loop. See the discussion about the conversion from XML to YAML here:
https://github.com/gahansen/Albany/issues/21

**Comment by lxmota** [comment]
I'll revert the conversion as it has many failing tests.

**Comment by lxmota** [comment]
@jrobbin Now I'm asked to keep and not revert the conversion, so the issue stands.

**Comment by ikalash** [comment]
Can this issue be closed?

**Comment by lxmota** [comment]
I'll close it because I never got a reply and that test has been deactivated for more that a year.
