### ISSUE TITLE
undefined references when building Albany without Rythmos

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#99]
I recently switched my nightly tests to build shared libraries; prior to this, I was always building static.  It appears there is an undefined reference error when building a no-Epetra Albany with shared libs; please see http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=50619 .  It seems to be looking for classes that are Epetra-only, e.g., Albany::RythmosObserver.  My guess is no one besides me has no-Epetra builds, and so the issue has not been encountered.  @ibaned , I am going on foreign travel at the end of the week.  Would you mind trying to have a look at this while I am away?  Until the issue is fixed, my no-Epetra tests will fail, unless I switch them back to statically linked.  @lxmota : I reproduced the issue on algol, so I don't think this is specific to my machine.

**Comment by ibaned** [comment]
Interesting... @bgranzow recently reported undefined reference errors, but only when building statically. I used to maintain an Epetra-free build, until I had to bring in Epetra for ATO and Aeras :)

@bgranzow could you post the errors you had if they're handy somewhere ? I'd like to see if they're connected.

**Comment by bgranzow** [comment]
@ibaned, I didn't save the errors. I'll rebuild Trilinos with static libs and see if I can reproduce the error.

**Comment by ibaned** [comment]
Updating the link because the one already posted actually is about #100:

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=50674

The errors are basically about RhythmosObserver:

`../libalbanyLib.so: undefined reference to `Albany_RythmosObserver::Albany_RythmosObserver(Teuchos::RCP const&)`

**Comment by ibaned** [comment]
I think this issue is actually about not having Rythmos, which according to the Trilinos CMake files does *not* require Epetra necessarily. I was able to build Trilinos with Rythmos and without Epetra.

**Comment by ibaned** [comment]
Hmm maybe not quite... Albany fails to find header files when Rythmos is gone, at least I just fixed that.

**Comment by ikalash** [comment]
Thanks for looking at this, Dan.  I have Rythmos on in my Trilinos build, actually.  It is needed for Aeras, so I still build with it.

**Comment by ibaned** [comment]
Yep, retrying with Rythmos on.

**Comment by ibaned** [comment]
Okay, I think I've pushed a fix for this. I'll close it for now, we can reopen if we see the same failure again.

**Comment by ikalash** [comment]
Thanks for working on this Dan!  I just tried a clean build, and it looks like there are still problems having to do with Albany::RythmosObserver though, but different than before.  Please see http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=50729 .

**Comment by ibaned** [comment]
yep, looks like I missed one. hopefully commit 38d3336 clears this up...

**Comment by ikalash** [comment]
Thanks, Dan.  There was another issue preventing the shared libs no-Epetra build having to do with the NOX::Observer, which I just pushed a fix to (afd9f6a24d6331d7095584c157e7e3bd541d3422) .  With your fixes and that one, my no-Epetra tests seem to be back up.
